### ISSUE TITLE
Reconnection connection error

### ISSUE THREAD

**Issue by thiru1010** [pedroSG94/rtmp-rtsp-stream-client-java#1018]
When am switch off wifi and turn on wifi reconnect not happen. It's showing connection error. 

 java.net.SocketException: socket is closed
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:551)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:288)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
        at com.pedro.rtmp.utils.UtilsKt.readUntil(Utils.kt:29)
        at com.pedro.rtmp.rtmp.message.RtmpMessage$Companion.getInputWithoutChunks(RtmpMessage.kt:97)
        at com.pedro.rtmp.rtmp.message.RtmpMessage$Companion.getRtmpMessage(RtmpMessage.kt:73)
        at com.pedro.rtmp.rtmp.CommandsManager.readMessageResponse(CommandsManager.kt:167)
        at com.pedro.rtmp.rtmp.RtmpClient.handleMessages(RtmpClient.kt:293)
        at com.pedro.rtmp.rtmp.RtmpClient.connect$lambda-0(RtmpClient.kt:196)
        at com.pedro.rtmp.rtmp.RtmpClient.lambda$2Ex0pWOcGVHPFRJWQRhtgifpZyQ(Unknown Source:0)
        at com.pedro.rtmp.rtmp.-$$Lambda$RtmpClient$2Ex0pWOcGVHPFRJWQRhtgifpZyQ.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

Note: After 1 to 2 mins reconnect success

**Comment by pedroSG94** [comment]
Hello,

In few servers by default the connection works a bit different that expected in this library because the server keep the connection alive few seconds until it is automatically disconnect and then you can restream to that endpoint.

It is the case for Nginx rtmp server that, for example, need a configuration to release reconnection instead of wait. This is the configuration recommended for nginx in this case:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/629

It is working as expected and should be fixed in server side because in Android you can for example change from wifi to 4G data and you will have different IP so you can't reconnect creating only the socket instead of using a reconnection from 0.

If you have any suggestion about it let me know it and give me a way to get an enviroment to reproduce the case.

**Comment by thiru1010** [comment]
It is fixed from Nginx rtmp server thank you for your response
