### ISSUE TITLE
Xiaomi Redme not working video stream. Please help.

### ISSUE THREAD

**Issue by MasTeh** [pedroSG94/rtmp-rtsp-stream-client-java#1027]
First of all, I would like to express my gratitude to the developer of this library.
There is one problem. The video stream is working fine. But exclusively on xiaomi phones, video is not transmitted, only audio. I did everything strictly as in the examples. The latest version of the library. This problem cannot be solved.
Can you suggest what I should pay attention to and what to check? What could be the possible cause?

**Comment by pedroSG94** [comment]
Hello,

First of all I need know which mode (Camera1, Camera2, Display, FromFile) and view (SurfaceView, TextureView, OpenGlView, Context) you are using.
The first test with my app example is recommanded to help me reproduce the error so compile my app example and use the case more close to you requirement and let me know it (if you modify any line explain it in details to repoduce your case).

After that, check your logcat and share me a full logcat.

**Comment by BaloghTamas** [comment]
I believe we are facing the same issue. We are getting crash reports, 99% for Xiaomi devices, where video stream is crashing.

This is the crashlog we are obversing

```
          Fatal Exception: java.lang.IllegalArgumentException: submitRequestList:360: Invalid camera request settings
       at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1712)
       at android.hardware.camera2.impl.ICameraDeviceUserWrapper.submitRequestList(ICameraDeviceUserWrapper.java:90)
       at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:1322)
       at android.hardware.camera2.impl.CameraDeviceImpl.setRepeatingRequest(CameraDeviceImpl.java:1375)
       at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:324)
       at com.pedro.encoder.input.video.Camera2ApiManager$1.onConfigured(Camera2ApiManager.java:177)
       at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$0(CallbackProxies.java:53)
       at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.$r8$lambda$XOBHWVfryPuKTX27fDYaiDBtLvc()
       at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy$$ExternalSyntheticLambda6.run(:4)
       at android.os.Handler.handleCallback(Handler.java:958)
```

I believe the corresponding code that catches it is here: 
https://github.com/pedroSG94/RootEncoder/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.kt#L152


I suspect that some configurations here is are not respected by Xiaomi devices https://github.com/pedroSG94/RootEncoder/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.kt#L182

**Comment by pedroSG94** [comment]
Hello,

Can you tell me the library version used to debug it?

> I suspect that some configurations here is are not respected by Xiaomi devices https://github.com/pedroSG94/RootEncoder/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.kt#L182

Technically that method should be supported in all devices acording with the android documentation:
https://developer.android.com/reference/android/hardware/camera2/CaptureRequest#CONTROL_MODE

I can try remove it but I'm not sure if this will solve the problem. What do you think about remove the line, generate a gradle to test it and then you can report me back if all is fine and I add the fix to master?

**Comment by pedroSG94** [comment]
Hello,

After check the android documentation I think that the problem could be this:
https://developer.android.com/reference/android/hardware/camera2/CaptureRequest.Builder#build()

As you can see in the documentation if you try start a captureSession without a Surface target build method crash with IllegalArgumentException that is exactly your error.

Are you using Camera2Base?
I only can think that the camera2 is stopped any time and prepareCamera is not called before open the camera again 
 producing this problem. According with version 2.4.7 the camera2 is stopped in this lines:
https://github.com/pedroSG94/RootEncoder/blob/2.4.7/library/src/main/java/com/pedro/library/base/Camera2Base.java#L475
https://github.com/pedroSG94/RootEncoder/blob/2.4.7/library/src/main/java/com/pedro/library/base/Camera2Base.java#L595
https://github.com/pedroSG94/RootEncoder/blob/2.4.7/library/src/main/java/com/pedro/library/base/Camera2Base.java#L694
https://github.com/pedroSG94/RootEncoder/blob/2.4.7/library/src/main/java/com/pedro/library/base/Camera2Base.java#L698

Are you using any of that methods?
