### ISSUE TITLE
Stream crashing on some devices.

### ISSUE THREAD

**Issue by MichHighlander** [pedroSG94/rtmp-rtsp-stream-client-java#1038]
Hey pedro,
I am using your library on my Android app.
When i installed the app on my phone everything is fine, but when i install the app on a device called Tinkerboard 2S that is running Android 11, the stream stops after a few mins of running and sometimes even crashes the app.
What is the cause of this and how can i detect a potential crash or overload to the system?
Thanks.

**Comment by pedroSG94** [comment]
Hello,

I need info about this.
Using my app example to avoid code implementation errors, can you share me logcat when you have this problems? (stream stop and the crash)
Also, let me know which activity are you using and write the code if you do any modification to it.

**Comment by pedroSG94** [comment]
Hello,

First of all, you are using SrsFlvMuxer that is deprecated and replaced by RtmpClient class so I can't upload a fix for it if it is necessary. I only can try to help you fix it yourself.

- frame discarded: It is a log when you have the library buffer full because you are producing frames faster than you can send. In this case, the library discard incoming frames until you can send the old one to avoid memory problems. You can increase buffer size in SrsFlvMuxer class if needed to test. Also, I recommend you check your internet speed and packets size to know if you can send that amount of data per second using that connection.

- About crash. I can't help you without any logcat. I think that you can enable ssh, connect to it and execute adb logcat command

**Comment by MichHighlander** [comment]
Hey Pedro thanks for the quick response,
i was at version 2.0.2 so i upgraded to 2.1.5, i don't see an RtmpClient class, i only see RtmpCamera1 and RtmpCamera2, when i enter RtmpDisplay that uses RtmpClient i get a red error which says "Library source does not match the bytecode for RtmpClient" did you encounter such error?

**Comment by pedroSG94** [comment]
How are you updating it?
Did you compile library as in README?

**Comment by MichHighlander** [comment]
i am importing using:
implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:2.1.6'
in my gradle file.
I think its only as README if i implement it from the gradle.

**Comment by pedroSG94** [comment]
It is really weird because rtplibrary include rtmp, rtsp and encoder modules. Anyway you can import it one by one:
```gradle
implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:encoder:2.1.6'
implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtsp:2.1.6'
implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtmp:2.1.6'

```

**Comment by MichHighlander** [comment]
I tried it, it also doesn't work.
My project is written in Java, maybe thats the problem?

**Comment by pedroSG94** [comment]
I don't think that. I did now a project in java with Android studio (kotlin not configured, creating a project with java as default language) and it is working fine. I can import RtmpClient class without problems.

Android studio version:
```
Android Studio Arctic Fox | 2020.3.1 Patch 2
Build #AI-203.7717.56.2031.7678000, built on August 26, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.0-43-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: GLSL, org.jetbrains.kotlin
Current Desktop: ubuntu:GNOME
```

**Comment by MichHighlander** [comment]
i see so maybe its a Cacheing issue, ill try fixing it and implement the RtmpCliet class and see if it still crashes.
Again thanks for the quick responses!

**Comment by MichHighlander** [comment]
Alright so i managed to fix the problem, Android studio caching...
Now i implemented the RtmpClient and i get an error:
"Unable to convey fps info to driver, performance might be affected"
What could that mean? i pass RtmpClient.setFps and when i prepare the VideoEncoder i also pass the same FPS.

**Comment by pedroSG94** [comment]
I haven't a log like that. Can you share me a logcat?

**Comment by MichHighlander** [comment]
2022-02-01 10:40:47.246 4471-4936/com.dji.ux.execution I/RtmpSender: wrote Video packet, size 6306
2022-02-01 10:40:47.279 4471-4925/com.dji.ux.execution I/CommandsManager: read UserControl(type=PING_REQUEST, event=Event(data=-1267625720, bufferLength=-1), bodySize=6)
2022-02-01 10:40:47.280 4471-4925/com.dji.ux.execution I/CommandsManager: send pong
2022-02-01 10:40:47.357 4471-4936/com.dji.ux.execution I/RtmpSender: wrote Video packet, size 6306
2022-02-01 10:40:47.464 4471-4936/com.dji.ux.execution I/RtmpSender: wrote Video packet, size 5787
2022-02-01 10:40:47.578 4471-4936/com.dji.ux.execution I/RtmpSender: wrote Video packet, size 6262
2022-02-01 10:40:47.693 4471-4936/com.dji.ux.execution I/RtmpSender: wrote Video packet, size 6592
2022-02-01 10:40:47.808 4471-4936/com.dji.ux.execution I/RtmpSender: wrote Video packet, size 5955
2022-02-01 10:40:47.884 4471-4936/com.dji.ux.execution I/RtmpSender: wrote Video packet, size 5910
2022-02-01 10:40:47.979 4471-4936/com.dji.ux.execution I/RtmpSender: wrote Video packet, size 6588
2022-02-01 10:40:48.093 4471-4936/com.dji.ux.execution I/RtmpSender: wrote Video packet, size 6304
2022-02-01 10:40:48.120 4471-4471/com.dji.ux.execution E/koy$fdd: send to server success: Response{protocol=h2, code=200, message=, url=https://statistical-report.djiservice.org/api/report/web}
2022-02-01 10:40:48.319 4471-4925/com.dji.ux.execution I/CommandsManager: read UserControl(type=PING_REQUEST, event=Event(data=-1267624720, bufferLength=-1), bodySize=6)
2022-02-01 10:40:48.320 4471-4485/com.dji.ux.execution I/ji.ux.executio: Background concurrent copying GC freed 81154(3859KB) AllocSpace objects, 89(31MB) LOS objects, 24% free, 74MB/98MB, paused 348us total 731.614ms
2022-02-01 10:40:49.521 4471-4485/com.dji.ux.execution I/ji.ux.executio: Background young concurrent copying GC freed 45893(2200KB) AllocSpace objects, 80(28MB) LOS objects, 25% free, 71MB/95MB, paused 246us total 173.854ms
2022-02-01 10:40:50.492 4471-4471/com.dji.ux.execution D/Updates drone details: DocumentSnapshot successfully written!
2022-02-01 10:40:51.123 4471-4485/com.dji.ux.execution I/ji.ux.executio: Background concurrent copying GC freed 50758(2355KB) AllocSpace objects, 89(33MB) LOS objects, 25% free, 70MB/94MB, paused 4.891ms total 561.771ms
2022-02-01 10:40:52.362 4471-4485/com.dji.ux.execution I/ji.ux.executio: Background young concurrent copying GC freed 37708(1749KB) AllocSpace objects, 75(27MB) LOS objects, 25% free, 70MB/94MB, paused 708us total 205.186ms
2022-02-01 10:40:53.453 4471-4921/com.dji.ux.execution I/RtmpSender: Video frame discarded
2022-02-01 10:40:53.837 4471-4921/com.dji.ux.execution I/chatty: uid=10142(com.dji.ux.execution) VideoEncoder identical 3 lines
2022-02-01 10:40:53.903 4471-4921/com.dji.ux.execution I/RtmpSender: Video frame discarded
2022-02-01 10:40:53.923 4471-4471/com.dji.ux.execution D/Updates drone details: DocumentSnapshot successfully written!
2022-02-01 10:40:53.969 4471-4921/com.dji.ux.execution I/RtmpSender: Video frame discarded
2022-02-01 10:40:54.084 4471-4485/com.dji.ux.execution I/ji.ux.executio: Background concurrent copying GC freed 47280(2237KB) AllocSpace objects, 90(33MB) LOS objects, 24% free, 73MB/97MB, paused 556us total 730.229ms
2022-02-01 10:40:54.086 4471-4921/com.dji.ux.execution I/RtmpSender: Video frame discarded

**Comment by MichHighlander** [comment]
Update:
i debugged your code a bit, i looks like in the RtmpSender.kt class after a while it doesn't continue after the "size = commandsManager.sendVideoPacket(flvPacket, output)" line.
Maybe its something with the flush?

**Comment by pedroSG94** [comment]
It is weird. If write packet fail, you should receive an "Error send packet" logcat and onConnectionFailed callback.
Did you check your packet size? Maybe the packet is too large and this produce the error.
Also, According with the logcat, the library stop to send packets after this line:
```
2022-02-01 10:40:48.120 4471-4471/com.dji.ux.execution E/koy$fdd: send to server success: Response{protocol=h2, code=200, message=, url=https://statistical-report.djiservice.org/api/report/web}
```
Can you try test stream only without other features added? Try to keep the code close to app example. If possible, use app example.

**Comment by MichHighlander** [comment]
This message doesn't always show before the error.
We don't get an write packet fail, it just gets stuck.

**Comment by pedroSG94** [comment]
> We don't get an write packet fail, it just gets stuck.

I can't find a similar problem on internet and I never see a problem like this.
Since I can't reproduce your case, I only can tell you:
- Test with my library alone to discard possible problems with others things
- Try to find a logic pattern to get more info about the problem:
Check if time to hang is alway the same.
Check the amount of bytes send before hang.
Check the packet size before send to know if hang with packets of a concrect size.


> edit: this are the logs when the app crashes

I can't do so much about this crash. It should be a room crash since the problem seems to be in system files.
I recommend you post this error on the official forum and get more info about the exact problem:
https://tinker-board.asus.com/forum/

Anyway, if you want test something for now, since I can't fix it. I need to know the exact part of the library that produce this fail:
- First of all test my library alone to discard problems using other things at the same time.
- Test a stream without video. Using RtmpOnlyAudio.
- Test a stream without OpenGL using RtmpCamera1 with SurfaceView.

Let me know the result of all this tests.

**Comment by LINWAYNE** [comment]
I have same  problem, It works fine on my own phone,It's not normal on the production machine. To troubleshoot the network, I tested it on a separate network, and it still didn't work.
The program lock rtpSocketTcp sendFrame, but not throw Exception, rtpFrameBlockingQueue keeps growing , then log Video frame discarded. the rtsp server has not received any message for a long time. The socket is disconnected

**Comment by pedroSG94** [comment]
> I have same problem, It works fine on my own phone,It's not normal on the production machine. To troubleshoot the network, I tested it on a separate network, and it still didn't work.I use the OpenGlRtspActivity test. The program lock rtpSocketTcp sendFrame, `sendFrame(rtpFrame: RtpFrame, isEnableLogs: Boolean)` but not throw Exception, rtpFrameBlockingQueue keeps growing , `override fun onVideoFrameCreated(rtpFrame: RtpFrame) { try { rtpFrameBlockingQueue.add(rtpFrame) } catch (e: IllegalStateException) { Log.i(TAG, "Video frame discarded") droppedVideoFrames++ } }` then log Video frame discarded. the rtsp server has not received any message for a long time. The socket is disconnected
> 
> I/RtspSender: Video frame discarded I/RtspSender: Video frame discarded I/RtspSender: Video frame discarded I/RtspSender: Video frame discarded E/RtspSender: send error: java.net.SocketException: Broken pipe at java.net.SocketOutputStream.socketWrite0(Native Method) at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:112) at java.net.SocketOutputStream.write(SocketOutputStream.java:157) at com.pedro.rtsp.rtp.sockets.RtpSocketTcp.sendFrameTCP(RtpSocketTcp.kt:56) at com.pedro.rtsp.rtp.sockets.RtpSocketTcp.sendFrame(RtpSocketTcp.kt:42) at com.pedro.rtsp.rtsp.RtspSender.start$lambda-1(RtspSender.kt:146) at com.pedro.rtsp.rtsp.RtspSender.$r8$lambda$REgfaJG23GVv18iw0UNmQNI9r-I(RtspSender.kt) at com.pedro.rtsp.rtsp.RtspSender$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)

Hello,

Your case seems different from above.

For now, we can try this:
1 - Can you tell me device model and Android API version?
2 - Can you test streaming only audio? 
Audio only use 64kbps so if you have a low connection the audio should work. To test it you only need replace RtspCamera1 to RtspOnlyAudio class. Using the correct constructor (remove SurfaceView) and remove all code that don't exists (related to filters or video).
3 - If the audio only test is working we need to check if the problem is related with video packet size or not. We need to do this:
Check video packet size before send it to rtsp library. To do this you can check bytebuffer size of h264 packet here (using remaining method):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L1019
Check internet connection stability using an app that send a ping to your media server constantly to know if you have internet problem. Also, you can do a speed test to know if you have enougth bandwidth.
https://play.google.com/store/apps/details?id=net.WisdomStar.Ping&hl=es&gl=US
https://play.google.com/store/apps/details?id=org.zwanoo.android.speedtest&hl=es_419&gl=US
