### ISSUE TITLE
Surfaceview turned black after starting stream.

### ISSUE THREAD

**Issue by uditshoprtv** [pedroSG94/rtmp-rtsp-stream-client-java#1046]
Once I'm starting the stream if my app is going to background and again coming to the app preview is not showing and surfaceview turned black, Is there any solution for the same? I'm using MUX for streaming. Before streaming started preview is working fine if my app is going to background and again coming to the app.

Any solution?

**Comment by pedroSG94** [comment]
Hello,

Are you using Camera2? In this case ...
Did you try using OpenGlView? It is recommended for the performance and SurfaceView or TextureView with Camera2 are deprecated and could be removed in future versions.

**Comment by uditshoprtv** [comment]
I'm using SurfaceView only so mostly it will be Camera2.

Trying to implement OpenGIView.

**Comment by uditshoprtv** [comment]
Tried OpenGlView too from your example and there is nothing related if app is going to background and coming again on the scree. in OpenGlView surface is also turned black.

**Comment by pedroSG94** [comment]
Hello,

Ah ok, I understand now. Did you try using background example?
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/java/com/pedro/rtpstreamer/backgroundexample

**Comment by bv-it** [comment]
Hello,

**1. Use SurfacelView**
2. Use Camera1 
3. start stream (MUX).
 - RtmpSender: wrote Audio packet. 
 - RtmpSender: wrote Video packet
4. No errors
5. going to background and coming again
 - RtmpSender: wrote Audio packet. ONLY
6. rtmpCamera.switchCamera() (twice)
 - RtmpSender: wrote Audio packet. 
 - RtmpSender: wrote Video packet
7. No Erros 


**1. Use OpenGlView**
2. Use Camera1 
3. start stream (MUX).
 - RtmpSender: wrote Audio packet. 
 - RtmpSender: wrote Video packet
4. No errors
5. going to background and coming again
 - RtmpSender: wrote Audio packet. ONLY
6. rtmpCamera.switchCamera() 
7. Error: 
```
E/BufferQueueProducer: [SurfaceTexture-1-20193-4] connect: BufferQueue has been abandoned
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kibo.app, PID: 20193
    java.lang.RuntimeException: startPreview failed
        at android.hardware.Camera.startPreview(Native Method)
        at com.pedro.encoder.input.video.Camera1ApiManager.start(Camera1ApiManager.java:197)
        at com.pedro.encoder.input.video.Camera1ApiManager.switchCamera(Camera1ApiManager.java:420)
        at com.pedro.rtplibrary.base.Camera1Base.switchCamera(Camera1Base.java:783)
        at com.Translation_Add$4.run(Translation_Add.java:926)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by pedroSG94** [comment]
Hello,

This seems an error code.
If you want continue streaming without activity you need replace glInterface on fly to avoid video render error.
You have an example on background example activity:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/backgroundexample/BackgroundActivity.kt#L54

As you can see here (surfaceChanged and surfaceDestroyed). You must use replaceView method with context surfaceDestroyed and replaceView with openglView on surfaceChanged to use always a valid preview.

This all is with OpenGlView. Using SurfaceView, close and reopen activity while streaming is not supported. You should stop stream if activity is closed/paused and re start after open again.

**Comment by uditshoprtv** [comment]
I have implemented background example activity, there is one issue I have found once I am done with the stream coming back to the another stream camera still shows in the use. 

Reproduce steps:

come the the camera screen -> start streaming -> stop streaming -> come to the home screen and check camera is still in use.

How to release camera when come to the home screen?

**Comment by pedroSG94** [comment]
I'm not sure about the code that you implemented but the correct way to stop all should be like this:
```java
if (rtmpCamera1.isRecording()) rtmpCamera1.stopRecord();
if (rtmpCamera1.isStreaming()) rtmpCamera1.stopStream();
if (rtmpCamera1.isOnPreview()) rtmpCamera1.stopPreview();
```

**Comment by pedroSG94** [comment]
You can get supported camera resolutions using:
```java
//rear camera resolutions
rtmpCamera1.getResolutionsBack();
//front camera resolutions
rtmpCamera1.getResolutionsFront();
```
To open front camera you can use startPreview with CameraFacing parameter:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L580

**Comment by pedroSG94** [comment]
> If somehow internet connection goes off and trying to reTry but it crashes and I have to check every 5 seconds when internet connection established again need to reconnect the stream again.

Crash or you receive a connection failed? Can you share crash logcat?


> Also, If I have started streaming and user put app in background then I need to stop preview of camera and also stop audio while streaming is for user privacy, Is it possible?

I assume that you have implemented a way that allow you stream in backgroudn and you want pause both.
I recommend you use BlackFilterRender ful screen (using setSize(100f, 100f);) to send black images and disableAudio to mute microphone. You can do it on fly.

**Comment by uditshoprtv** [comment]
send error: 
    java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:117)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:140)
        at com.pedro.rtmp.rtmp.message.RtmpHeader.writeHeader(RtmpHeader.kt:121)
        at com.pedro.rtmp.rtmp.message.RtmpHeader.writeHeader(RtmpHeader.kt:112)
        at com.pedro.rtmp.rtmp.message.RtmpMessage.writeHeader(RtmpMessage.kt:118)
        at com.pedro.rtmp.rtmp.CommandsManager.sendAudioPacket(CommandsManager.kt:299)
        at com.pedro.rtmp.rtmp.RtmpSender.start$lambda-2(RtmpSender.kt:122)
        at com.pedro.rtmp.rtmp.RtmpSender.$r8$lambda$RWpSSbIll9sp_byGoOkFIfDGBxg(Unknown Source:0)
        at com.pedro.rtmp.rtmp.RtmpSender$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
2022-05-27 03:19:06.672 21552-26812/tv.shopr.user E/RtmpClient: connection error
2022-05-27 03:19:06.680 21552-26814/tv.shopr.user E/AndroidRuntime: FATAL EXCEPTION: pool-26-thread-1
    Process: tv.shopr.user, PID: 21552
    kotlin.UninitializedPropertyAccessException: lateinit property output has not been initialized
        at com.pedro.rtmp.utils.socket.TcpSocket.getOutStream(TcpSocket.kt:38)
        at com.pedro.rtmp.rtmp.CommandsManager.sendClose(CommandsManager.kt:263)
        at com.pedro.rtmp.rtmp.RtmpClient.disconnect$lambda-5(RtmpClient.kt:464)
        at com.pedro.rtmp.rtmp.RtmpClient.$r8$lambda$L6f1XZSd9tdbDvwE21RqUPtnFoA(Unknown Source:0)
        at com.pedro.rtmp.rtmp.RtmpClient$$ExternalSyntheticLambda1.run(Unknown Source:2)
        
        
        I'm seeing this in logcat in while doing retry.
        
        camera2Base?.reTry(5000, endpoint),

**Comment by pedroSG94** [comment]
Hello,

This error is already fixed in version 2.1.9 of the library. Please update library version:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/1122#event-6683968496

**Comment by uditshoprtv** [comment]
Thank you so much Pedro.

**Comment by pedroSG94** [comment]
Closing issue. If you have any problem you can re open the issue or open a new issue.
