### ISSUE TITLE
java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.

### ISSUE THREAD

**Issue by egrgdam** [pedroSG94/rtmp-rtsp-stream-client-java#105]
Partial stack:

`  java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
                                                                          at android.media.AudioRecord.startRecording(AudioRecord.java:977)
                                                                          at com.pedro.encoder.input.audio.MicrophoneManager.init(MicrophoneManager.java:87)
                                                                          at com.pedro.encoder.input.audio.MicrophoneManager.start(MicrophoneManager.java:66)
                                                                          at com.pedro.rtplibrary.base.Camera1Base.startStream(Camera1Base.java:240)`

Could be related to the: https://stackoverflow.com/questions/4843739/audiorecord-object-not-initializing

Also, when looking at the decompiled class from lib, sampleRate prop has follwing value: 
`private int sampleRate = '걄';`
Do not why decompiles shows Chinese character, cos when looking at GitHub:
`private int sampleRate = 44100; //hz`

Tested on Pixel XL

Not related to issue, maybe it's good to expose these params to API consumer...

**Comment by pedroSG94** [comment]
You get this error in app example?
Normally this is for no audio permissions. Did you try with other samplerate?

**Comment by egrgdam** [comment]
Yes. This was from example act. And yes you were correct, didn't ask for permission at the runtime... 
Please close it!
