### ISSUE TITLE
SocketException: Broken pipe

### ISSUE THREAD

**Issue by ali-safdarii** [pedroSG94/rtmp-rtsp-stream-client-java#1055]
hey pedro, i get this exception after 2 minutes sending stream to server, can you help me? how to fix it?
this is my logcat:

```
2022-02-10 12:53:58.732 8956-15812/com.pedro.rtpstreamer E/RtmpSender: send error: 
    java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:117)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:140)
        at com.pedro.rtmp.rtmp.message.RtmpHeader.writeHeader(RtmpHeader.kt:121)
        at com.pedro.rtmp.rtmp.message.RtmpMessage.writeBody(RtmpMessage.kt:134)
        at com.pedro.rtmp.rtmp.CommandsManager.sendVideoPacket(CommandsManager.kt:254)
        at com.pedro.rtmp.rtmp.RtmpSender.start$lambda-2(RtmpSender.kt:115)
        at com.pedro.rtmp.rtmp.RtmpSender.$r8$lambda$RWpSSbIll9sp_byGoOkFIfDGBxg(Unknown Source:0)
        at com.pedro.rtmp.rtmp.RtmpSender$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2022-02-10 12:53:58.798 8956-15933/com.pedro.rtpstreamer E/RtmpClient: disconnect error
    java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:117)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:140)
        at com.pedro.rtmp.rtmp.message.RtmpHeader.writeHeader(RtmpHeader.kt:121)
        at com.pedro.rtmp.rtmp.message.RtmpHeader.writeHeader(RtmpHeader.kt:112)
        at com.pedro.rtmp.rtmp.message.RtmpMessage.writeHeader(RtmpMessage.kt:118)
        at com.pedro.rtmp.rtmp.CommandsManager.sendClose(CommandsManager.kt:240)
        at com.pedro.rtmp.rtmp.RtmpClient.disconnect$lambda-5(RtmpClient.kt:467)
        at com.pedro.rtmp.rtmp.RtmpClient.$r8$lambda$L6f1XZSd9tdbDvwE21RqUPtnFoA(Unknown Source:0)
        at com.pedro.rtmp.rtmp.RtmpClient$$ExternalSyntheticLambda1.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by pedroSG94** [comment]
Hello,

Normally, this is related with lose connection with your server () and this could be for multiple reason:
- Your server close connection.
- You lose connection with your server (internet problem like swipe from wifi to mobile data or bad internet stability).

I recommend you test in local server to discard internet stability and disable totally mobile data in your device. Also, test with multiple devices to discard specific device problems.
After that, check server logs to know the reason about this error because if the error persist this means that the server close connection for some reason.

If possible, share me: server used (version and name), device used (android API and model) and an extended logcat to get more info about it.

**Comment by pedroSG94** [comment]
OBS and Larix Broadcaster have a reconnection feature by default that could be the reason of not lose connection. You can use it with this library too. You have this enabled using Default RTMP example in the app sample.
Can you explain it a bit? What is the different in both stream url?
Can you share me more info about your favorite url? (server name and version) and logcat with more info to know the possible reason.

**Comment by ali-safdarii** [comment]
Hi Pedro, sorry for too late answering and thank u so much for supporting , i asking about server version and other requirement tools , the backend developers sayd to me we  used Nginx rtmp and Node media server for streaming

**Comment by pedroSG94** [comment]
Hello,

I was waiting for you nginx version and Node media server name/version.
I'm sure that Ningx rtmp module is working fine with this library using default configuration in local network so I only can wait to know the version to test it again.
About Node media server. If you means this server:
https://github.com/iizukanao/node-rtsp-rtmp-server
It is working fine using default configuration. Ask about server version and share me server configuration. If possible install server in local network to test.

Also, you never told me if you have problems with nginx or node server (according with your comments. You only have problem with one)

**Comment by ali-safdarii** [comment]
thanks pedro i send your comment for my team , please check this issue will again, and waiting for my answering

**Comment by ali-safdarii** [comment]
Hello Pedro, special thanks for supporting, this is message i recived from backend developers team:
we use this node media server : ["https://github.com/illuspas/Node-Media-Server"](url)
and we dont changed any configuration,every thing exactly same

**Comment by ali-safdarii** [comment]
And This is local log from Node Media Server we Recived:

 [ERROR] rtmp packet parse error. {
  header: {
    fmt: 0,
    cid: 6,
    timestamp: 10031331,
    length: 10933256,
    type: 56,
    stream_id: 2591815683
  },
  clock: 149229,
  payload: <Buffer 27 01 00 00 00 00 00 48 33 21 e2 01 8b 94 20 78 e0 18 d1 f9 21 66 f6 1a ef 8a 37 16 15 fe 73 30 bf f0 5c 14 50 66 00 02 72 91 08 d6 17 1d f4 ce 8e 5a ... 89113 more bytes>,
  capacity: 89163,
  bytes: 15104
}
2/13/2022 23:37:08 8368 [ERROR] rtmp packet parse error. {
  header: {
    fmt: 0,
    cid: 75264,
    timestamp: 14093024,
    length: 12043039,
    type: 72,
    stream_id: 3960065392
  },
  clock: 0,
  payload: null,
  capacity: 0,
  bytes: 0
}
2/13/2022 23:37:08 8368 [ERROR] rtmp packet parse error. {
  header: {
    fmt: 1,
    cid: 46,
    timestamp: 12636275,
    length: 9404964,
    type: 189,
    stream_id: 0
  },
  clock: 0,
  payload: null,
  capacity: 0,
  bytes: 0
}
2/13/2022 23:37:08 8368 [ERROR] rtmp packet parse error. {
  header: {
    fmt: 0,
    cid: 7,
    timestamp: 14715947,
    length: 14622835,
    type: 165,
    stream_id: 3256221285
  },
  clock: 200839,
  payload: <Buffer 10 57 0a 09 97 40 44 59 68 54 06 73 2d f6 38 08 29 94 c0 1c 2b 84 e8 64 b0 a9 58 6d 10 20 12 82 04 c6 55 02 4e e3 6f 42 c3 30 2d 1a 9b 58 58 90 f8 02 ... 5630249 more bytes>,
  capacity: 5630299,
  bytes: 128
}
2/13/2022 23:37:08 8368 [ERROR] rtmp packet parse error. {
  header: {
    fmt: 0,
    cid: 18,
    timestamp: 8612256,
    length: 1774092,
    type: 162,
    stream_id: 2643762434
  },
  clock: 0,
  payload: null,
  capacity: 0,
  bytes: 0
}
2/13/2022 23:37:08 8368 [ERROR] rtmp packet parse error. {
  header: {
    fmt: 2,
    cid: 7,
    timestamp: 4281748,
    length: 14622835,
    type: 165,
    stream_id: 3256221285
  },
  clock: 200839,
  payload: <Buffer 10 57 0a 09 97 40 44 59 68 54 06 73 2d f6 38 08 29 94 c0 1c 2b 84 e8 64 b0 a9 58 6d 10 20 12 82 04 c6 55 02 4e e3 6f 42 c3 30 2d 1a 9b 58 58 90 f8 02 ... 5630249 more bytes>,
  capacity: 5630299,
  bytes: 256
}
2/13/2022 23:37:08 8368 [ERROR] rtmp packet parse error. {
  header: {
    fmt: 2,
    cid: 6,
    timestamp: 1425944,
    length: 10933256,
    type: 56,
    stream_id: 2591815683
  },
  clock: 149229,
  payload: <Buffer 27 01 00 00 00 00 00 48 33 21 e2 01 8b 94 20 78 e0 18 d1 f9 21 66 f6 1a ef 8a 37 16 15 fe 73 30 bf f0 5c 14 50 66 00 02 72 91 08 d6 17 1d f4 ce 8e 5a ... 89113 more bytes>,
  capacity: 89163,
  bytes: 15232
}

**Comment by pedroSG94** [comment]
I think I could find the error and it should be fixed now. Try with this branch and let me know if all is working fine:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/writesync

**Comment by ali-safdarii** [comment]
very very thank you, its working fine and every things now  is ok, just another question how can i use this library with this special branch? can i implement in gradel? iknow is it stupid question sorry for  about that

**Comment by pedroSG94** [comment]
This seems solved. 
Closing issue, remember update library to 2.1.8 when it is available. That version will include this fix.
