### ISSUE TITLE
OnStopstream using rtmpCamera2.stopStream(); app is crashing.

### ISSUE THREAD

**Issue by MTayyabSarfraz** [pedroSG94/rtmp-rtsp-stream-client-java#1068]
@pedroSG94 bro!! i'm facing this consistently, when ever i try to stop my live stream on any device it crashes after a second or to delay... 
I've gone in underlying classes to identify point of crash but no luck.
It throws an  .**`IllegalStateExceptio`n: Recording currently in progress - missing #endRecording() call?**

evenThough I'm not using/enabling startRecording option nowhere in my basicActivity.(the UI controller activity)

I'm using latest version code i.e 1.2.7. not as dependency but as module

Here is my Start and StopStream Code.. don't know what am I doing wrong

here in code `**webViewRenderer** `is Object of `**AndroidViewFilterRender**`

```
    private void startLiveStreamAction() {
        if (!rtmpCamera1.isStreaming()) {

            if (rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo()) {
                button.setText(R.string.stop_button);
                attachViewsToStream();
                //lockControls();
                rtmpCamera1.startStream(rtmpLink);
            } else {
                Toast.makeText(this, "Error preparing stream, This device cant do it",
                        Toast.LENGTH_SHORT).show();
            }
        } else {
            stopStream();
        }
    }
 private void attachViewsToStream() {
        if (glInterFace != null) {
            if (glInterFace.filtersCount() > 0)
                glInterFace.clearFilters();

            webViewRenderer.setView(clStreamContent);
            glInterFace.addFilter(webViewRenderer);
        }
}
    private void stopStream() {
        if (rtmpCamera1.isStreaming()) {
      
            button.setText(R.string.live_now);
          
            rtmpCamera1.stopStream();

        }
    }
```

**_CrashLogs_**

```
E/FrameEvents: updateAcquireFence: Did not find frame.
E/FrameEvents: updateAcquireFence: Did not find frame.
I/chatty: uid=10321(com.myproj.live) RenderThread identical 7 lines
E/FrameEvents: updateAcquireFence: Did not find frame.
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: commyproj.live, PID: 18993
    ```
java.lang.IllegalStateException: Recording currently in progress - missing #endRecording() call?
        at android.graphics.RenderNode.beginRecording(RenderNode.java:372)
        at android.view.View.updateDisplayListIfDirty(View.java:21359)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4524)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4497)
        at android.view.View.updateDisplayListIfDirty(View.java:21346)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4524)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4497)
        at android.view.View.updateDisplayListIfDirty(View.java:21346)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4524)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4497)
        at android.view.View.updateDisplayListIfDirty(View.java:21346)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4524)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4497)
        at android.view.View.updateDisplayListIfDirty(View.java:21346)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4524)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4497)
        at android.view.View.updateDisplayListIfDirty(View.java:21346)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4524)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4497)
        at android.view.View.updateDisplayListIfDirty(View.java:21346)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4524)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4497)
        at android.view.View.updateDisplayListIfDirty(View.java:21346)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4524)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4497)
        at android.view.View.updateDisplayListIfDirty(View.java:21346)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4524)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4497)
        at android.view.View.updateDisplayListIfDirty(View.java:21346)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4524)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4497)
        at android.view.View.updateDisplayListIfDirty(View.java:21346)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4524)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4497)
        at android.view.View.updateDisplayListIfDirty(View.java:21346)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4230)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3944)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3215)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2057)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8360)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
        at android.view.Choreographer.doCallbacks(Choreographer.java:880)
        at android.view.Choreographer.doFrame(Choreographer.java:813)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7889)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```
```

**Comment by pedroSG94** [comment]
I can't see a line related with my library so I supose it is related with android lifecycle.
This look a problem related with AndroidViewFilterRender that try to use your view that is already destroyed.
First of all try reproduce your error without that filter to discard that the filter is the problem.

If the filter is the problem make sure that you clear filters before your activity/fragment anything that you are using to show preview is paused or destroyed to avoid this problem.
Let me know the result of your test to know where I can start to test.

**Comment by MTayyabSarfraz** [comment]
@pedroSG94 I'm clearing filter before stoping preview or stop stream... but this issue still persists...
What I notice is that if is top/start screen in quick successions it doesn't crash... but if I'm streaming for a while .. let's say 3-4 minutes .. it crashes..
Can't understand what I'm doing wrong with the lifecycle/stop streaming events.
Actually, the lifeCycle issue shouldn't be the issue as I am not doing any screen changes in screen configs or anything that relates to activity lifecycle (as I'm standing on same screen just triggering stopEvent).

**Comment by pedroSG94** [comment]
Try to reproduce it without AndroidViewFilterRender. This seems an error related with canvas rendering:
https://android.googlesource.com/platform/frameworks/base/+/master/graphics/java/android/graphics/RenderNode.java#389
AndroidViewFilterRender is the only side where I'm using canvas.
I will try to reproduce it. I will need your AndroidViewFilterRender configuration (View used)

**Comment by MTayyabSarfraz** [comment]
@pedroSG94 sorry for the late response.. actually I was away for a week!!
here are both my java and XML gist...
plz have a look.
[Layout and java class gist url](https://gist.github.com/MTayyabSarfraz/99b63a53b8d77f0ff2c96be536b25725)

**Comment by MTayyabSarfraz** [comment]
@pedroSG94 bro please can i have your attention here...

**Comment by MTayyabSarfraz** [comment]
Hi bro... I've added my code link .. plz have a look.
Thanks

**Comment by pedroSG94** [comment]
I already saw that yesterday. I had no time to test it yesterday and today I'm still working.
Please, be patient. I only can work in this library in my free time.
I will notify you if I can reproduce your case or not with your code shared this night or tomorrow.

**Comment by MTayyabSarfraz** [comment]
Sure bro!! actually, that was a panic call (deadLine).. didn't have the slightest of idea what was going wrong, tried to work from a different perspective but not a single one worked for me. Now thinking of re-assessing the filters assignment work again.
Would be waiting for your assessment, if mine still doesn't work.

**Comment by pedroSG94** [comment]
Hello,

After few tests I can comfirm that the problem is related with AndroidViewFilterRender and stop render it.
You can fix it replacing your stopStream method to this:
```java
    private void stopStream() {
        if (rtmpCamera2.isStreaming()) {
            webViewRenderer.setView(null); //stop render view
            clStreamContent.setVisibility(View.VISIBLE);
            button.setText(R.string.start_button);
            rtmpCamera2.stopStream();
        }
    }
```
With this line, the problem never happens. I'm looking the exact reason about the problem to avoid need stop render manually in this case.

**Comment by MTayyabSarfraz** [comment]
@pedroSG94 thanks for the solution. Now I can have a sigh of relief!! 

There is another issue popping, feel related to this.

when I put my app in the background and resume again.
the screen gets black. Previews stops and 
I found that upon resuming `**openGlView.getHolder().getSurface().isValid()**` always returns null and I cant start preview again, even if I try to reinitialize my opengl using my **`initializeRTMPCameraInstance()`** method.


```
    @Override
    protected void onResume() {
        super.onResume();

       if (rtmpCamera2 != null && !rtmpCamera2.isOnPreview() && openGlView.getHolder().getSurface().isValid())
            rtmpCamera2.startPreview();
    }
```

**Comment by pedroSG94** [comment]
Hello,

This is a code problem. You should read app examples.
In this case the problem is that you should start preview only on onSurfaceChanged callback and stop preivew onSurfaceDestroyed callback like in the examples.

**Comment by MTayyabSarfraz** [comment]
Code example is doing the same thing bro.
