### ISSUE TITLE
Bad notification for startForeground

### ISSUE THREAD

**Issue by hogantan** [pedroSG94/rtmp-rtsp-stream-client-java#1093]
Error: `E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.djiaapp, PID: 15936
    android.app.RemoteServiceException: Bad notification for startForeground
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:359)
        at android.app.ActivityThread.main(ActivityThread.java:7418)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)`

Not too sure why I am getting this error. It is occuring in `DisplayService.kt`: 
`  private fun keepAliveTrick() {
    val notification = NotificationCompat.Builder(this, channelId)
            .setSilent(true)
            .setOngoing(false)
            .build()
    startForeground(1, notification)
  }`

Any idea what is the issue here? Only occurring in selected devices only as well.

**Comment by pedroSG94** [comment]
It is really weird, normally it is because the channel in Android 8+ is not created but I'm doing it.
Can you specify devices and Android version?
Also, check that this is called (check if null):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/displayexample/DisplayService.kt#L49
remove setSilent and setOngoing and try use a different id in startForeground

**Comment by hogantan** [comment]
My bad I forgot to include that code. Yup it runs fine now.

I was on a Xperia XZ2 on Android 10. 

Thanks for the help!
