### ISSUE TITLE
onConnectionFailedRtmp (FATAL EXCEPTION: pool-4-thread-1)

### ISSUE THREAD

**Issue by redjamhere** [pedroSG94/rtmp-rtsp-stream-client-java#1122]
Hi, I have a problem with onConnectionFailedRtmp.
I try connect to unavailable server, but interface method "onConnectionFailedRtmp" crash activity and application.
Your example rtmp activities crash too
And after executing "onConnectionFailedRtmp" I turn on the rtmp server, but I can start stream, because error state ( FATAL EXCEPTION: pool-4-thread-1) remains

Log:

E/AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
    Process: com.pedro.rtpstreamer, PID: 18276
    kotlin.UninitializedPropertyAccessException: lateinit property output has not been initialized
        at com.pedro.rtmp.utils.socket.TcpSocket.getOutStream(TcpSocket.kt:38)
        at com.pedro.rtmp.rtmp.CommandsManager.sendClose(CommandsManager.kt:263)
        at com.pedro.rtmp.rtmp.RtmpClient.disconnect$lambda-5(RtmpClient.kt:464)
        at com.pedro.rtmp.rtmp.RtmpClient.$r8$lambda$L6f1XZSd9tdbDvwE21RqUPtnFoA(Unknown Source:0)
        at com.pedro.rtmp.rtmp.RtmpClient$$ExternalSyntheticLambda1.run(Unknown Source:2)

device: Samsung s20 FE

**Comment by pedroSG94** [comment]
Fixed here: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/8d6438dda707e4a5732eacc7f7175daa4ad26623
You can compile library version 2.1.9
