### ISSUE TITLE
Connection refuse 

### ISSUE THREAD

**Issue by himanshumistri** [pedroSG94/rtmp-rtsp-stream-client-java#113]
i am trying to run RTSP default activity but it always fails on samsung galaxy a 8 device .

```java
01-08 15:16:49.476 22380-23909/com.pedro.rtpstreamer E/RtspClient: connection error
                                                                   java.net.ConnectException: failed to connect to /192.168.43.150 (port 8080) after 3000ms: isConnected failed: ECONNREFUSED (Connection refused)
                                                                       at libcore.io.IoBridge.isConnected(IoBridge.java:234)
                                                                       at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
                                                                       at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                       at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                       at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
                                                                       at java.net.Socket.connect(Socket.java:884)
                                                                       at com.pedro.rtsp.rtsp.RtspClient$1.run(RtspClient.java:168)
                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                    Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
                                                                       at libcore.io.IoBridge.isConnected(IoBridge.java:223)
                                                                       at libcore.io.IoBridge.connectErrno(IoBridge.java:171) 
                                                                       at libcore.io.IoBridge.connect(IoBridge.java:122) 
                                                                       at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) 
                                                                       at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452) 
                                                                       at java.net.Socket.connect(Socket.java:884) 
                                                                       at com.pedro.rtsp.rtsp.RtspClient$1.run(RtspClient.java:168) 
                                                                       at java.lang.Thread.run(Thread.java:818) 
```

**Comment by pedroSG94** [comment]
Normally this is because you can't find the server IP. Make sure that you are in the same network, some times mobile data can produce it, try disable it and test.
To make sure that you are in the same network that your device you can try do a ping to server IP with some app like this:
https://play.google.com/store/apps/details?id=com.lipinic.ping&hl=es

**Comment by himanshumistri** [comment]
@pedroSG94 Why RTSP does require server ip can't it done without server ip, i mean if my device connected to wifi and it have it's own IP address can't it start the stream from device IP.

**Comment by pedroSG94** [comment]
What are you using to connect? IP camera?
This library is a client not a player so it use a media server to connect and stream. Media server like:
https://github.com/iizukanao/node-rtsp-rtmp-server
https://github.com/EasyDarwin/EasyDarwin
https://www.wowza.com/pricing/streaming-engine?utm_source=google&utm_medium=cpc&utm_campaign=ppc-brand_europe_cbi-wowza&gclid=EAIaIQobChMIue64k_HK2AIVRxDTCh1Kmg9cEAAYASAAEgJBS_D_BwE

This library connect to media server and send video and audio.

**Comment by bhavinatharva** [comment]
Hello @pedroSG94  brother, 

I am getting this error when i am going to use decast with below this url

rtmp://rtmp.ap.live.dacast.com/live

**Comment by pedroSG94** [comment]
Hello,

Your problem is the url. You need add the stream name/key to the url. Something like this:
rtmp://rtmp.ap.live.dacast.com/live/writestreamkeyhere

**Comment by bhavinatharva** [comment]
Hi,
I shared that URL only as a reference example, I already includes the correct stream key/name. The issue still occurs even with the proper full RTMP URL.

Let me know if you need any logs or more details to help debug it.

Try this 
```
rtmp://rtmp.ap.live.dacast.com/live
```

```
DtiDI7k9v3R0pN21
```
