### ISSUE TITLE
rtsp display error

### ISSUE THREAD

**Issue by mrds1997** [pedroSG94/rtmp-rtsp-stream-client-java#1137]
Hi.
I used the library for live screen faced a problem in release mode , it can't connect to a server.
maybe related to proguard?

**Comment by mrds1997** [comment]
This is the log:

2022-06-16 13:57:08.301 31115-31841/? E/RtmpClient: connection error
    java.lang.NullPointerException: throw with null exception
        at qa.b.c(Unknown Source:1)
        at oa.h$a.a(SourceFile:1)
        at xd.h.a(Unknown Source:20)
        at oa.h.a(Unknown Source:2)
        at ma.d.c(SourceFile:16)
        at ma.c.run(SourceFile:3)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by mrds1997** [comment]
Yes i'm using the last version

**Comment by mrds1997** [comment]
library for live screen works correctly in dubug mode. but in release not working correct

**Comment by pedroSG94** [comment]
Exclude the library from proguard and share me the error again to detect the problem:
```
 -keep class com.pedro.** { *; }
```

**Comment by mrds1997** [comment]
The issue fixed, thanks a lot.
