### ISSUE TITLE
Sockettimeoutexception

### ISSUE THREAD

**Issue by annyjasmin39** [pedroSG94/rtmp-rtsp-stream-client-java#1159]
HI,

I am trying to implement this library to stream RTSP .
Basically want to create a RTSP server.
But its giving Socketimeoutexception,i think its on this line
line = reader.ReadLine()

Could you please help

**Comment by pedroSG94** [comment]
Hello,

That is expected if you haven't a server to connect.
This library is used as a pusher not a Server. Basically you send video/audio data to a RTSP server.
You have a RTSP server that only support send data directly to a media player (you can't push video/audio data and receive that data in other device):
https://github.com/pedroSG94/RTSP-Server

**Comment by annyjasmin39** [comment]
HI @pedroSG94 ,I have implemented the above server in my codes,
but i am still not able to see the camera video in VLC.
In VLC I am providing link like this-
rtsp://192.168.1.33:8554

also tried with rtsp://192.168.1.33:8554/streamid=1

but everytime it is coming to below line
 output.Write(commandsManager.createError(500, cSeq));

this line getting called here-
return  getResponse(input, Method.UNKNOWN); in servercommandmanager file


Could you please help us on this...spent lot of time...still not getting the video in VLC

**Comment by annyjasmin39** [comment]
After more debugging found that response is always blank...Once setup is called ,Response is always empty
in commandsmanager getresponse method
Not sure what may be the issue,at the moment i am just looking for  video ,all audio codes I have removed in my project

**Comment by pedroSG94** [comment]
Hello,

First of all compile app example without modifications and test it with your VLC. 
If the problem persist share me error logcat, player name, player version and OS used to reproduce the case.

**Comment by annyjasmin39** [comment]
HI,Thanks for reply,your app code is working fine,
Basically I am coverting your codes to .net codes in xamarin,may be some codes I have written wrong.
In this method it is always showing error
public Command getResponseCommands(BufferedReader reader, Method method)
        {
            try
            {
                String response = "";
                String line;

                while ((line = reader.ReadLine()) != null)
                {
                    response += line + "\n";
                    if (line.Length < 3) break;
                }
                if (method == Method.UNKNOWN)
                {
                    return parser.parseCommand(response);
                }
                else
                {
                    var command = parser.parseResponse(method, response);
                    sessionId = parser.getSessionId(command);
                    if (command.method == Method.SETUP && protocol == ProtocolType.Udp)
                    {
                        parser.loadServerPorts(command, protocol, audioClientPorts, videoClientPorts,
                          audioServerPorts, videoServerPorts);
                    }

                    // Log.i(TAG, response);
                    return command;
                }
            }
            catch (IOException e)
            {
                // Log.e(TAG, "read error", e);
                return null;
            }
        }

**Comment by annyjasmin39** [comment]
exception i caught,its broken pipe issue

**Comment by annyjasmin39** [comment]
{Java.Net.SocketException: Broken pipe
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00068] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:11884 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00024] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:29 
  at Java.IO.BufferedWriter.Flush () [0x00000] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-29/mcw/Java.IO.BufferedWriter.cs:129 
  at RTSPServer.ServerClient.Run () [0x0004e] in D:\AlphaLatestLocalBranch\AlphaTouch_Dev_G2\RTSPServer\ServerClient.cs:69 
  --- End of managed Java.Net.SocketException stack trace ---
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:117)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:161)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at java.io.BufferedWriter.flush(BufferedWriter.java:254)
	at crc64692946ddbff9908d.ServerClient.n_run(Native Method)
	at crc64692946ddbff9908d.ServerClient.run(ServerClient.java:85)
}

**Comment by pedroSG94** [comment]
Broken pipe normally means that the other side closed connection.
Can you show me logcat of the library?

You are writing a wrapper of my library to use it in xamarin, right?
In this case I can't help you so much doing a port because I don't know about Xamarin. I only can help you with Android native code.

Can you write a native activity and use it from Xamarin like in Cordova?
If the app example is working fine. You can copy example activity and try using it.

**Comment by annyjasmin39** [comment]
finally i was able to port it to xamarin successfully...actually there was nothing wrong with codes...issue was with port,if i use any other port apart from 1935,it doesnot work

**Comment by annyjasmin39** [comment]
now it is giving different error in setlong method but connection was successfull
