### ISSUE TITLE
App crash when start record before start streaming

### ISSUE THREAD

**Issue by hemant-novotrax** [pedroSG94/rtmp-rtsp-stream-client-java#1178]
Hello @pedroSG94 
When I record the video before streaming the video and later when I start the streaming, my app crashes.
bellow logcat show:-

```
E/CameraCaptureSession: Session 0: Exception while stopping repeating: 
    android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): cancelRequest:470: Camera 0: Error clearing streaming request: Function not implemented (-38)
        at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:802)
        at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:97)
        at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1150)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:527)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:738)
        at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:245)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.os.ServiceSpecificException: cancelRequest:470: Camera 0: Error clearing streaming request: Function not implemented (-38) (code 10)
        at android.os.Parcel.createException(Parcel.java:2085)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:658)
        at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:95)
        at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1150) 
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:527) 
        at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:738) 
        at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:245) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2022-10-07 12:21:20.533 679-18553/? E/mm-camera: <STATS ><ERROR> 3040: stats_port_check_caps_reserve: Invalid Port capability type!
2022-10-07 12:21:20.533 679-18553/? E/mm-camera: <STATS ><ERROR> 3040: stats_port_check_caps_reserve: Invalid Port capability type!
2022-10-07 12:21:20.548 679-18553/? E/libc: Access denied finding property "ro.camera.req.fmq.size"
2022-10-07 12:21:20.549 679-18553/? E/libc: Access denied finding property "ro.camera.res.fmq.size"
2022-10-07 12:21:20.557 930-4563/? E/libc: Access denied finding property "camera.clientname"
2022-10-07 12:21:20.557 930-4563/? E/VendorTagDescriptor: lookupTag: Tag name 'availableStreamConfigurations' does not exist.
2022-10-07 12:21:20.579 679-18553/? E/CamComm1.0-MD: Mismatched tag type when updating entry enable (-2146762752) of type byte; got type int32 data instead 
2022-10-07 12:21:20.579 679-18553/? E/CamComm1.0-MD: Mismatched tag type when updating entry is_main (-2146762751) of type byte; got type int32 data instead 
```
and

```
 java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
        at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
        at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:248)
        at com.pedro.encoder.input.gl.render.CameraRender.updateTexImage(CameraRender.java:131)
        at com.pedro.encoder.input.gl.render.ManagerRender.updateFrame(ManagerRender.java:96)
        at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:182)
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by pedroSG94** [comment]
Hello,

Are you using app example to discard code errors?
Did you tried using this method to start record and stream at same time?
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L618

**Comment by hemant-novotrax** [comment]
> 

Hello @pedroSG94 
My simple requirement is I want to record video whenever streaming has not started and as soon as streaming starts I want to stop recording.

I try this functionality in Camera1Base its works but when this is used in the service class (for background) it's not working and throw the above error.

I hope you understand the actual situation.

**Comment by pedroSG94** [comment]
Hello,

Which line is 802? I think it is not related with the actual library code:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java#L802
