### ISSUE TITLE
Crash app while opens video from file

### ISSUE THREAD

**Issue by pratheepchowdhary** [pedroSG94/rtmp-rtsp-stream-client-java#12]
Hello sir rtmp with camera is working good but I try to open with file my app is crashing 
Please tell me the solution sir.

**Comment by pedroSG94** [comment]
At the moment that feature is unstable.
Could you show me log error?

**Comment by pradeepchows** [comment]
here my logs


06-27 13:10:09.420 19144-19144/com.pedro.rtmpstreamer D/AsfParser: MediaExtractor track of type 'audio/mp4a-latm'
06-27 13:10:09.420 19144-19144/com.pedro.rtmpstreamer D/AsfParser: JB -MediaExtractor::Create
06-27 13:10:09.426 19144-19144/com.pedro.rtmpstreamer D/AndroidRuntime: Shutting down VM
06-27 13:10:09.428 19144-19144/com.pedro.rtmpstreamer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.pedro.rtmpstreamer, PID: 19144
                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                                            at android.media.MediaFormat.getInteger(MediaFormat.java:524)
                                                                            at com.pedro.encoder.input.decoder.VideoDecoder.initExtractor(VideoDecoder.java:48)
                                                                            at com.pedro.builder.RtmpBuilderFromFile.prepareVideo(RtmpBuilderFromFile.java:63)
                                                                            at com.pedro.rtmpstreamer.filestreamexample.RtmpFromFileActivity.onClick(RtmpFromFileActivity.java:111)
                                                                            at android.view.View.performClick(View.java:4848)
                                                                            at android.view.View$PerformClick.run(View.java:20262)
                                                                            at android.os.Handler.handleCallback(Handler.java:815)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                            at android.os.Looper.loop(Looper.java:194)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5706)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1033)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
06-27 13:10:09.429 743-1477/? W/ActivityManager:   Force finishing activity 1 com.pedro.rtmpstreamer/.filestreamexample.RtmpFromFileActivity

**Comment by pedroSG94** [comment]
Crash in this line right?:
height = videoFormat.getInteger(MediaFormat.KEY_HEIGHT);
The file is a mp4 video or only audio?
If only audio crash because try decode a video. If not then let me know device details to reproduce crash (API, device model, etc).

**Comment by pradeepchows** [comment]
Its mp4 video file 

And device details

Lollipop
Api 22
coolpad note3 lite

**Comment by pedroSG94** [comment]
I did a update. Get last commit and test with this file:
https://mega.nz/#!bhgDUBRJ!XujCvKLntcASO8k1DCm-IxzXe3yWkWQfpYZH6IyiOxQ
If the problem persists I need reproduce the fail.

**Comment by pradeepchows** [comment]
hello sir same thing happening which i follows above
same logs

**Comment by pedroSG94** [comment]
Ok. I will try reproduce the crash and fix.

**Comment by pradeepchows** [comment]
Thank u sir 
Please notify me after completion

**Comment by pedroSG94** [comment]
I did a update for it, resolutions params should be getted always.

**Comment by pradeepchows** [comment]
Same issue force closes app after few secs

**Comment by pradeepchows** [comment]
logs
7-04 09:07:05.559 20889-21603/com.pedro.rtmpstreamer E/IOMX: binder transaction failed: -32
07-04 09:07:05.559 20889-21603/com.pedro.rtmpstreamer E/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] storeMetaDataInBuffers failed w/ err -32
07-04 09:07:05.559 20889-21603/com.pedro.rtmpstreamer D/ACodec: GetVideoCodingTypeFromMime video/avc, video/avc
07-04 09:07:05.559 20889-21603/com.pedro.rtmpstreamer E/IOMX: binder transaction failed: -32
07-04 09:07:05.559 20889-21603/com.pedro.rtmpstreamer E/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] configureCodec returning error ffffffe0
07-04 09:07:05.559 20889-21603/com.pedro.rtmpstreamer E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
07-04 09:07:05.561 20889-21602/com.pedro.rtmpstreamer E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 3
07-04 09:07:05.561 20889-21602/com.pedro.rtmpstreamer D/Surface: Surface::disconnect(this=0x7f8a641000,api=3)
07-04 09:07:05.561 20889-21602/com.pedro.rtmpstreamer W/MediaCodec: native_window_api_disconnect returned an error: Broken pipe (-32)
07-04 09:07:05.562 20889-20889/com.pedro.rtmpstreamer E/MediaCodec: configure failed with err 0x80001001, resetting...
07-04 09:07:05.562 20889-20889/com.pedro.rtmpstreamer I/MediaCodec: [release]line:366 [OMX.MTK.VIDEO.DECODER.AVC]+++
07-04 09:07:05.562 20889-21603/com.pedro.rtmpstreamer E/IOMX: binder transaction failed: -32
07-04 09:07:05.562 20889-21603/com.pedro.rtmpstreamer A/ACodec: frameworks/av/media/libstagefright/ACodec.cpp:7884 CHECK_EQ( mCodec->mOMX->freeNode(mCodec->mNode),(status_t)OK) failed: -32 vs. 0
07-04 09:07:05.562 20889-21603/com.pedro.rtmpstreamer A/libc: Fatal signal 5 (SIGTRAP), code 1 in tid 21603 (CodecLooper)
07-04 09:07:05.564 20889-20906/com.pedro.rtmpstreamer W/CameraBase: Camera service died!
07-04 09:07:05.564 20889-21592/com.pedro.rtmpstreamer E/ACodec: OMX/mediaserver died, signalling error!

**Comment by pedroSG94** [comment]
This crash is different.
In this log i can't see the line that crash, but i think that crash decoder video configure. I need discard hardware problems with your decoder. For this use methods with params. Use this params for the video that i shared: resolution 480X290, stereo channel and 48000 samplerate.

For that replace in activity this line:
```

if (rtmpBuilderFromFile.prepareVideo(filePath, 1200 * 1024)
                  && rtmpBuilderFromFile.prepareAudio(filePath)) {
```

To:

```
if (rtmpBuilderFromFile.prepareVideo(filePath, 1200 * 1024, 480, 290)
                  && rtmpBuilderFromFile.prepareAudio(filePath, true, 48000)) {
```
Do it and show me the log if crash. If the crash persist in VideoDecoder class then could be a decoder problem and fix it without the device will be really hard and maybe cant be fixed.

Other test that you could do is install this proyect and test with double decode and play video (Surfaceview):
https://github.com/google/grafika

**Comment by pradeepchows** [comment]
same issue no change
here the logs text file
[logs..txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/1121883/logs.txt)

**Comment by pradeepchows** [comment]
I tried grafika its working good

But this not works

**Comment by pedroSG94** [comment]
Ok. I will do a refactor with grafika examples.

**Comment by pedroSG94** [comment]
After find different solutions, I think that the last solution should work for you. Now stream from file video is renderer with MediaPlayer android class and not with a video decoder. In my Samsung S7 with video decoder and with MediaPlayer work similar but it should solve decoder problems.

Other possible problem was find in VideoEncoder with this crash:
```

07-20 15:32:09.184 7260-7512/com.pedro.rtmpstreamer E/ACodec: [OMX.qcom.video.encoder.avc] ERROR(0x80001009)
07-20 15:32:09.184 7260-7511/com.pedro.rtmpstreamer E/MediaCodec: Codec reported an error. (omx error 0x80001009, internalError -2147483648)
07-20 15:32:09.184 7260-7520/com.pedro.rtmpstreamer E/AndroidRuntime: FATAL EXCEPTION: Thread-415
                                                                      Process: com.pedro.rtmpstreamer, PID: 7260
                                                                      java.lang.IllegalStateException
                                                                          at android.media.MediaCodec.getBuffers(Native Method)
                                                                          at android.media.MediaCodec.getOutputBuffers(MediaCodec.java:551)
                                                                          at com.pedro.encoder.video.VideoEncoder$3.run(VideoEncoder.java:343)
                                                                          at java.lang.Thread.run(Thread.java:841)
```

Same crash in line 305 ifyou use API 21+.
No solution found for this, could be a hardware limitation but I'm not sure.
