### ISSUE TITLE
How to send watermark  and timestamp on vedio to server

### ISSUE THREAD

**Issue by Rishabhsoti** [pedroSG94/rtmp-rtsp-stream-client-java#124]
How to send watermark  and timestamp on vedio to server

**Comment by pedroSG94** [comment]
To send watermark you can use setImageStreamObject and for timestamp you can send an Android view that will be updated.
Android view should be inflated before send it so you should add it to XML layout (Of couurse you can hide it drawing under OpenglView).
You have both examples in opengl activities for rtmp and rtsp:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/java/com/pedro/rtpstreamer/surfacemodeexample

You can test installing my app and use the menu in right top of the screen.
You can see how to send a image to stream like bitmap (In this case icon app) and how to send a layout view with Android view filter (in this case all activity layout) but you can send any Android view like a Textview for your timestamps.
Then to update Textview simply send text to it.

**Comment by Rishabhsoti** [comment]
setImageStreamObject method not working on custom RTMP class when I call the method by a button app stops automatically.

**Comment by pedroSG94** [comment]
can you send logcat?

**Comment by Rishabhsoti** [comment]
no

**Comment by pedroSG94** [comment]
If you don't show me the error of the console I can't help you to debug

**Comment by Rishabhsoti** [comment]
ok let me check as you say just to use setImageStreamObject so I am just using this method in the custom rtmp.java and provide an option for image in menu XML but when I click on image app will stop working  at the end error logcat is this----

02-08 13:03:32.162 21100-21100/com.pedro.rtpstreamer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.pedro.rtpstreamer, PID: 21100
                                                                       java.lang.RuntimeException: You must use OpenGlView in the constructor to set a text
                                                                           at com.pedro.rtplibrary.base.Camera1Base.setTextStreamObject(Camera1Base.java:511)
                                                                           at com.pedro.rtpstreamer.customexample.RtmpActivity.setTextToStream(RtmpActivity.java:239)
                                                                           at com.pedro.rtpstreamer.customexample.RtmpActivity.onOptionsItemSelected(RtmpActivity.java:194)
                                                                           at android.app.Activity.onMenuItemSelected(Activity.java:3384)
                                                                           at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:380)
                                                                           at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
                                                                           at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.onMenuItemSelected(AppCompatDelegateImplV9.java:674)
                                                                           at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
                                                                           at android.support.v7.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:89)
                                                                           at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
                                                                           at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
                                                                           at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
                                                                           at android.widget.AdapterView.performItemClick(AdapterView.java:343)
                                                                           at android.widget.AbsListView.performItemClick(AbsListView.java:1664)
                                                                           at android.widget.AbsListView$PerformClick.run(AbsListView.java:4075)
                                                                           at android.widget.AbsListView.onTouchUp(AbsListView.java:6572)
                                                                           at android.widget.AbsListView.onTouchEvent(AbsListView.java:6319)
                                                                           at android.widget.ListView.onTouchEvent(ListView.java:1641)
                                                                           at android.support.v7.widget.ListViewCompat.onTouchEvent(ListViewCompat.java:124)
                                                                           at android.view.View.dispatchTouchEvent(View.java:10779)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2858)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2534)
                                                                           at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:6231)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
                                                                           at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2480)
                                                                           at android.view.View.dispatchPointerEvent(View.java:11008)
                                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5155)
                                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5007)
                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4532)
                                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4585)
                                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4551)
                                                                           at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4684)
                                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4559)
                                                                           at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4741)
                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4532)
                                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4585)
                                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4551)
                                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4559)
                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4532)
                                                                           at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7092)
                                                                           at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7024)
                                                                           at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6985)
                                                                           at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7202)
                                                                           at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                           at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                           at android.os.MessageQueue.next(MessageQueue.java:323)
02-08 13:03:32.162 21100-21100/com.pedro.rtpstreamer E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by pedroSG94** [comment]
java.lang.RuntimeException: You must use OpenGlView in the constructor to set a text

As you can see in logcat. You need use Openglview in your XML layaout and when you get it on Activity.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/res/layout/activity_open_gl.xml#L7
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L73

**Comment by Rishabhsoti** [comment]
But when I do  this in java
 OpenGlView openGlView = findViewById(R.id.surfaceView);
    openGlView.getHolder().addCallback(this);
    rtmpCamera1 = new RtmpCamera1(openGlView, this);
and this in xml 
<com.pedro.rtplibrary.view.OpenGlView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/surfaceView"
        />
instead of 
SurfaceView surfaceView = findViewById(R.id.surfaceView);
    surfaceView.getHolder().addCallback(this);
    rtmpCamera1 = new RtmpCamera1(surfaceView, this);
and 
<SurfaceView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/surfaceView"
        />
IN CUSTOM EXAMPLE RTMP FILE APP CLOSSES UNFORTUNETLY.

**Comment by pedroSG94** [comment]
Openglview mode with camera1 had a problem calling startPreview method. 
Now this is fixed: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/d9204e1b0198e7f71b81a9f8a1ea3b6f78d65fd0
Get last commit and retry
