### ISSUE TITLE
com.pedro.rtpstreamer E/AndroidRuntime: FATAL EXCEPTION: AudioEncoder When I Use RtmpOnlyAudio startRecord And startStream

### ISSUE THREAD

**Issue by iwuq** [pedroSG94/rtmp-rtsp-stream-client-java#1244]
2023-06-06 11:48:52.476 30193-30252/com.pedro.rtpstreamer E/AndroidRuntime: FATAL EXCEPTION: AudioEncoder
    Process: com.pedro.rtpstreamer, PID: 30193
    java.nio.BufferUnderflowException
        at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:239)
        at com.pedro.rtmp.flv.audio.AacPacket.createFlvAudioPacket(AacPacket.kt:77)
        at com.pedro.rtmp.rtmp.RtmpSender.sendAudioFrame(RtmpSender.kt:79)
        at com.pedro.rtmp.rtmp.RtmpClient.sendAudio(RtmpClient.kt:507)
        at com.pedro.rtplibrary.rtmp.RtmpOnlyAudio.getAacDataRtp(RtmpOnlyAudio.java:163)
        at com.pedro.rtplibrary.base.OnlyAudioBase.getAacData(OnlyAudioBase.java:356)
        at com.pedro.encoder.audio.AudioEncoder.sendBuffer(AudioEncoder.java:150)
        at com.pedro.encoder.BaseEncoder.processOutput(BaseEncoder.java:209)
        at com.pedro.encoder.BaseEncoder.outputAvailable(BaseEncoder.java:242)
        at com.pedro.encoder.BaseEncoder$2.onOutputBufferAvailable(BaseEncoder.java:262)
        at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1797)
        at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1705)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by iwuq** [comment]
When I use RtmpOnlyAudio streaming and record audio locally, this error is always reported. I tried using RtmpCamera1 to record audio and video successfully
