### ISSUE TITLE
Timeout error in RtspDisplay and RtmpDisplay

### ISSUE THREAD

**Issue by erickpatrickx** [pedroSG94/rtmp-rtsp-stream-client-java#163]
I receive a socket timeout  after few minutes of connection im my server remote (RMTP and RTSP) . I tried increase the timeout but not worked 

Can you help ? 

Thanks

**Comment by pedroSG94** [comment]
Did you try with my app example?
What server are you using? Can you share me logcat and reason error of callback onConnectionFailed?

**Comment by erickpatrickx** [comment]
Only with your app example no, but i'm included in mine app. 
I'm using wowza server but i tested  also  youtube and twitch  

Logcat:


04-25 13:51:42.393 1342-1413/? W/System.err: Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
04-25 13:51:42.401 1342-1342/? W/System.err: com.mobi.sdk.HttpRequest$HttpRequestException: java.net.SocketTimeoutException: connect timed out
        at com.mobi.sdk.HttpRequest.do(SourceFile:1512)
        at com.mobi.sdk.assert.do(SourceFile:315)
04-25 13:51:42.403 1342-1342/? W/System.err: Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
        at java.net.Socket.connect(Socket.java:586)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
        at com.android.okhttp.Connection.connectSocket(Connection.java:1432)
        at com.android.okhttp.Connection.connect(Connection.java:1390)
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1667)
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:133)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:466)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:371)
04-25 13:51:46.352 1342-1699/? W/System.err: com.mobi.sdk.HttpRequest$HttpRequestException: java.net.SocketTimeoutException: connect timed out
        at com.mobi.sdk.HttpRequest.do(SourceFile:1512)
04-25 13:51:46.360 1342-1699/? W/System.err: Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
        at java.net.Socket.connect(Socket.java:586)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
        at com.android.okhttp.Connection.connectSocket(Connection.java:1432)
        at com.android.okhttp.Connection.connect(Connection.java:1390)
04-25 13:51:46.364 1342-1342/? W/System.err: com.mobi.sdk.HttpRequest$HttpRequestException: java.net.SocketTimeoutException: connect timed out
04-25 13:51:46.365 1342-1342/? W/System.err:     at com.mobi.sdk.integration.doInBackground(SourceFile:220)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at com.mobi.sdk.g.run(SourceFile:44)
        at java.lang.Thread.run(Thread.java:762)
    Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
        at java.net.Socket.connect(Socket.java:586)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
        at com.android.okhttp.Connection.connectSocket(Connection.java:1432)
        at com.android.okhttp.Connection.connect(Connection.java:1390)
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1667)
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:133)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:466)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:371)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:503)
04-25 13:51:53.316 1342-1411/? W/System.err: com.mobi.sdk.HttpRequest$HttpRequestException: java.net.SocketTimeoutException: connect timed out
        at com.mobi.sdk.HttpRequest.case(SourceFile:3007)
        at com.mobi.sdk.portability.do(SourceFile:75)
        at com.mobi.sdk.portability.do(SourceFile:124)
        at com.mobi.sdk.return.do(SourceFile:65)
        at com.mobi.sdk.persistance.do(SourceFile:60)
04-25 13:51:53.317 1342-1411/? W/System.err:     at com.mobi.sdk.persistance.doInBackground(SourceFile:17)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at com.mobi.sdk.g.run(SourceFile:44)
        at java.lang.Thread.run(Thread.java:762)
    Caused by: java.net.SocketTimeoutException: connect timed out
04-25 13:51:53.319 1342-1411/? W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:261)
        at com.mobi.sdk.HttpRequest.try(SourceFile:2688)
        at com.mobi.sdk.HttpRequest.case(SourceFile:3004)
    	... 11 more
    com.mobi.sdk.HttpRequest$HttpRequestException: java.net.SocketTimeoutException: connect timed out
        at com.mobi.sdk.HttpRequest.case(SourceFile:3007)
        at com.mobi.sdk.portability.do(SourceFile:75)
        at com.mobi.sdk.portability.do(SourceFile:124)
        at com.mobi.sdk.return.do(SourceFile:65)
        at com.mobi.sdk.persistance.do(SourceFile:60)
        at com.mobi.sdk.persistance.doInBackground(SourceFile:17)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at com.mobi.sdk.g.run(SourceFile:44)
        at java.lang.Thread.run(Thread.java:762)
    Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)


Thanks

**Comment by pedroSG94** [comment]
My app is working fine?
Can you share me your code example to reproduce error?

**Comment by erickpatrickx** [comment]
I tested your app and isn't working , at 20 seconds is stoped.
I tested 3g and Wifi the apps only working in local network.

I saw you said in another issue that could use a proxy.
Would it work in my case?

**Comment by pedroSG94** [comment]
Yes, your proxy could be the problem if you work success in local network. Try disable your proxy to test if that is the problem.
Also try do a ping to make sure that your IP is correct.
Remember open TCP or UDP ports used.
