### ISSUE TITLE
Error when start RTSP connection

### ISSUE THREAD

**Issue by omarmakeen** [pedroSG94/rtmp-rtsp-stream-client-java#173]
I've the following error when try to start RTSP connection
Error configure stream, Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
could you please help?

**Comment by pedroSG94** [comment]
Did you test with my app example?
If yes, go to this class:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtsp/src/main/java/com/pedro/rtsp/rtsp/RtspClient.java
And delete nullpointerexception catch to know the line that crash:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtsp/src/main/java/com/pedro/rtsp/rtsp/RtspClient.java#L225

**Comment by omarmakeen** [comment]
Yes and I did please check the below error

05-20 13:44:39.326 30961-31084/com.pedro.rtpstreamer E/RtspClient: read error
                                                                   java.net.SocketTimeoutException: Read timed out
                                                                       at java.net.SocketInputStream.socketRead0(Native Method)
                                                                       at java.net.SocketInputStream.socketRead(SocketInputStream.java:114)
                                                                       at java.net.SocketInputStream.read(SocketInputStream.java:170)
                                                                       at java.net.SocketInputStream.read(SocketInputStream.java:139)
                                                                       at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:288)
                                                                       at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:351)
                                                                       at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:180)
                                                                       at java.io.InputStreamReader.read(InputStreamReader.java:184)
                                                                       at java.io.BufferedReader.fill(BufferedReader.java:172)
                                                                       at java.io.BufferedReader.readLine(BufferedReader.java:335)
                                                                       at java.io.BufferedReader.readLine(BufferedReader.java:400)
                                                                       at com.pedro.rtsp.rtsp.RtspClient.getResponse(RtspClient.java:404)
                                                                       at com.pedro.rtsp.rtsp.RtspClient.access$800(RtspClient.java:28)
                                                                       at com.pedro.rtsp.rtsp.RtspClient$1.run(RtspClient.java:184)
                                                                       at java.lang.Thread.run(Thread.java:764)
05-20 13:44:39.326 30961-31084/com.pedro.rtpstreamer E/AndroidRuntime: FATAL EXCEPTION: Thread-6
                                                                       Process: com.pedro.rtpstreamer, PID: 30961
                                                                       java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
                                                                           at java.util.regex.Matcher.reset(Matcher.java:1052)
                                                                           at java.util.regex.Matcher.<init>(Matcher.java:180)
                                                                           at java.util.regex.Pattern.matcher(Pattern.java:1006)
                                                                           at com.pedro.rtsp.rtsp.RtspClient.getResponseStatus(RtspClient.java:503)
                                                                           at com.pedro.rtsp.rtsp.RtspClient.access$1000(RtspClient.java:28)
                                                                           at com.pedro.rtsp.rtsp.RtspClient$1.run(RtspClient.java:185)
                                                                           at java.lang.Thread.run(Thread.java:764)

**Comment by omarmakeen** [comment]
@pedroSG94 You are right, Thanks a lot :)
