### ISSUE TITLE
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.SurfaceView.getContext()' on a null object reference

### ISSUE THREAD

**Issue by anonym24** [pedroSG94/rtmp-rtsp-stream-client-java#181]
```
  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.SurfaceView.getContext()' on a null object reference
        at com.pedro.rtplibrary.base.Camera1Base.<init>(Camera1Base.java:82)
        at com.pedro.rtplibrary.rtsp.RtspCamera1.<init>(RtspCamera1.java:28)
        at com.example.admin.rtmp.MainActivity.onCreate(MainActivity.java:29)
```

at

  ```
 RtspCamera1 rtspCamera1 = new RtspCamera1(mSurfaceView, new ConnectCheckerRtsp() {
                @Override
                public void onConnectionSuccessRtsp() {
                    Log.i(TAG, "onConnectionSuccessRtsp");
                }

                @Override
                public void onConnectionFailedRtsp(String s) {
                    Log.i(TAG, "onConnectionFailedRtsp " + s);
                }

                @Override
                public void onDisconnectRtsp() {
                    Log.i(TAG, "onDisconnectRtsp");
                }

                @Override
                public void onAuthErrorRtsp() {
                    Log.i(TAG, "onAuthErrorRtsp");
                }

                @Override
                public void onAuthSuccessRtsp() {
                    Log.i(TAG, "onAuthSuccessRtsp");
                }
            });
```

**Comment by pedroSG94** [comment]
This look that your surfaceview is null. Make sure that your surface is not null with a conditional
Can you share me full activity code?

**Comment by anonym24** [comment]
```
package com.example.admin.rtmp;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.SurfaceView;

import com.pedro.rtplibrary.rtsp.RtspCamera1;
import com.pedro.rtsp.utils.ConnectCheckerRtsp;

import static android.Manifest.permission.CAMERA;
import static android.Manifest.permission.RECORD_AUDIO;
import static android.Manifest.permission.WRITE_EXTERNAL_STORAGE;

public class MainActivity extends AppCompatActivity {

    private final static String TAG = "RtspClient";

    private SurfaceView mSurfaceView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        requestPermissions(new String[]{WRITE_EXTERNAL_STORAGE, RECORD_AUDIO, CAMERA}, 21);
        mSurfaceView = findViewById(R.id.surfaceView);
        //create builder
        //by default TCP protocol.
        if (true) {
            RtspCamera1 rtspCamera1 = new RtspCamera1(mSurfaceView, new ConnectCheckerRtsp() {
                @Override
                public void onConnectionSuccessRtsp() {
                    Log.i(TAG, "onConnectionSuccessRtsp");
                }

                @Override
                public void onConnectionFailedRtsp(String s) {
                    Log.i(TAG, "onConnectionFailedRtsp " + s);
                }

                @Override
                public void onDisconnectRtsp() {
                    Log.i(TAG, "onDisconnectRtsp");
                }

                @Override
                public void onAuthErrorRtsp() {
                    Log.i(TAG, "onAuthErrorRtsp");
                }

                @Override
                public void onAuthSuccessRtsp() {
                    Log.i(TAG, "onAuthSuccessRtsp");
                }
            });
            //start stream
            if (rtspCamera1.prepareVideo()) {
                rtspCamera1.startStream("rtsp://:8554/");
            } else {
                Log.i(TAG, "device cant init encoders");
                // This device cant init encoders, this could be for 2 reasons: The encoder selected doesnt support any configuration setted or your device hasnt a H264 or AAC encoder (in               //  this case you can see log error valid encoder not found)
            }
            //stop stream
            //rtspCamera1.stopStream();
        }
    }
}

```

layout

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <SurfaceView
        android:id="@+id/surfaceView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

</RelativeLayout>
```

manifest 
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.example.admin.rtmp">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <!--some devices need it-->
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera2.full" />
    <uses-feature android:name="android.hardware.camera2.autofocus" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>

                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>

</manifest>
```

**Comment by pedroSG94** [comment]
OK: I understand your problem now. 2 Problems:
- You don't set layout to your activity so when you find surfaceview by id the result is null(not found).
- You want start stream before surface is inflated you need wait surface is inflated to start stream.

Code example:
```java
public class ExampleActivity extends AppCompatActivity implements SurfaceHolder.Callback {

  private final static String TAG = "RtspClient";

  private SurfaceView mSurfaceView; //Use Openglview for better performance.
  private RtspCamera1 rtspCamera1;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
    mSurfaceView = findViewById(R.id.surfaceView);
    mSurfaceView.getHolder().addCallback(this);
    //by default TCP protocol.
    rtspCamera1 = new RtspCamera1(mSurfaceView, new ConnectCheckerRtsp() {
      @Override
      public void onConnectionSuccessRtsp() {
        Log.i(TAG, "onConnectionSuccessRtsp");
      }

      @Override
      public void onConnectionFailedRtsp(String s) {
        Log.i(TAG, "onConnectionFailedRtsp " + s);
      }

      @Override
      public void onDisconnectRtsp() {
        Log.i(TAG, "onDisconnectRtsp");
      }

      @Override
      public void onAuthErrorRtsp() {
        Log.i(TAG, "onAuthErrorRtsp");
      }

      @Override
      public void onAuthSuccessRtsp() {
        Log.i(TAG, "onAuthSuccessRtsp");
      }
    });
  }

  @Override
  public void surfaceCreated(SurfaceHolder surfaceHolder) {

  }

  @Override
  public void surfaceChanged(SurfaceHolder surfaceHolder, int i, int i1, int i2) {
    //Your surface is inflated. You can stream now
    if (!rtspCamera1.isStreaming()) {
      if (rtspCamera1.prepareVideo() && rtspCamera1.prepareAudio()) {
        rtspCamera1.startStream("rtsp://:8554/");
      } else {
        Log.i(TAG, "device cant init encoders");
      }
    }
  }

  @Override
  public void surfaceDestroyed(SurfaceHolder surfaceHolder) {
    //Your surface is destroyed. You should stop stream here and release camera
    if (rtspCamera1.isStreaming()) {
      rtspCamera1.stopStream();
      rtspCamera1.stopPreview();
    }
  }
}

```

**Comment by anonym24** [comment]
Thanks. Yeah I didn't notice that I didn't set content
Seems this code is for rtsp server
But I need client

**Comment by pedroSG94** [comment]
This code is for stream from a device to a server.
So you need:
- Media server to receive stream: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Media-servers-tested
- Player to visualize stream. I recommend you VLC
