### ISSUE TITLE
do start/stopStream() multiple times

### ISSUE THREAD

**Issue by Loren1994** [pedroSG94/rtmp-rtsp-stream-client-java#199]
I click startStream()/stopStream() button many times,
first time connect success,
android8.1
after many times, startStream connect fail.
EHOSTUNREACH(no route to host)
android4.4
after many times, push stream very slow ,1~10k/s , 
200~300k/s at first time.

android8.1 log
`2018-07-13 11:34:54.262 21479-22600/com.pedro.rtpstreamer W/ExtendedACodec: Failed to get extension for extradata parameter
2018-07-13 11:34:54.499 21479-21479/com.pedro.rtpstreamer W/dro.rtpstreamer: type=1400 audit(0.0:9330): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=17461 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
2018-07-13 11:34:54.495 21479-21479/com.pedro.rtpstreamer I/AudioEncoder: AudioEncoder started
2018-07-13 11:34:54.507 21479-21479/com.pedro.rtpstreamer I/MicrophoneManager: Microphone started
2018-07-13 11:34:54.510 21479-21479/com.pedro.rtpstreamer E/libc: Access denied finding property "camera.hal1.packagelist"
2018-07-13 11:34:54.604 21479-21479/com.pedro.rtpstreamer D/Camera: Lct package name is com.pedro.rtpstreamer
2018-07-13 11:34:54.681 21479-21479/com.pedro.rtpstreamer I/Camera1ApiManager: 2048X1536
2018-07-13 11:34:54.681 21479-21479/com.pedro.rtpstreamer I/Choreographer: Skipped 37 frames!  The application may be doing too much work on its main thread.
2018-07-13 11:35:00.113 21479-22670/com.pedro.rtpstreamer E/RtspClient: connection error
    java.net.SocketTimeoutException: failed to connect to /192.168.10.21 (port 10554) from /192.168.10.19 (port 48330) after 5000ms
        at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
        at libcore.io.IoBridge.connect(IoBridge.java:130)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:357)
        at java.net.Socket.connect(Socket.java:616)
        at com.pedro.rtsp.rtsp.RtspClient$1.run(RtspClient.java:159)
        at java.lang.Thread.run(Thread.java:764)
2018-07-13 11:35:00.239 21479-21479/com.pedro.rtpstreamer I/MicrophoneManager: Microphone stopped
2018-07-13 11:35:00.346 21479-21479/com.pedro.rtpstreamer I/AudioEncoder: AudioEncoder stopped
2018-07-13 11:36:34.750 21479-21508/com.pedro.rtpstreamer E/ContentCatcherManager: failed to get ContentCatcherService.
2018-07-13 11:36:34.783 21479-21508/com.pedro.rtpstreamer E/ContentCatcherManager: failed to get ContentCatcherService.`

**Comment by Loren1994** [comment]
it's possible that LightGLSurfaceView callback data is wrong,
because I saw a black screen on VLC player.

**Comment by Loren1994** [comment]
`rtspCamera1!!.prepareAudio() && rtspCamera1!!.prepareVideo(640, 480, 30, 2000000, false, 90)`
I use EasyDarWin RTSP server :https://github.com/EasyDarwin/EasyDarwin
My phone is XIAOMI 6X (android 8.1, it's Chinese manufacturer)
I use SurfaceView now, and problem is not reproduce,and same network.
I do it fast start and stop .
by the way ,my project LightGLSurfaceView or SurfaceView is 1px * 1px,because I would like it no preview.

if I use LightGLSurfaceView, will I setVideoBitrateOnFly(smaller) ?

**Comment by pedroSG94** [comment]
Bitrate should be the same with all mode if you set it I tell you that to temporal fix if you want try it but I will see your error case too.
Can you share me activity exmaple that you use (maybe the resize view is the reason).

**Comment by Loren1994** [comment]
[PushActivity.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/2194537/PushActivity.txt)

xml : 
`
<SurfaceView  //or LightGLSurfaceView
        android:id="@+id/preview_sv"
        android:layout_width="1px"
        android:layout_height="1px" />
`
and some button

**Comment by Loren1994** [comment]
I use LightOpenGLView
`W/art: Long monitor contention with owner Thread-4 (17192) at void com.pedro.rtplibrary.view.LightOpenGlView.run()(LightOpenGlView.java:72) waiters=0 in void com.pedro.rtplibrary.view.OpenGlViewBase.onFrameAvailable(android.graphics.SurfaceTexture) for 115ms`
line72 is " synchronized (sync) {"

this log often appear.
Is it right ?

**Comment by pedroSG94** [comment]
Yes, It should be right.

**Comment by pedroSG94** [comment]
It is only with slow devices? I tried with samsung s6 and same delay in local server with surfaceview, lightopenglview and openglview. (Around 1-2 seconds). My player is VLC in desktop too.
I don't understand this:
```
is it push-frequency low? is it push-data small ?
```
What is frequency low and data small?
Data size depend of video bitrate and fps that your device can generate. Bad fps = less packets send so less bandwidth used because packets size should be the same.

**Note:**You can apply this if you send same image obviously. This depend of color in the image, is not the same send full black image or a normal image with more colors you can see it if you block camera with your hand you will see video packets in the log more light

**Comment by Loren1994** [comment]
sorry, I am not good at English.
I will try it again.
thank you.

**Comment by pedroSG94** [comment]
I wanted to say what is low frequency low and data small for you.
Data small is packet size? I told you my response because I thought that.
Frequency low is FPS(frames per second)? In this case nothing to do (maybe I could try get more performance, but no more and I don't know how do it).

**Comment by Loren1994** [comment]
yes, you're right. 
I found that video stream too slow , delay time around 5s~8s and not fluent by VLC when I use LightOpenGlView, and I don't use SurfaceView because of often appear "frame discard".
but now I think it should be a problem with my smart device(not phone,too slow).
so , thank you .😀
