### ISSUE TITLE
java.lang.IllegalStateException: Queue full

### ISSUE THREAD

**Issue by jutikorn** [pedroSG94/rtmp-rtsp-stream-client-java#20]
```
frame discarded, cant add more frames: 
                                                                      java.lang.IllegalStateException: Queue full
                                                                          at java.util.AbstractQueue.add(AbstractQueue.java:69)
                                                                          at com.pedro.encoder.video.VideoEncoder.inputNv21Data(VideoEncoder.java:286)
                                                                          at com.pedro.builder.base.BuilderBase.inputNv21Data(BuilderBase.java:185)
                                                                          at com.pedro.encoder.input.video.Camera1ApiManager.onPreviewFrame(Camera1ApiManager.java:192)
                                                                          at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1563)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:168)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5845)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
```

happened immediately when I tried to stream with RTMP (both default and custom)

**Comment by pedroSG94** [comment]
The stream should work with that error.
It happens when you add more than 40 frame to the encoder queue and then discard that frames to preserve memory and sync. Normally this is because your device is working to slow.
See if you send video and audio packets.
Let me know too your device model and API.
If you never send any packets i will need more informative log because it don't should be a problem for work.
