### ISSUE TITLE
OpenGlView rare crash on device rotation

### ISSUE THREAD

**Issue by andrewBatutin** [pedroSG94/rtmp-rtsp-stream-client-java#253]
Device: CLT-L29 Huawei, Android 8.1
SDK version 1.4.2

Sometimes after app is rotated to landscape i've got a crash in OpenGlView

`Fatal Exception: java.lang.RuntimeException: eglCreateWindowSurface: EGL error: 0x3003
       at com.pedro.encoder.utils.gl.GlUtil.checkEglError(GlUtil.java:134)
       at com.pedro.encoder.input.gl.SurfaceManager.eglSetup(SurfaceManager.java:143)
       at com.pedro.encoder.input.gl.SurfaceManager.<init>(SurfaceManager.java:54)
       at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:101)
       at java.lang.Thread.run(Thread.java:784)`

it is rare bug but it happens from time to time

crash log attached
[tv.corecloud.streamer_issue_6_crash_5BEB334B0252000111C787D6F955A84B_DNE_1_v2.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/2581824/tv.corecloud.streamer_issue_6_crash_5BEB334B0252000111C787D6F955A84B_DNE_1_v2.txt)

**Comment by pedroSG94** [comment]
Only in that device?
Are you doing rotate while stream or record or only with preview?
I will try with my devices to rotate multiple times to reproduce it.

**Comment by andrewBatutin** [comment]
on several devices

only preview

it's happens from time to time, but not that often 

BTW
can we rotate camera while streaming?

**Comment by pedroSG94** [comment]
I means stream with activity not blocked and stop stream or record on surfacedestroyed callback.

**Comment by andrewBatutin** [comment]
well the steps to reproduce are next:
- you start at portrait 
- start streaming
- stop streaming
- turn device to landscape
- startPreview method is called to update the view for the new dimensions
- crash

**Comment by pedroSG94** [comment]
I did that steps multiple times but I can't reproduce it on S7, S6 and nexus 5. Maybe I should try more times.
For now, I was doing an investigation about this crash and this error could be an invalid surface setted to:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/OpenGlView.java#L101

- Possible reason could be that your device inflate view so fast.

**Comment by pedroSG94** [comment]
When you get this error. The lines before that logcat tell you something similar to?
```
already connected to another API
```

**Comment by pedroSG94** [comment]
For now, I can't reproduce any error but I did a refactor that could fix your error. Please try last commit and confirm me if any error is fixed.

**Comment by andrewBatutin** [comment]
ok
will keep you posted about the issue
