### ISSUE TITLE
Camera2 + OpenGL crash when start recording on some devices

### ISSUE THREAD

**Issue by arkadiyo** [pedroSG94/rtmp-rtsp-stream-client-java#263]
We are trying to implement camera2 api + OpenGlView. But, when we start recording on some devices (Sony Xperia XZ, Lenovo a6010), application crashes with error:
```
USER_COMMENT=null
ANDROID_VERSION=5.1.1
APP_VERSION_NAME=1.1.6
BRAND=Sony
PHONE_MODEL=C6903
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: eglCreateWindowSurface: EGL error: 0x3003
at com.pedro.encoder.utils.gl.GlUtil.checkEglError(GlUtil.java:134)
at com.pedro.encoder.input.gl.SurfaceManager.eglSetup(SurfaceManager.java:131)
at com.pedro.encoder.input.gl.SurfaceManager.<init>(SurfaceManager.java:46)
at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:101)
at java.lang.Thread.run(Thread.java:818)
```

It's the manifest fragment with permissions:
```
<uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.FLASHLIGHT" />

<uses-feature
        android:name="android.hardware.camera"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.camera2.full"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.camera2.autofocus"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.microphone"
        android:required="false" />
```

nginx-rtmp on the server side.

We are working last few days on this problem and have no idea for the moment, how to resolve the issue. Can you help?

**Comment by pedroSG94** [comment]
I did a fix for it. Can you tell me if it is solved?
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/33222788f31a14aa41e584fa996199e4b8c580a2

**Comment by arkadiyo** [comment]
Thank you very much for the quick reply! We will test it on our morning. And I will report you in next 12 hours.
Arkadiy & Artak

**Comment by arkadiyo** [comment]
The error is no longer displayed, but application freezes on this code:
```
@Override
    public void start() {
        synchronized (sync) {
            Log.i(TAG, "Thread started.");
            thread = new Thread(this);
            running = true;
            thread.start();
            
            //on this line app freezes, and views are not displayed
            semaphore.acquireUninterruptibly();
        }
    }


protected void releaseSurfaceManager() {
        // method releaseSurfaceManager() called, but it's code is not executed
        synchronized (sync) {
            if (surfaceManager != null) {
                surfaceManager.release();
                surfaceManager = null;
            }
        }
    }
```

**Comment by pedroSG94** [comment]
It is rare, it was working for me. I did other commit to fix it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/2448e28c9f0fcb94575efb87fb42cbeb800fa82d

**Comment by arkadiyo** [comment]
Great! Problem is solved. This version works well. Thank you for your help!!!

**Comment by pedroSG94** [comment]
Thank you for you collaboration :D
Issue closed.
