### ISSUE TITLE
[Ant Media Server] Invalid RTMP protocol version

### ISSUE THREAD

**Issue by iostreamchik** [pedroSG94/rtmp-rtsp-stream-client-java#268]
I'm getting the error trying broadcast through [Ant Media Server](https://github.com/ant-media/Ant-Media-Server)

```
RtmpConnection: Error
    java.io.IOException: Invalid RTMP protocol version; expected 3, got 72
        at com.github.faucamp.simplertmp.packets.Handshake.readS0(Handshake.java:57)
        at com.github.faucamp.simplertmp.io.RtmpConnection.handshake(RtmpConnection.java:93)
        at com.github.faucamp.simplertmp.io.RtmpConnection.connect(RtmpConnection.java:143)
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.connect(DefaultRtmpPublisher.java:21)
        at net.ossrs.rtmp.SrsFlvMuxer.connect(SrsFlvMuxer.java:125)
        at net.ossrs.rtmp.SrsFlvMuxer.access$000(SrsFlvMuxer.java:45)
        at net.ossrs.rtmp.SrsFlvMuxer$1.run(SrsFlvMuxer.java:161)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by iostreamchik** [comment]
Fixed. Got the successful connection to secure Ant Media Server channel.
@pedroSG94, thank you.

**Comment by iostreamchik** [comment]
@Fixed.
