### ISSUE TITLE
Restart stream without stop recording?

### ISSUE THREAD

**Issue by HraD** [pedroSG94/rtmp-rtsp-stream-client-java#287]
Hi again!
Is it possible to restart or start/stop stream without stopping video recording? Camera2 API.
E.g. network problems, i got onConnectionFailedRtmp/onDisconnectRtmp and need to restart same stream again, but not to stop recording.
I got Fatal Exception in my code and in your sample app too.
`
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pedro.rtpstreamer, PID: 14842
    java.lang.IllegalStateException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2068)
        at com.pedro.encoder.video.VideoEncoder.start(VideoEncoder.java:238)
        at com.pedro.encoder.video.VideoEncoder.start(VideoEncoder.java:219)
....
`

or 

`
onConnectionFailedRtmp Attempt to invoke virtual method 'void android.media.MediaCodec.start()' on a null object reference
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaCodec.start()' on a null object reference
        at com.pedro.encoder.video.VideoEncoder.start(VideoEncoder.java:238)
        at com.pedro.encoder.video.VideoEncoder.start(VideoEncoder.java:219)
        at com.pedro.rtplibrary.base.Camera2Base.startEncoders(Camera2Base.java:353)
        at com.pedro.rtplibrary.base.Camera2Base.startStream(Camera2Base.java:343)
...
`

To reproduce: start sample app, goto OpenGL RTMP (RTMPCamera1 replaced to RTMPCamera2), press Start stream, Start record, Stop stream, Start stream -> Crash.

**Comment by pedroSG94** [comment]
It is working for me. Did you clone my last commit?. (I did a commit 2 hours ago).
Also let me know server used and android device model and API.

**Comment by HraD** [comment]
Thanks, it works with last commit

**Comment by mrgaric** [comment]
Hi, i have the same problem. I call startStream->stopStream->startStream and I get an error

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaCodec.setCallback(android.media.MediaCodec$Callback, android.os.Handler)' on a null object reference
        at com.pedro.encoder.video.VideoEncoder.start(VideoEncoder.java:158)
        at com.pedro.encoder.BaseEncoder.start(BaseEncoder.java:25)
        at com.pedro.rtplibrary.base.Camera2Base.startEncoders(Camera2Base.java:441)
        at com.pedro.rtplibrary.base.Camera2Base.startStream(Camera2Base.java:432)
```

I use RtmpCamera2 and OpenGlView
lib version - 1.8.4
