### ISSUE TITLE
Null Pointer Exception at writeVideoSample

### ISSUE THREAD

**Issue by ElectronHerder** [pedroSG94/rtmp-rtsp-stream-client-java#294]
So far, your rtmp streaming library is the very best I have found. I'm testing on various devices and your sample program works flawlessly. I am running into a problem, however, on an older Samsung Galaxy SIII with Android 4.4 Kitkat. Your sample program works just fine, streaming to my server without a glitch. However, my own app runs into trouble. This may be related to the device having a slower processor or less available memory (?).

I am including your video streaming code in a very busy screen with a Mapbox map, use of location and compass information and some other UI elements that demand UI thread time. Perhaps there is too much going on. My newer devices can handle it but this phone will occasionally get a crash with the following debug information:

D/RtmpConnection: wrote packet: RTMP Audio, size: 374
    wrote packet: RTMP Audio, size: 371
D/RtmpConnection: wrote packet: RTMP Audio, size: 391
    wrote packet: RTMP Audio, size: 378
W/dalvikvm: threadid=24: thread exiting with uncaught exception (group=0x4178bda0)
E/AndroidRuntime: FATAL EXCEPTION: Thread-674
    Process: com.rescueresponder.commtestandroid, PID: 13759
    java.lang.NullPointerException
        at net.ossrs.rtmp.SrsFlvMuxer$SrsFlv.writeVideoSample(SrsFlvMuxer.java:774)
        at net.ossrs.rtmp.SrsFlvMuxer.sendVideo(SrsFlvMuxer.java:219)
        at com.pedro.rtplibrary.rtmp.RtmpCamera1.getH264DataRtp(RtmpCamera1.java:102)
        at com.pedro.rtplibrary.base.Camera1Base.getVideoData(Camera1Base.java:645)
        at com.pedro.encoder.video.VideoEncoder.getDataFromSurface(VideoEncoder.java:413)
        at com.pedro.encoder.video.VideoEncoder.access$100(VideoEncoder.java:33)
        at com.pedro.encoder.video.VideoEncoder$1.run(VideoEncoder.java:248)
        at java.lang.Thread.run(Thread.java:841)

**Comment by pedroSG94** [comment]
This should fix your issue:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/eb3c1acfe3ff54cac628511ee6ac07f1b2dec7e7

**Comment by ElectronHerder** [comment]
Thank you, it worked! Much appreciated.
