### ISSUE TITLE
Recovering from CameraOpenException

### ISSUE THREAD

**Issue by paNjii** [pedroSG94/rtmp-rtsp-stream-client-java#306]
Hi Pedro,

I am currently working on allowing users to set their parameters to be used with the prepareVideo function. I ran into the following when the parameters are not entirely correct:
```
2019-03-14 18:00:20.755 29513-29513/nl.tno.flame.prosumer.debug E/ProducerFragment: com.pedro.encoder.input.video.CameraOpenException: This camera resolution cant be opened
        at com.pedro.encoder.input.video.Camera1ApiManager.start(Camera1ApiManager.java:121)
        at com.pedro.encoder.input.video.Camera1ApiManager.start(Camera1ApiManager.java:109)
        at com.pedro.encoder.input.video.Camera1ApiManager.start(Camera1ApiManager.java:116)
        at com.pedro.rtplibrary.base.Camera1Base.startEncoders(Camera1Base.java:386)
        at com.pedro.rtplibrary.base.Camera1Base.startStream(Camera1Base.java:372)
```
What I try do to is catch the exception and continue as usual. However, after the CameraOpenException, the preview remains black and does not return to normal.

What I've tried is to call the startPreview and prepareVideo functions again, but the openglview remains black. Do you have any ideas ?

**Comment by pedroSG94** [comment]
You should use this methods to know resolutions supported by your device.
Back camera:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L451
Front camera:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L460

**Comment by paNjii** [comment]
Thanks for the (quick) input pedro, very much appreciated. My interest came from the perspective if this event is recoverable. If it is not, I will go for the direction you just posted.

**Comment by pedroSG94** [comment]
No, you cant handle this error.

**Comment by paNjii** [comment]
Thanks! In that case I will close this issue.
