### ISSUE TITLE
EGL error: 0x3003

### ISSUE THREAD

**Issue by danilashamin** [pedroSG94/rtmp-rtsp-stream-client-java#333]
Hello!
We have problems with the library version 1.5.3 on device:
# OS Version: 5.0
# Device: Galaxy Note3
# RAM Free: 45.7%
# Disk Free: 80.9%

Fatal Exception: java.lang.RuntimeException: eglCreateWindowSurface: EGL error: 0x3003
       at com.pedro.encoder.utils.gl.GlUtil.checkEglError(GlUtil.java:134)
       at com.pedro.encoder.input.gl.SurfaceManager.eglSetup(SurfaceManager.java:131)
       at com.pedro.encoder.input.gl.SurfaceManager.<init>(SurfaceManager.java:46)
       at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:106)
       at java.lang.Thread.run(Thread.java:818)

Can this be fixed without changing the library version? or the problem may not be in the library?

**Comment by pedroSG94** [comment]
I did a fix for it long time ago but I don't remember version. Onlyclone the project and test it. If the problem persist let me know it.
