### ISSUE TITLE
Connection Failure

### ISSUE THREAD

**Issue by viniciusccarvalho** [pedroSG94/rtmp-rtsp-stream-client-java#36]
Hi, first kudos on setting this up, I've been all over the place looking for an android rtmp client.

I pretty much copied your sample on the SurfaceView, and I'm trying to stream to azure media services. But I keep getting a connection failure, I don't have any more information on the reason why, the endpoint is open, I can test it using other tools, any hints on what could be the cause?

Here's the logcat of the starting of the streaming

```
08-23 09:46:40.920 16915-16915/org.springframework.cloud.stream.videostreaming I/MicrophoneManager: Microphone created, 44100hz, Stereo
08-23 09:46:40.921 16915-16915/org.springframework.cloud.stream.videostreaming I/MicrophoneManager: Microphone created, 44100hz, Stereo
08-23 09:46:40.923 16915-22285/org.springframework.cloud.stream.videostreaming I/OMXClient: MuxOMX ctor
08-23 09:46:40.930 16915-16915/org.springframework.cloud.stream.videostreaming I/VideoEncoder: videoEncoder OMX.qcom.video.encoder.avc type supported: video/avc
08-23 09:46:40.931 16915-16915/org.springframework.cloud.stream.videostreaming W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
08-23 09:46:40.931 16915-16915/org.springframework.cloud.stream.videostreaming W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
08-23 09:46:40.932 16915-16915/org.springframework.cloud.stream.videostreaming I/VideoEncoder: Color supported: 2141391878
08-23 09:46:40.932 16915-16915/org.springframework.cloud.stream.videostreaming I/VideoEncoder: Color supported: 2141391876
08-23 09:46:40.932 16915-16915/org.springframework.cloud.stream.videostreaming I/VideoEncoder: Color supported: 2141391880
08-23 09:46:40.932 16915-16915/org.springframework.cloud.stream.videostreaming I/VideoEncoder: Color supported: 2141391879
08-23 09:46:40.932 16915-16915/org.springframework.cloud.stream.videostreaming I/VideoEncoder: Color supported: 2130708361
08-23 09:46:40.932 16915-16915/org.springframework.cloud.stream.videostreaming I/VideoEncoder: Color supported: 2135033992
08-23 09:46:40.932 16915-16915/org.springframework.cloud.stream.videostreaming I/VideoEncoder: Color supported: 21
08-23 09:46:40.937 16915-22289/org.springframework.cloud.stream.videostreaming I/OMXClient: MuxOMX ctor
08-23 09:46:40.956 16915-22289/org.springframework.cloud.stream.videostreaming E/ACodec: [OMX.qcom.video.encoder.avc] storeMetaDataInBuffers (output) failed w/ err -1010
08-23 09:46:40.957 16915-22289/org.springframework.cloud.stream.videostreaming W/ACodec: do not know color format 0x7fa30c06 = 2141391878
08-23 09:46:40.957 16915-22289/org.springframework.cloud.stream.videostreaming W/ACodec: do not know color format 0x7fa30c04 = 2141391876
08-23 09:46:40.957 16915-22289/org.springframework.cloud.stream.videostreaming W/ACodec: do not know color format 0x7fa30c08 = 2141391880
08-23 09:46:40.958 16915-22289/org.springframework.cloud.stream.videostreaming W/ACodec: do not know color format 0x7fa30c07 = 2141391879
08-23 09:46:40.958 16915-22289/org.springframework.cloud.stream.videostreaming W/ACodec: do not know color format 0x7f000789 = 2130708361
08-23 09:46:40.974 16915-22289/org.springframework.cloud.stream.videostreaming I/ACodec: setupAVCEncoderParameters with [profile: Baseline] [level: Level1]
08-23 09:46:40.977 16915-22289/org.springframework.cloud.stream.videostreaming I/ACodec: [OMX.qcom.video.encoder.avc] cannot encode HDR static metadata. Ignoring.
08-23 09:46:40.977 16915-22289/org.springframework.cloud.stream.videostreaming I/ACodec: setupVideoEncoder succeeded
08-23 09:46:40.982 16915-22289/org.springframework.cloud.stream.videostreaming W/ACodec: do not know color format 0x7f000789 = 2130708361
08-23 09:46:41.026 16915-16915/org.springframework.cloud.stream.videostreaming I/AudioEncoder: AudioEncoder started
08-23 09:46:41.076 16915-22294/org.springframework.cloud.stream.videostreaming I/Camera2ApiManager: camera opened
08-23 09:46:41.078 16915-22294/org.springframework.cloud.stream.videostreaming I/Camera2ApiManager: camera configured
08-23 09:46:41.090 16915-16915/org.springframework.cloud.stream.videostreaming I/MicrophoneManager: Microphone started
08-23 09:46:41.092 16915-22330/org.springframework.cloud.stream.videostreaming I/SrsFlvMuxer: worker: connecting to RTMP server by url=rtmp://xxx.channel.mediaservices.windows.net:1935/live/5dab22a72374418ba322c5e1f5437a33
08-23 09:46:41.092 16915-22330/org.springframework.cloud.stream.videostreaming D/RtmpConnection: connect() called. Host: xxx.channel.mediaservices.windows.net, port: 1935, appName: live, publishPath: 5dab22a72374418ba322c5e1f5437a33
08-23 09:46:41.250 16915-22330/org.springframework.cloud.stream.videostreaming D/RtmpConnection: connect(): socket connection established, doing handhake...
08-23 09:46:41.251 16915-22330/org.springframework.cloud.stream.videostreaming D/Handshake: writeC0
08-23 09:46:41.251 16915-22330/org.springframework.cloud.stream.videostreaming D/Handshake: writeC1
08-23 09:46:41.252 16915-22330/org.springframework.cloud.stream.videostreaming D/Handshake: writeC1(): Calculating digest offset
08-23 09:46:41.252 16915-22330/org.springframework.cloud.stream.videostreaming D/Handshake: writeC1(): (real value of) digestOffset: 352
08-23 09:46:41.252 16915-22330/org.springframework.cloud.stream.videostreaming D/Handshake: writeC1(): recalculated digestOffset: 1128
08-23 09:46:41.253 16915-22330/org.springframework.cloud.stream.videostreaming D/Handshake: writeC1(): digestOffsetBytes: 000061FF
08-23 09:46:41.253 16915-22330/org.springframework.cloud.stream.videostreaming D/Handshake: partBeforeDigest(): size: 1128
08-23 09:46:41.253 16915-22330/org.springframework.cloud.stream.videostreaming D/Handshake: writeC1(): Writing timestamp and Flash Player version
08-23 09:46:41.253 16915-22330/org.springframework.cloud.stream.videostreaming D/Handshake: partAfterDigest(): size: 376
08-23 09:46:41.253 16915-22330/org.springframework.cloud.stream.videostreaming D/Handshake: copying digest offset bytes in partBeforeDigest
08-23 09:46:41.253 16915-22330/org.springframework.cloud.stream.videostreaming D/Handshake: writeC1(): Calculating digest
08-23 09:46:41.253 16915-22330/org.springframework.cloud.stream.videostreaming D/Handshake: writeC1(): writing C1 packet
08-23 09:46:41.254 16915-22330/org.springframework.cloud.stream.videostreaming D/Handshake: readS0
08-23 09:46:41.297 16915-22330/org.springframework.cloud.stream.videostreaming D/Handshake: readS1
08-23 09:46:41.297 16915-22330/org.springframework.cloud.stream.videostreaming D/Handshake: readS1(): S1 total bytes read OK
08-23 09:46:41.297 16915-22330/org.springframework.cloud.stream.videostreaming D/Handshake: readC2
08-23 09:46:41.297 16915-22330/org.springframework.cloud.stream.videostreaming D/Handshake: readS2
08-23 09:46:41.297 16915-22330/org.springframework.cloud.stream.videostreaming D/Handshake: readS2(): S2 total bytes read OK
08-23 09:46:41.297 16915-22330/org.springframework.cloud.stream.videostreaming D/RtmpConnection: connect(): handshake done
08-23 09:46:41.297 16915-22330/org.springframework.cloud.stream.videostreaming D/RtmpConnection: rtmpConnect(): Building 'connect' invoke packet
08-23 09:46:41.297 16915-22353/org.springframework.cloud.stream.videostreaming D/RtmpConnection: starting main rx handler loop
08-23 09:46:41.298 16915-22330/org.springframework.cloud.stream.videostreaming D/RtmpConnection: wrote packet: RTMP Command (command: connect, transaction ID: 1), size: 312
08-23 09:46:41.478 16915-22289/org.springframework.cloud.stream.videostreaming D/ACodec: dataspace changed to 0x10c40000 (R:2(Limited), P:4(BT601_6_525), M:3(BT601_6), T:3(SMPTE170M)) (R:2(Limited), S:4(BT601_525), T:3(SMPTE_170M))
08-23 09:46:41.488 16915-22293/org.springframework.cloud.stream.videostreaming I/SrsFlvMuxer: annexb demux 29B, pts=487, frame=17B, nalu=7
08-23 09:46:41.488 16915-22293/org.springframework.cloud.stream.videostreaming I/SrsFlvMuxer: annexb demux 29B, pts=487, frame=4B, nalu=8
08-23 09:46:41.488 16915-22293/org.springframework.cloud.stream.videostreaming I/SrsFlvMuxer: flv: h264 sps/pps sent, sps=17B, pps=4B
08-23 09:46:41.511 16915-16924/org.springframework.cloud.stream.videostreaming W/MessageQueue: Handler (android.os.Handler) {f23a81d} sending message to a Handler on a dead thread
                                                                                               java.lang.IllegalStateException: Handler (android.os.Handler) {f23a81d} sending message to a Handler on a dead thread
                                                                                                   at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                                                   at android.os.Handler.enqueueMessage(Handler.java:643)
                                                                                                   at android.os.Handler.sendMessageAtTime(Handler.java:612)
                                                                                                   at android.os.Handler.sendMessageDelayed(Handler.java:582)
                                                                                                   at android.os.Handler.post(Handler.java:338)
                                                                                                   at android.hardware.camera2.dispatch.HandlerDispatcher.dispatch(HandlerDispatcher.java:61)
                                                                                                   at android.hardware.camera2.dispatch.MethodNameInvoker.invoke(MethodNameInvoker.java:88)
                                                                                                   at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.onClosed(CallbackProxies.java:177)
                                                                                                   at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:404)
                                                                                                   at android.hardware.camera2.impl.CameraCaptureSessionImpl.finalize(CameraCaptureSessionImpl.java:619)
                                                                                                   at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
                                                                                                   at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
                                                                                                   at java.lang.Thread.run(Thread.java:761)
08-23 09:46:41.600 16915-16915/org.springframework.cloud.stream.videostreaming I/MicrophoneManager: Microphone stopped
08-23 09:46:41.600 16915-22330/org.springframework.cloud.stream.videostreaming D/RtmpConnection: socket closed
08-23 09:46:41.601 16915-16915/org.springframework.cloud.stream.videostreaming I/SrsFlvMuxer: SrsFlvMuxer closed
08-23 09:46:41.604 16915-22366/org.springframework.cloud.stream.videostreaming I/SrsFlvMuxer: worker: disconnect ok.
08-23 09:46:41.624 16915-16915/org.springframework.cloud.stream.videostreaming I/AudioEncoder: AudioEncoder stopped
08-23 09:46:41.624 16915-16915/org.springframework.cloud.stream.videostreaming I/Choreographer: Skipped 31 frames!  The application may be doing too much work on its main thread.
08-23 09:46:41.633 16915-16915/org.springframework.cloud.stream.videostreaming I/MicrophoneManager: Microphone stopped
08-23 09:46:41.633 16915-16915/org.springframework.cloud.stream.videostreaming I/SrsFlvMuxer: SrsFlvMuxer closed
08-23 09:46:41.634 16915-16915/org.springframework.cloud.stream.videostreaming I/AudioEncoder: AudioEncoder stopped
08-23 09:46:41.634 16915-22367/org.springframework.cloud.stream.videostreaming I/SrsFlvMuxer: worker: disconnect ok.

```

**Comment by pedroSG94** [comment]
This look a problem with a connect packet response from server, maybe any param is not supported for azure server. Maybe flash version is the problem.
Go to:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L185
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L220
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L258
and replace with:
`args.setProperty("flashVer", "LNX 11,2,202,233");`

If the problem persists, let me know a rtmp url for test or instructions to install azure server for debug

**Comment by pnobbe** [comment]
Hi, sorry for reopening an old issue but this issue is currently affecting me. I have tried changing the `flashVer` as per your last comment but this does not resolve the problem.

If you are still willing to help resolve the issue let me know and I can get an RTMP url for testing purposes.

**Comment by pedroSG94** [comment]
Hi, If you can give me an url for test I can do it more easy. You ca send me url to email if you want
