### ISSUE TITLE
Red5 connection

### ISSUE THREAD

**Issue by MikeMannox** [pedroSG94/rtmp-rtsp-stream-client-java#39]
Hi, 
I am trying to broadcast live video to the open source Red5 Media Server using RTMP (_not sure if it supports RTSP yet_)
[Red5](http://red5.org/)
[releases](https://github.com/Red5/red5-server/releases)

I have the oflaDemo app running, an instance of _Simple Subscriber_ in a browser tab and I set the app to broadcast to `rtmp://<ubuntu-server-local-network-ip>/oflaDemo`.
The app appears to connect to the server, but crashes shortly after on an NPE.

```
: Process: com.pedro.rtmpstreamer, PID: 8948
: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaCodec.start()' on a null object reference
: 	at com.pedro.encoder.video.VideoEncoder.start(VideoEncoder.java:199)
: 	at com.pedro.builder.base.BuilderBase.startStream(BuilderBase.java:113)
: 	at com.pedro.rtmpstreamer.defaultexample.ExampleRtspActivity.onClick(ExampleRtspActivity.java:100)
: 	at android.view.View.performClick(View.java:6199)
: 	at android.widget.TextView.performClick(TextView.java:11090)
: 	at android.view.View$PerformClick.run(View.java:23647)
: 	at android.os.Handler.handleCallback(Handler.java:751)
: 	at android.os.Handler.dispatchMessage(Handler.java:95)
: 	at android.os.Looper.loop(Looper.java:154)
: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
: 	at java.lang.reflect.Method.invoke(Native Method)
: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

Any suggestions on how I might fix this?

**Comment by pedroSG94** [comment]
It look like you never called preparevideo method. Did you see readme example?
Can you show me code used?

**Comment by MikeMannox** [comment]
Sorry about the above stack trace, I mistakenly copied the trace from one of the many, and didn't notice it was for `ExampleRtspActivity` (they all were crashing on the same point).

I am running your demo app I have read [README.md](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/README.md), but I am testing using the demo app for this project (rtmp-rtsp-stream-client-java)

You are right about the url, I had to download the Flash `SimpleSubscriber.fla` file to find the name of the broadcast the _Simple Subscriber_ was subscribing to:
`rmtp://<ubuntu-server-local-network-ip>/oflaDemo/red5BroadcastDemo`
This stopped the above crash. 

The issue I have now:
once I try to broadcast by pressing _Start Stream_ I receive a `Connection failed` toast and can not see a clear reason why in LogCat.

**Comment by MikeMannox** [comment]
Stacktrace for above

```
com.pedro.rtmpstreamer I/MicrophoneManager: Microphone created, 44100hz, Stereo
com.pedro.rtmpstreamer I/MicrophoneManager: Microphone created, 44100hz, Stereo
com.pedro.rtmpstreamer I/ACodec:  [] Now uninitialized
com.pedro.rtmpstreamer I/ACodec: [] onAllocateComponent
com.pedro.rtmpstreamer I/OMXClient: MuxOMX ctor
com.pedro.rtmpstreamer I/ACodec: Set Google AAC Dec for aacProfile 0
com.pedro.rtmpstreamer I/ACodec: [OMX.google.aac.encoder] Now Loaded
com.pedro.rtmpstreamer I/VideoEncoder: videoEncoder OMX.Exynos.AVC.Encoder type supported: video/avc
com.pedro.rtmpstreamer W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
com.pedro.rtmpstreamer W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
com.pedro.rtmpstreamer W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
com.pedro.rtmpstreamer W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
com.pedro.rtmpstreamer W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
com.pedro.rtmpstreamer W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
com.pedro.rtmpstreamer W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
com.pedro.rtmpstreamer W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
com.pedro.rtmpstreamer W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
com.pedro.rtmpstreamer W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
com.pedro.rtmpstreamer W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
com.pedro.rtmpstreamer W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
com.pedro.rtmpstreamer W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
com.pedro.rtmpstreamer W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
com.pedro.rtmpstreamer W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
com.pedro.rtmpstreamer W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
com.pedro.rtmpstreamer W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
com.pedro.rtmpstreamer I/VideoEncoder: Color supported: 2135033992
com.pedro.rtmpstreamer I/VideoEncoder: Color supported: 19
com.pedro.rtmpstreamer I/ACodec:  [] Now uninitialized
com.pedro.rtmpstreamer I/ACodec: [] onAllocateComponent
com.pedro.rtmpstreamer I/OMXClient: MuxOMX ctor
com.pedro.rtmpstreamer I/art: Do partial code cache collection, code=21KB, data=30KB
com.pedro.rtmpstreamer I/art: After code cache collection, code=20KB, data=30KB
com.pedro.rtmpstreamer I/art: Increasing code cache capacity to 128KB
com.pedro.rtmpstreamer I/ACodec: [OMX.Exynos.AVC.Encoder] Now Loaded
com.pedro.rtmpstreamer I/ACodec: setupAVCEncoderParameters with [profile: Baseline] [level: Level31]
com.pedro.rtmpstreamer I/ACodec: Success set VideoMinQP(5/5/5) VideoMaxQP(50/50/50)
com.pedro.rtmpstreamer I/ACodec: [OMX.Exynos.AVC.Encoder] cannot encode color aspects. Ignoring.
com.pedro.rtmpstreamer I/ACodec: [OMX.Exynos.AVC.Encoder] cannot encode HDR static metadata. Ignoring.
com.pedro.rtmpstreamer I/ACodec: setupVideoEncoder succeeded
com.pedro.rtmpstreamer I/ACodec: [OMX.Exynos.AVC.Encoder] Now Loaded->Idle
com.pedro.rtmpstreamer I/SrsFlvMuxer: worker: connecting to RTMP server by url=rmtp://192.168.1.7/oflaDemo/red5BroadcastDemo
com.pedro.rtmpstreamer I/ACodec: [OMX.google.aac.encoder] Now Loaded->Idle
com.pedro.rtmpstreamer I/ACodec: [OMX.google.aac.encoder] Now Idle->Executing
com.pedro.rtmpstreamer I/ACodec: [OMX.google.aac.encoder] Now Executing
com.pedro.rtmpstreamer I/AudioEncoder: AudioEncoder started
com.pedro.rtmpstreamer I/MediaCodec: onMessageReceived(kWhatOutputFormatChanged), prependSPSPPS 0
com.pedro.rtmpstreamer I/ACodec: [OMX.Exynos.AVC.Encoder] Now Idle->Executing
com.pedro.rtmpstreamer I/ACodec: [OMX.Exynos.AVC.Encoder] Now Executing
com.pedro.rtmpstreamer I/Camera1ApiManager: 1088X1088, not supported for encoder
com.pedro.rtmpstreamer I/Camera1ApiManager: 640X480
com.pedro.rtmpstreamer I/MicrophoneManager: Microphone started
com.pedro.rtmpstreamer D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1440x2240]-format:1
com.pedro.rtmpstreamer I/MicrophoneManager: Microphone stopped
com.pedro.rtmpstreamer I/SrsFlvMuxer: SrsFlvMuxer closed
com.pedro.rtmpstreamer I/SrsFlvMuxer: worker: disconnect ok.
com.pedro.rtmpstreamer I/ACodec: [OMX.Exynos.AVC.Encoder] Now Executing->Idle
com.pedro.rtmpstreamer I/ACodec: [OMX.Exynos.AVC.Encoder] Now Idle->Loaded
com.pedro.rtmpstreamer I/ACodec: [OMX.Exynos.AVC.Encoder] Now Loaded
com.pedro.rtmpstreamer I/ACodec:  [OMX.Exynos.AVC.Encoder] Now kWhatShutdownCompleted event : 8445
com.pedro.rtmpstreamer I/MediaCodec: Codec shutdown complete
com.pedro.rtmpstreamer I/ACodec:  [OMX.Exynos.AVC.Encoder] Now uninitialized
com.pedro.rtmpstreamer I/ACodec:  [] Now kWhatShutdownCompleted event : 8445
com.pedro.rtmpstreamer I/MediaCodec: Codec shutdown complete
com.pedro.rtmpstreamer I/ACodec: [OMX.google.aac.encoder] Now Executing->Idle
com.pedro.rtmpstreamer I/ACodec: [OMX.google.aac.encoder] Now Idle->Loaded
com.pedro.rtmpstreamer I/ACodec: [OMX.google.aac.encoder] Now Loaded
com.pedro.rtmpstreamer I/ACodec:  [OMX.google.aac.encoder] Now kWhatShutdownCompleted event : 8445
com.pedro.rtmpstreamer I/MediaCodec: Codec shutdown complete
com.pedro.rtmpstreamer I/ACodec:  [OMX.google.aac.encoder] Now uninitialized
com.pedro.rtmpstreamer I/ACodec:  [] Now kWhatShutdownCompleted event : 8445
com.pedro.rtmpstreamer I/MediaCodec: Codec shutdown complete
com.pedro.rtmpstreamer I/AudioEncoder: AudioEncoder stopped
com.pedro.rtmpstreamer D/ViewRootImpl@654aa1[Toast]: ThreadedRenderer.create() translucent=true
com.pedro.rtmpstreamer D/InputTransport: Input channel constructed: fd=69
com.pedro.rtmpstreamer D/ViewRootImpl@654aa1[Toast]: setView = android.widget.LinearLayout{16404c6 V.E...... ......I. 0,0-0,0} touchMode=true
com.pedro.rtmpstreamer D/ViewRootImpl@654aa1[Toast]: dispatchAttachedToWindow
com.pedro.rtmpstreamer D/ViewRootImpl@654aa1[Toast]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[397,2128][1042,2304] result=0x27 surface={isValid=true 499880552960} surfaceGenerationChanged=true
com.pedro.rtmpstreamer D/ViewRootImpl@654aa1[Toast]: mHardwareRenderer.initialize() mSurface={isValid=true 499880552960} hwInitialized=true
com.pedro.rtmpstreamer D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [645x176]-format:1
com.pedro.rtmpstreamer D/ViewRootImpl@654aa1[Toast]: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
com.pedro.rtmpstreamer D/ViewRootImpl@654aa1[Toast]: mHardwareRenderer.destroy()#4
com.pedro.rtmpstreamer D/ViewRootImpl@82e8c87[Toast]: ThreadedRenderer.create() translucent=true
com.pedro.rtmpstreamer D/InputTransport: Input channel constructed: fd=71
com.pedro.rtmpstreamer D/ViewRootImpl@82e8c87[Toast]: setView = android.widget.LinearLayout{20d27b4 V.E...... ......I. 0,0-0,0} touchMode=true
com.pedro.rtmpstreamer D/ViewRootImpl@654aa1[Toast]: dispatchDetachedFromWindow
com.pedro.rtmpstreamer D/InputTransport: Input channel destroyed: fd=69
com.pedro.rtmpstreamer D/ViewRootImpl@82e8c87[Toast]: dispatchAttachedToWindow
com.pedro.rtmpstreamer D/ViewRootImpl@82e8c87[Toast]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[447,2128][993,2304] result=0x27 surface={isValid=true 499880552960} surfaceGenerationChanged=true
com.pedro.rtmpstreamer D/ViewRootImpl@82e8c87[Toast]: mHardwareRenderer.initialize() mSurface={isValid=true 499880552960} hwInitialized=true
com.pedro.rtmpstreamer D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [546x176]-format:1
com.pedro.rtmpstreamer D/ViewRootImpl@82e8c87[Toast]: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
com.pedro.rtmpstreamer D/ViewRootImpl@82e8c87[Toast]: mHardwareRenderer.destroy()#4
com.pedro.rtmpstreamer D/ViewRootImpl@82e8c87[Toast]: dispatchDetachedFromWindow
com.pedro.rtmpstreamer D/InputTransport: Input channel destroyed: fd=71
```

**Comment by pedroSG94** [comment]
com.pedro.rtmpstreamer I/SrsFlvMuxer: worker: connecting to RTMP server by url=rmtp://192.168.1.7/oflaDemo/red5BroadcastDemo

incorrect url, should be rtmp not rmtp

**Comment by MikeMannox** [comment]
I am sorry for this... a school-boy mistake!
OK, I have `Connection success` now :)
(no image being displayed in Browser though (http://192.168.1.7/demos/simpleSubscriber.html)

**Comment by pedroSG94** [comment]
I cant see your local file.
First of all see logcat and tell me if you see video and audio packets writed in it.
To make sure if library is working donwload VLC and open your URL or use ffplay command.
Your ffplay command is like:
`ffplay rtmp://<ubuntu-server-local-network-ip>/oflaDemo/red5BroadcastDemo`

**Comment by MikeMannox** [comment]
Hi, 
Yes, it is sending packets a snippet:

```java
com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Audio, size: 395
com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Video, size: 2431
com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Audio, size: 384
com.pedro.rtmpstreamer W/RtmpConnection: handleRxPacketLoop(): Not handling unimplemented/unknown packet of type: ACKNOWLEDGEMENT
com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Audio, size: 381
com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Audio, size: 371
com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Video, size: 3279
com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Audio, size: 370
com.pedro.rtmpstreamer I/SrsFlvMuxer: worker: send frame type=9, dts=476615, size=131072B
com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Video, size: 25039
com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Audio, size: 375
com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Audio, size: 379
com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Video, size: 3789
com.pedro.rtmpstreamer W/art: Suspending all threads took: 15.243ms
com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Audio, size: 382
com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Audio, size: 389
```

However, pasting the `rtmp://<ubuntu-server-local-network-ip>/oflaDemo/red5BroadcastDemo` _URL_ into the _Network_ tab, after a short while I can hear audio, but unfortunately see no video.

I am not sure where to find `ffplay` 
(I am on a MacOS Sierra with VLC installed)

**Comment by pedroSG94** [comment]
ffplay is a ffmpeg command, you need install that library.
But you can get the stream with VLC insteand of ffplay (both do the same).
Open a URL with VLC, use the same URL that you use to put stream with the library.
I'm not sure in Mac but in Linux the option is in:
VLC > Media > Open network location > Play

If the problem persists using VLC then I will install RED5 server and test the problem. Can you give me the tutorial that you follow to install RED5 and reproduce the problem?

**Comment by MikeMannox** [comment]
[Installation directions can be found here](https://github.com/Red5/red5-server/wiki/Installation-on-Linux) as I installed Red5 on a spare Ubuntu box.

Once installed open a browser & point to : http://localhost:5080

Enable/Allow the Flash Player, then visit the "Demos" page.

I was able to broadcast from one Mac & see the results in the Ubuntu computer using the Broadcast & Simple Subscribe demos. Make sure to edit the rtmp IP addresses, then press the strange little icon under the TextField to connect.

In your Android app, I point to `rtmp://<ubuntu-server-local-network-ip>/oflaDemo/red5BroadcastDemo` (this is the stream name hardcoded in the .fla file)

As mentioned, the Android app connects & shows packet data. Opening the network URL in VLC only played sound for me. (VLC, is pretty much the same on Mac.)

**Comment by MikeMannox** [comment]
After installing `FFMPEG`on the Ubuntu box & running:
```bash
ffplay rtmp://192.168.1.7/oflaDemo/red5BroadcastDemo
```
I get:
```bash
Closing connection: NetStream.Play.StreamNotFound sq=    0B f=0/0   
rtmp://192.168.1.7/oflaDemo/red5BroadcastDemo: Unknown error occurred
```
All devices are on the same network and the Red5 instance is running

**Comment by pedroSG94** [comment]
That get stream from sever, before do ffplay you need start a stream.
You can do it with ffmpeg or with my library.
ffmpeg command:
`ffmpeg -i pathtomp4file -f flv rtmp://192.168.1.7/oflaDemo/red5BroadcastDemo`

**Comment by MikeMannox** [comment]
Quite possibly, I have wowza server sunning quite nicely, but seem to be stalling with Red5.
Maybe @mondain could help...?
As he appears to be the main contributor to Red5 lately
https://github.com/mondain

**Comment by mondain** [comment]
I'll look at it as soon as I can; no promises other than that.

**Comment by pedroSG94** [comment]
Thank you @mondain, please notify the result when you finish.
I don't know if red5 RTSP will work with my library because a did a implemention for wowza and I never  tested in other server.
For example I tested with easydarwin to see this issue: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/38
But server close connection to library because don't send a packet supported for server.

**Comment by MikeMannox** [comment]
Hi @mondain, did you manage to take a look? Could you please offer some feedback?
I would love to use the Red-5 Open Source project.

Also the plugins for Red5 do not compile. Are there any releases available for download?

Many thanks in advance

**Comment by MikeMannox** [comment]
I spotted this in another test of Red5 again today (my Wowza trial ran out :gun:)

```java
10-02 18:33:33.618 19867-21171/com.dailymail.online.broadcaster W/System.err: java.io.IOException: Invalid RTMP protocol version; expected 3, got 72
10-02 18:33:33.619 19867-21171/com.dailymail.online.broadcaster W/System.err:     at com.github.faucamp.simplertmp.packets.Handshake.readS0(Handshake.java:54)
10-02 18:33:33.619 19867-21171/com.dailymail.online.broadcaster W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.handshake(RtmpConnection.java:99)
10-02 18:33:33.619 19867-21171/com.dailymail.online.broadcaster W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.connect(RtmpConnection.java:144)
10-02 18:33:33.619 19867-21171/com.dailymail.online.broadcaster W/System.err:     at com.github.faucamp.simplertmp.DefaultRtmpPublisher.connect(DefaultRtmpPublisher.java:26)
10-02 18:33:33.619 19867-21171/com.dailymail.online.broadcaster W/System.err:     at net.ossrs.rtmp.SrsFlvMuxer.connect(SrsFlvMuxer.java:123)
10-02 18:33:33.619 19867-21171/com.dailymail.online.broadcaster W/System.err:     at net.ossrs.rtmp.SrsFlvMuxer.access$000(SrsFlvMuxer.java:46)
10-02 18:33:33.619 19867-21171/com.dailymail.online.broadcaster W/System.err:     at net.ossrs.rtmp.SrsFlvMuxer$1.run(SrsFlvMuxer.java:159)
10-02 18:33:33.619 19867-21171/com.dailymail.online.broadcaster W/System.err:     at java.lang.Thread.run(Thread.java:762)
10-02 18:33:33.623 19867-21171/com.dailymail.online.broadcaster I/System.out: onConnectionFailedRtmp() Thread[Thread-4,5,main] 
10-02 18:33:33.623 19867-21171/com.dailymail.online.broadcaster I/System.out: MainCameraControl$conne .onConnectionFailedRtmp(MainCameraControl.kt:62)
```

**Comment by MikeMannox** [comment]
I spotted this in another test of Red5 again today (my Wowza trial ran out :gun:)

```java
W/System.err: java.io.IOException: Invalid RTMP protocol version; expected 3, got 72
W/System.err:     at com.github.faucamp.simplertmp.packets.Handshake.readS0(Handshake.java:54)
W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.handshake(RtmpConnection.java:99)
W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.connect(RtmpConnection.java:144)
W/System.err:     at com.github.faucamp.simplertmp.DefaultRtmpPublisher.connect(DefaultRtmpPublisher.W/System.err:     at net.ossrs.rtmp.SrsFlvMuxer.connect(SrsFlvMuxer.java:123)
W/System.err:     at net.ossrs.rtmp.SrsFlvMuxer.access$000(SrsFlvMuxer.java:46)
W/System.err:     at net.ossrs.rtmp.SrsFlvMuxer$1.run(SrsFlvMuxer.java:159)
W/System.err:     at java.lang.Thread.run(Thread.java:762)
I/System.out: onConnectionFailedRtmp() Thread[Thread-4,5,main] 
I/System.out: MainCameraControl$conne .onConnectionFailedRtmp(MainCameraControl.kt:62)
```

**Comment by MikeMannox** [comment]
I create an SWF to help test the stream 
https://github.com/MikeMannox/RtpSubscriber/releases/tag/1.0

**Comment by ozankonur** [comment]
Hi, so, is it possible to connection between red5 & rtmp-rtsp-stream-client ?

**Comment by MikeMannox** [comment]
Yes, works perfectly
