### ISSUE TITLE
  java.lang.IllegalStateException

### ISSUE THREAD

**Issue by woipot** [pedroSG94/rtmp-rtsp-stream-client-java#391]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2622)
        at com.pedro.encoder.video.VideoEncoder.getDataFromSurfaceAPI21(VideoEncoder.java:363)
        at com.pedro.encoder.video.VideoEncoder.access$000(VideoEncoder.java:33)
        at com.pedro.encoder.video.VideoEncoder$1.run(VideoEncoder.java:249)
        at java.lang.Thread.run(Thread.java:764)

**Comment by pedroSG94** [comment]
Duplicated. Please, respond question in this issue to help me fix it.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/387
