### ISSUE TITLE
 java.net.SocketTimeoutException: connect timed out on RTMP streaming

### ISSUE THREAD

**Issue by saching13** [pedroSG94/rtmp-rtsp-stream-client-java#419]
E/RtmpConnection: Error
    java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
        at java.net.Socket.connect(Socket.java:605)
        at com.github.faucamp.simplertmp.io.RtmpConnection.connect(RtmpConnection.java:143)
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.connect(DefaultRtmpPublisher.java:22)
        at net.ossrs.rtmp.SrsFlvMuxer.connect(SrsFlvMuxer.java:124)
        at net.ossrs.rtmp.SrsFlvMuxer.access$000(SrsFlvMuxer.java:45)
        at net.ossrs.rtmp.SrsFlvMuxer$1.run(SrsFlvMuxer.java:160)
        at java.lang.Thread.run(Thread.java:761

This is the error I am getting. I have started a rtmp server using nginx port 1935 on my laptop. both my laptop and phone are connected to the same wifi but it is unable to connect to it. I am a newbies to rtmp so can I get some help here

**Comment by pedroSG94** [comment]
Try with ffmpeg to test server. Also check that nginx service is running
By default nginx should create an endpoint like:
rtmp://ip:1935/live/name

**Comment by saching13** [comment]
Hey, thank you I tried with OBS studio and it worked so server worked fine and yeah I was able to fix the server issue. It was Mac firewall rejecting the communication. But now the app  is able to stream to youtube romp link but when I give my local server rtmp link inside LAN it connects and shows black screen. But I can hear audio in that but not video. Can you help me with that. I am kind of new to this.

**Comment by pedroSG94** [comment]
Can you see this log?:
```java
wrote packet: RTMP Video, size: xxx
```
In this case my library send video to server. Make sure that your player is working fine. Use VLC or ffplay to discard player problems. Also check server logcat to know bandwidth used and check if you are getting video.
If you can't find the error let me know server and player used to reproduce your case.
