### ISSUE TITLE
shutdown socket exception after Wifi state changed 

### ISSUE THREAD

**Issue by woipot** [pedroSG94/rtmp-rtsp-stream-client-java#427]
Hi, an error occurred after turning off Wifi. When I turned on Wifi again, the stream stopped connecting to the server with an error: "Error configure stream, publish permitted failed"

2019-10-11 17:15:47.689 23812-28477/com.pedro.rtpstreamer E/RtmpConnection: Shutdown socket
    java.io.IOException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:267)
        at java.net.AbstractPlainSocketImpl.shutdownInput(AbstractPlainSocketImpl.java:582)
        at java.net.Socket.shutdownInput(Socket.java:1565)
        at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:401)
        at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:381)
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:31)
        at net.ossrs.rtmp.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:172)
        at net.ossrs.rtmp.SrsFlvMuxer.access$1000(SrsFlvMuxer.java:48)
        at net.ossrs.rtmp.SrsFlvMuxer$3.run(SrsFlvMuxer.java:319)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.system.ErrnoException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at libcore.io.Linux.shutdown(Native Method)
        at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:176)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:265)

**Comment by pedroSG94** [comment]
I can't reproduce it. Can you tell me server used, Android device API and model?
