### ISSUE TITLE
Cannot retry connection after switching network

### ISSUE THREAD

**Issue by beerpcc** [pedroSG94/rtmp-rtsp-stream-client-java#435]
I'm trying to reconnect after switching network but i got an error
```
java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(Unknown Source:0)
        at com.pedro.encoder.BaseEncoder.stop(BaseEncoder.java:35)
        at com.pedro.encoder.video.VideoEncoder.reset(VideoEncoder.java:174)
        at com.pedro.rtplibrary.base.Camera2Base.resetVideoEncoder(Camera2Base.java:392)
        at com.pedro.rtplibrary.base.Camera2Base.reTry(Camera2Base.java:456)
```

```
override fun onConnectionFailedRtmp(reason: String?) {
        if (rtmpCamera.shouldRetry(reason)) {
            rtmpCamera.reTry(2000)
        }
 }
```

Step to reproduce
1. start stream
2. turn-off wifi and turn on LTE
3. `onConnectionFailedRtmp` will triggered and call `rtmpCamera.reTry(2000)`
4. an error occurred.

Thanks

**Comment by pedroSG94** [comment]
Can you tell me library version?

**Comment by beerpcc** [comment]
1.7.0, thanks

**Comment by pedroSG94** [comment]
I did a fix for it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/f0a10cf9430f8db367b1b4856afb7329eb7b2f57
Download last commit and let me know if all is working fine to update version.

**Comment by beerpcc** [comment]
Seem like it's doesn't fix. I did a test for many times (without modification of my own code), it show different crash and cause activity crash.

```
E/VideoEncoder: Create VideoEncoder failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.createInputSurface(Native Method)
        at com.pedro.encoder.video.VideoEncoder.prepareVideoEncoder(VideoEncoder.java:115)
        at com.pedro.encoder.video.VideoEncoder.reset(VideoEncoder.java:175)
        at com.pedro.rtplibrary.base.Camera2Base.resetVideoEncoder(Camera2Base.java:392)
        at com.pedro.rtplibrary.base.Camera2Base.reTry(Camera2Base.java:458)
        at com.tt.LiveBroadcastActivity.onConnectionFailedRtmp(LiveBroadcastActivity.kt:3164)
        at com.github.faucamp.simplertmp.io.RtmpConnection.sendRtmpPacket(RtmpConnection.java:515)
        at com.github.faucamp.simplertmp.io.RtmpConnection.publishAudioData(RtmpConnection.java:469)
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.publishAudioData(DefaultRtmpPublisher.java:41)
        at net.ossrs.rtmp.SrsFlvMuxer.sendFlvTag(SrsFlvMuxer.java:242)
        at net.ossrs.rtmp.SrsFlvMuxer.access$700(SrsFlvMuxer.java:48)
        at net.ossrs.rtmp.SrsFlvMuxer$2.run(SrsFlvMuxer.java:281)
        at java.lang.Thread.run(Thread.java:919)
2019-10-25 14:54:30.969 1110-7728/? E/OMX-VENC: venc_dev: Unsupported eColorFormat 0x7f000789
2019-10-25 14:54:30.969 19321-19877/com.tt E/AndroidRuntime: FATAL EXCEPTION: Thread-5
    Process: com.tt, PID: 19321
    java.lang.IllegalStateException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(Unknown Source:0)
        at com.pedro.encoder.video.VideoEncoder.start(VideoEncoder.java:140)
        at com.pedro.encoder.video.VideoEncoder.reset(VideoEncoder.java:177)
        at com.pedro.rtplibrary.base.Camera2Base.resetVideoEncoder(Camera2Base.java:392)
        at com.pedro.rtplibrary.base.Camera2Base.reTry(Camera2Base.java:458)
        at com.tt.LiveBroadcastActivity.onConnectionFailedRtmp(LiveBroadcastActivity.kt:3164)
        at com.github.faucamp.simplertmp.io.RtmpConnection.sendRtmpPacket(RtmpConnection.java:515)
        at com.github.faucamp.simplertmp.io.RtmpConnection.publishAudioData(RtmpConnection.java:469)
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.publishAudioData(DefaultRtmpPublisher.java:41)
        at net.ossrs.rtmp.SrsFlvMuxer.sendFlvTag(SrsFlvMuxer.java:242)
        at net.ossrs.rtmp.SrsFlvMuxer.access$700(SrsFlvMuxer.java:48)
        at net.ossrs.rtmp.SrsFlvMuxer$2.run(SrsFlvMuxer.java:281)
        at java.lang.Thread.run(Thread.java:919)
```
```
java.lang.IllegalStateException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(Unknown Source:0)
        at com.pedro.encoder.video.VideoEncoder.start(VideoEncoder.java:140)
        at com.pedro.encoder.video.VideoEncoder.reset(VideoEncoder.java:177)
        at com.pedro.rtplibrary.base.Camera2Base.resetVideoEncoder(Camera2Base.java:392)
        at com.pedro.rtplibrary.base.Camera2Base.reTry(Camera2Base.java:458)
        at com.tt.LiveBroadcastActivity.onConnectionFailedRtmp(LiveBroadcastActivity.kt:3164)
        at com.github.faucamp.simplertmp.io.RtmpConnection.handleRxPacketLoop(RtmpConnection.java:586)
        at com.github.faucamp.simplertmp.io.RtmpConnection.access$000(RtmpConnection.java:44)
        at com.github.faucamp.simplertmp.io.RtmpConnection$1.run(RtmpConnection.java:160)
        at java.lang.Thread.run(Thread.java:919)
```

```
E/RtmpConnection: Error
    java.net.ConnectException: failed to connect to /xx.xx.xxx.xx (port 1935) from /:: (port 0) after 5000ms: connect failed: ENETUNREACH (Network is unreachable)
        at libcore.io.IoBridge.connect(IoBridge.java:143)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
        at java.net.Socket.connect(Socket.java:621)
        at com.github.faucamp.simplertmp.io.RtmpConnection.connect(RtmpConnection.java:138)
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.connect(DefaultRtmpPublisher.java:21)
        at net.ossrs.rtmp.SrsFlvMuxer.connect(SrsFlvMuxer.java:218)
        at net.ossrs.rtmp.SrsFlvMuxer.access$100(SrsFlvMuxer.java:48)
        at net.ossrs.rtmp.SrsFlvMuxer$2.run(SrsFlvMuxer.java:256)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: android.system.ErrnoException: connect failed: ENETUNREACH (Network is unreachable)
        at libcore.io.Linux.connect(Native Method)
        at libcore.io.ForwardingOs.connect(ForwardingOs.java:95)
        at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:136)
        at libcore.io.ForwardingOs.connect(ForwardingOs.java:95)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:174)
        at libcore.io.IoBridge.connect(IoBridge.java:135)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142) 
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390) 
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230) 
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212) 
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436) 
        at java.net.Socket.connect(Socket.java:621) 
        at com.github.faucamp.simplertmp.io.RtmpConnection.connect(RtmpConnection.java:138) 
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.connect(DefaultRtmpPublisher.java:21) 
        at net.ossrs.rtmp.SrsFlvMuxer.connect(SrsFlvMuxer.java:218) 
        at net.ossrs.rtmp.SrsFlvMuxer.access$100(SrsFlvMuxer.java:48) 
        at net.ossrs.rtmp.SrsFlvMuxer$2.run(SrsFlvMuxer.java:256) 
        at java.lang.Thread.run(Thread.java:919) 


E/RtmpConnection: Shutdown socket
    java.io.IOException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:283)
        at java.net.AbstractPlainSocketImpl.shutdownInput(AbstractPlainSocketImpl.java:622)
        at java.net.Socket.shutdownInput(Socket.java:1570)
        at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:401)
        at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:381)
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:31)
        at net.ossrs.rtmp.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:172)
        at net.ossrs.rtmp.SrsFlvMuxer.access$1000(SrsFlvMuxer.java:48)
        at net.ossrs.rtmp.SrsFlvMuxer$3.run(SrsFlvMuxer.java:319)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: android.system.ErrnoException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at libcore.io.Linux.shutdown(Native Method)
        at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:216)
        at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:216)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:281)
        at java.net.AbstractPlainSocketImpl.shutdownInput(AbstractPlainSocketImpl.java:622) 
        at java.net.Socket.shutdownInput(Socket.java:1570) 
        at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:401) 
        at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:381) 
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:31) 
        at net.ossrs.rtmp.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:172) 
        at net.ossrs.rtmp.SrsFlvMuxer.access$1000(SrsFlvMuxer.java:48) 
        at net.ossrs.rtmp.SrsFlvMuxer$3.run(SrsFlvMuxer.java:319) 
        at java.lang.Thread.run(Thread.java:919) 
2019-10-25 14:59:43.485 768-956/? E/CHIUSECASE: chxadvancedcamerausecase.cpp:4091 FindFeatureToProcessMessage() FindFeatureToProcessMessage pFeature is NULL!
    
    --------- beginning of crash
2019-10-25 14:59:43.487 23265-23691/com.tt E/AndroidRuntime: FATAL EXCEPTION: Thread-8
    Process: com.tt, PID: 23265
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.github.faucamp.simplertmp.io.RtmpSessionInfo.addInvokedCommand(int, java.lang.String)' on a null object reference
        at com.github.faucamp.simplertmp.io.RtmpConnection.sendRtmpPacket(RtmpConnection.java:506)
        at com.github.faucamp.simplertmp.io.RtmpConnection.closeStream(RtmpConnection.java:394)
        at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:379)
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:31)
        at net.ossrs.rtmp.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:172)
        at net.ossrs.rtmp.SrsFlvMuxer.access$1000(SrsFlvMuxer.java:48)
        at net.ossrs.rtmp.SrsFlvMuxer$3.run(SrsFlvMuxer.java:319)
        at java.lang.Thread.run(Thread.java:919)
```

But sometime seem like it's work, when i'm turn off wifi, a below message show and i turn on wifi again and it's reconnect.
```
E/RtmpConnection: Shutdown socket
    java.net.SocketException: Socket is not connected
        at java.net.Socket.shutdownInput(Socket.java:1567)
        at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:401)
        at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:381)
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:31)
        at net.ossrs.rtmp.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:172)
        at net.ossrs.rtmp.SrsFlvMuxer.access$1000(SrsFlvMuxer.java:48)
        at net.ossrs.rtmp.SrsFlvMuxer$3.run(SrsFlvMuxer.java:319)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by beerpcc** [comment]
Seem like it's still occurred. (Same crash message)

**Comment by pedroSG94** [comment]
You are right. This fix only reduced the probability in my device. I'm looking for another way

**Comment by beerpcc** [comment]
Seem like using `rtmpCamera.prepareAudio() && rtmpCamera.prepareVideo()`  help increase probability to success reconnection.

```
override fun onConnectionFailedRtmp(reason: String?) {
        if(rtmpCamera.shouldRetry(reason)){
            if (rtmpCamera.prepareAudio() && rtmpCamera.prepareVideo()) {
                rtmpCamera.startStream(live?.rtmpLiveUrl)
            }
        }
    }
```

**Comment by pedroSG94** [comment]
I was doing multiple test, but in my case this only fail when I dont do retry in main thread.
Can you test with this code?
```java
override fun onConnectionFailedRtmp(reason: String?) {
    runOnUiThread {
      if(rtmpCamera.shouldRetry(reason)){
        if (rtmpCamera.prepareAudio() && rtmpCamera.prepareVideo()) {
          rtmpCamera.reTry(2000)
        }
      }
    }
  }
```

**Comment by beerpcc** [comment]
It's work, thanks
