### ISSUE TITLE
Reconnect does not work properly (or i doing something wrong)

### ISSUE THREAD

**Issue by Radcat501** [pedroSG94/rtmp-rtsp-stream-client-java#447]
Hello! 

I am working on stream stability, because at moment it very unstable, and causes crashes and disconnects. I connect to stream by VLC player for tests. So i find your methods for retry added it in ConnectCheckerRtmp callbacks:

```
override fun onConnectionFailedRtmp(reason: String?) {

        Log.e("TEST", "ON CONNECTION FAILED: $reason")
        try {
            if (rtmpCamera.shouldRetry(reason)) {
                rtmpCamera.reTry(5000)
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
```

But as i see, stream does not reconnect properly, here is a logs of work:

2019-11-09 10:03:09.391 24005-24005 E/TEST: ON SURFACE CREATED
2019-11-09 10:03:09.391 24005-24005 E/TEST: ON SURFACE CHANGED
2019-11-09 10:03:09.639 24005-24005 E/TEST: START STREAM!!!
2019-11-09 10:03:10.741 24005-24280 E/TEST: ON CONNECTION SUCCESS
2019-11-09 10:03:10.742 24005-24280 E/TEST: IS STREAMING? true
2019-11-09 10:03:14.308 24005-24363 E/TEST: ON CONNECTION SUCCESS
2019-11-09 10:03:14.308 24005-24363 E/TEST: IS STREAMING? true
2019-11-09 10:03:15.027 24005-24285 E/TEST: ON CONNECTION FAILED: Error reading packet: Connection reset
2019-11-09 10:03:15.032 24005-24280 E/TEST: ON CONNECTION FAILED: Error send packet: Broken pipe
....
2019-11-09 10:03:15.111 24005-24285 E/TEST: ON CONNECTION FAILED: Error reading packet: Connection reset
2019-11-09 10:03:15.186 24005-24285 E/TEST: ON CONNECTION FAILED: Error reading packet: Connection reset

And then crashes:
2019-11-09 10:03:16.145 24005-24285 E/RtmpConnection: Caught SocketException while reading/decoding packet, shutting down: Connection reset
    
    read: unexpected EOF!

Another scenario is when looks like all normal, but in fact a cant connect to stream with VLC player after reconnection. At start of streaming player shows stream, after reconnect player cant connect, but in logs i see, that stream reconnected:

2019-11-09 10:10:25.706 26093-26093 E/TEST: ON SURFACE CREATED
2019-11-09 10:10:25.706 26093-26093 E/TEST: ON SURFACE CHANGED
2019-11-09 10:10:25.888 26093-26093 E/TEST: START STREAM!!!
2019-11-09 10:10:26.893 26093-26354 E/TEST: ON CONNECTION SUCCESS
2019-11-09 10:10:26.893 26093-26354 E/TEST: IS STREAMING? true
2019-11-09 10:10:30.650 26093-26439 E/TEST: ON CONNECTION SUCCESS
2019-11-09 10:10:30.650 26093-26439 E/TEST: IS STREAMING? true
2019-11-09 10:10:31.864 26093-26354 E/TEST: ON CONNECTION FAILED: Error send packet: Broken pipe
2019-11-09 10:10:37.439 26093-26467 E/TEST: ON CONNECTION SUCCESS
2019-11-09 10:10:37.439 26093-26467 E/TEST: IS STREAMING? true

And the last issue is - when i disconnect wifi on phone, stream cause crash with stack trace:

2019-11-09 10:11:53.670 26093-26708 E/RtmpConnection: Shutdown socket
    java.io.IOException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:267)
        at java.net.AbstractPlainSocketImpl.shutdownInput(AbstractPlainSocketImpl.java:582)
        at java.net.Socket.shutdownInput(Socket.java:1589)
        at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:401)
        at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:381)
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:31)
        at net.ossrs.rtmp.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:172)
        at net.ossrs.rtmp.SrsFlvMuxer.access$1000(SrsFlvMuxer.java:48)
        at net.ossrs.rtmp.SrsFlvMuxer$3.run(SrsFlvMuxer.java:319)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.system.ErrnoException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at libcore.io.Linux.shutdown(Native Method)
        at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:178)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:265)
        at java.net.AbstractPlainSocketImpl.shutdownInput(AbstractPlainSocketImpl.java:582) 
        at java.net.Socket.shutdownInput(Socket.java:1589) 
        at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:401) 
        at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:381) 
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:31) 
        at net.ossrs.rtmp.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:172) 
        at net.ossrs.rtmp.SrsFlvMuxer.access$1000(SrsFlvMuxer.java:48) 
        at net.ossrs.rtmp.SrsFlvMuxer$3.run(SrsFlvMuxer.java:319) 
        at java.lang.Thread.run(Thread.java:764) 

Can you give me some recomendations what i need to do for making more stable and dont crashable streaming? I am already forked your lib for needed modifications.

Thanks!

**Comment by Radcat501** [comment]
And one small, off topic question - I want to rotate stream frames on 90 degrees, but do not rotate preview. I tried to rotate Frames in my FrameListener and in VideoEncoder, but stream wont rotated. Is it possible? Thanks.

**Comment by pedroSG94** [comment]
To fix crash try this:
```java
override fun onConnectionFailedRtmp(reason: String?) {
    runOnUiThread {
      Log.e("TEST", "ON CONNECTION FAILED: $reason")
      if (rtmpCamera.shouldRetry(reason)) {
        rtmpCamera.reTry(5000)
      }
    }
  }
```
About rotate frames, depend of your stream instance.
- With Camrera1 and surfaceview or textureview you can modify rotation here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L411
- Camera1 with openglview or lighopenglview and Camera2 you need modify opengl. This method is called to render preview and stream, you should modify only when stream is renderer:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/ScreenRender.java#L77

**Comment by Radcat501** [comment]
I am added runOnUiThread, but this dont help, still crashes, and stream still unstable. Also still when stream reconnected, VLC player cant connect to it.

About rotation:
I am added this in method draw()
`Matrix.setRotateM(STMatrix, 0, 90, 0, 0, 1.0f);`

And now screen looks like this:
![photo_2019-11-11_10-56-18](https://user-images.githubusercontent.com/11228628/68574225-14cd4080-0472-11ea-8d21-9de8f655dbe2.jpg)

I dont know open gl good enough, so looks like i should add something else?

**Comment by pedroSG94** [comment]
Your logcat seems from this log:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L405
This isn't a crash, only informative log. Your crash should be from other place.
About VLC reconnection. I don't know it is working with ffplay and VLC for me. I will do more test and try reproduce.

In Rotation:
As I tell you this method is called from preview and stream result so you should set a boolean from here to difference the 2 cases:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/ManagerRender.java#L64
Now you should rotate 90 in stream result and rotate to 0 in preview like:
```java
//this last boolean should be created
public void draw(int width, int height, boolean keepAspectRatio, boolean isPreview) {
if (isPreview) {
setRotation(0);
} else {
setRotation(90);
}
}

public void setRotation(int rotation) {
    Matrix.setIdentityM(squareVertexData, 0);
    Matrix.rotateM(squareVertexData, 0, rotation, 0f, 0f, -1f);
    update();
  }
private void update() {
    Matrix.setIdentityM(MVPMatrix, 0);
    Matrix.multiplyMM(MVPMatrix, 0, squareVertexData, 0, MVPMatrix, 0);
  }
```

**Comment by Radcat501** [comment]
Yes, rotation works now as needed, thanks! 

About stream stability i`ll try to call stop stream when disconected and start stream again.

**Comment by Radcat501** [comment]
Looks like i found problem:

```
rtmpCamera = RtmpCamera1(cameraSurface, this)

rtmpCamera.setReTries(reconnectionRetries)
rtmpCamera.reConnect(reconnectionDelay)
```
I am added this lines in camera initialization, and this causes stream falling after it starts.

**Comment by pedroSG94** [comment]
Ok. 
I will modify the library to avoid this problem in the future.

**Comment by Radcat501** [comment]
And i found problem with crash after wifi disabling - you was right, it caused by my http client which dont has error handling, so it crashing without internet. 

Thanks a lot for your help!
