### ISSUE TITLE
Crash on API 19

### ISSUE THREAD

**Issue by ElectronHerder** [pedroSG94/rtmp-rtsp-stream-client-java#449]
Pedro, I have run into a crash situation using the latest version of RTMP Encoder on a Samsung Galaxy S3 that I have been using to test. The app under development has been using your RTMP library for about a year and it has worked. So, perhaps a recent change to the RTMP library has triggered this.

Android Version: 4.4.2

Gradle:
 minSdkVersion 19
 targetSdkVersion 27

 implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:1.7.1'

This line in my code:

rtmpCamera1 = new RtmpCamera1(openGlView, this);

Triggers this crash:

W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x417a0da0)
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.rescueresponder.commtestandroid, PID: 10179
    java.lang.NoClassDefFoundError: com.pedro.encoder.video.VideoEncoder$2
        at com.pedro.encoder.video.VideoEncoder.<init>(VideoEncoder.java:449)
        at com.pedro.rtplibrary.base.Camera1Base.init(Camera1Base.java:107)
        at com.pedro.rtplibrary.base.Camera1Base.<init>(Camera1Base.java:85)
        at com.pedro.rtplibrary.rtmp.RtmpCamera1.<init>(RtmpCamera1.java:39)
        at com.rescueresponder.commtestandroid.AlertOriginatorActivity.onCreate(AlertOriginatorActivity.java:183)
        at android.app.Activity.performCreate(Activity.java:5451)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
        at android.app.ActivityThread.access$900(ActivityThread.java:169)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:146)
        at android.app.ActivityThread.main(ActivityThread.java:5487)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)
I/Process: Sending signal. PID: 10179 SIG: 9
Process 10179 terminated.

Thanks for your time and attention.

**Comment by pedroSG94** [comment]
Fixed:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/24d3130e4aca3cbc39c1a4af464b29c5658731ec

**Comment by ElectronHerder** [comment]
Confirmed good on Android 4.4.2 and a new Pixel with Android 10
