### ISSUE TITLE
Can not start RTSP streaming with exception

### ISSUE THREAD

**Issue by ThangPk** [pedroSG94/rtmp-rtsp-stream-client-java#450]
Hi Pedro, i am trying with demo rtsp link: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
but get exception like below:
2019-11-15 10:07:59.725 1478-2029/com.pedro.rtpstreamer E/MediaCodec: getBufferAndFormat - not executing
2019-11-15 10:07:59.727 1478-2029/com.pedro.rtpstreamer I/VideoEncoder: Encoding error
    java.lang.IllegalStateException
        at android.media.MediaCodec.getBuffer(Native Method)
        at android.media.MediaCodec.getOutputBuffer(MediaCodec.java:3270)
        at com.pedro.encoder.BaseEncoder.outputAvailable(BaseEncoder.java:117)
        at com.pedro.encoder.video.VideoEncoder$2.onOutputBufferAvailable(VideoEncoder.java:464)
        at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1749)
        at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)

2019-11-15 10:07:59.802 1478-2107/com.pedro.rtpstreamer E/RtspClient: connection error
    java.net.SocketException: Socket closed
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:394)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
        at java.net.Socket.connect(Socket.java:621)
        at com.pedro.rtsp.rtsp.RtspClient$1.run(RtspClient.java:147)
        at java.lang.Thread.run(Thread.java:919)

Please help to take a look, thank you.

P/S: Test on emulator.

**Comment by pedroSG94** [comment]
Hello,
First time your logcat is not a crash. It is a symple log wrote by me to debug.
About your fail, this is because you are trying stream to an endpoint that don't support push (it is blocked by wowza company and only support play the stream).

You should use your own media server:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Media-servers-tested
