### ISSUE TITLE
OpenGL rendering on weak phones

### ISSUE THREAD

**Issue by Radcat501** [pedroSG94/rtmp-rtsp-stream-client-java#452]
Hello!

As you may remember, later i made some modifications, with your help, for rotation stream while preview is portrait.

```
public void drawScreen(int width, int height, boolean keepAspectRatio, boolean isPreview) {

    screenRender.draw(width, height, keepAspectRatio);

    if(isPreview) {
      screenRender.setRotation(0);
    }
    else {
      screenRender.setRotation(90);
    }
  }
```

I calling this method in OpenGlView class in method run(), here:
 ```
if (frameAvailable) {
    ...
    managerRender.drawScreen(previewWidth, previewHeight, keepAspectRatio, true);
```

and here:

```
synchronized (sync) {
            ...
            managerRender.drawScreen(encoderWidth, encoderHeight, false, false);
            ...
          }
```

All works fine, but we are noticed, that on some old phones sometimes stream is blinking, possibly because of slow rendering. So sometimes on video we can see rotated stream frames instead preview. Is it possible somehow to hide stream frames and show only preview, but do not wreck stream meanwhile?

Thanks!

**Comment by pedroSG94** [comment]
Theoretically this should work fine in old phones. But you can try with:
1 - Use 2 different matrix rotated to 0 and 90 and change matrix used instead of rotate a matrix in each render. 
2 - If 1st is not working we can modify glsl file to rotate in shader instead of matrix.
After test this. I don't know how to solve it without reproduce your case (unfortunately I haven't old devices with this problem so I hope this work for you)
Let me know if you have problems to implement it.

**Comment by Radcat501** [comment]
Ok, thanks! I'll try and inform you about results later.

**Comment by Radcat501** [comment]
I founded the way how to reproduce this bug on better phones. I am setting two filters:

```
rtmpCamera.glInterface.setFilter(SepiaFilterRender())
val exposureFilterRender = ExposureFilterRender()
exposureFilterRender.exposure = 3.0f
rtmpCamera.glInterface.setFilter(exposureFilterRender)
```

And when rotated matrix is appeared, we can see blinking on stream.

**Comment by Radcat501** [comment]
So, i tried first way. In ScreenRender class a copied matrix squareVertexData:

```
 private final float[] rotatedVertexData = {
          // X, Y, Z, U, V
          -1f, -1f, 0f, 0f, 0f, //bottom left
          1f, -1f, 0f, 1f, 0f, //bottom right
          -1f, 1f, 0f, 0f, 1f, //top left
          1f, 1f, 0f, 1f, 1f, //top right
  };
```

Then in constructor i rotated my new matrix:

```
public ScreenRender() {
    // Prepare rotated matrix
    Matrix.setIdentityM(rotatedVertexData, 0);
    Matrix.rotateM(rotatedVertexData, 0, 90, 0f, 0f, -1f);
    ...
}
```

Then modified rotation code:

```
public void setRotation(int rotation) {
    if(rotation == 90) {
        updateWithMatrix(rotatedVertexData);
    }
    else {
        updateWithMatrix(squareVertexData);
    }
}

private void updateWithMatrix(float[] matrixData) {
      Matrix.setIdentityM(MVPMatrix, 0);
      Matrix.multiplyMM(MVPMatrix, 0, matrixData, 0, MVPMatrix, 0);
}
```

But, unfortunately, looks like blinking does not disappear.

**Comment by Radcat501** [comment]
I was wrong about reproducing bug. So, maybe fix with changing matrix still can work.

**Comment by Radcat501** [comment]
User tested a new version and said - still blinking.

**Comment by pedroSG94** [comment]
Yout matrix implementation look fine. We can try with rotation in shader.
- Delete rotation in with matrix:
```java
if(isPreview) {
      screenRender.setRotation(0);
} else {
      screenRender.setRotation(90);
}
```
- Modify shader to rotate:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/res/raw/fxaa.glsl
To:
```glsl
/*
* http://www.geeks3d.com/20110405/fxaa-fast-approximate-anti-aliasing-demo-glsl-opengl-test-radeon-geforce/3/
*/
precision highp float;

#define FXAA_SPAN_MAX 8.0
#define FXAA_REDUCE_MUL (1.0 / 8.0)
#define FXAA_REDUCE_MIN (1.0 / 256.0)

uniform sampler2D uSampler;
uniform vec2 uResolution;
uniform float uAAEnabled;
uniform float uRotation = 0; //this is the new line

varying vec2 vTextureCoord;

vec4 FxaaTexOff(sampler2D tex, vec2 p, vec2 o, vec2 r){
  return texture2D(tex, p + (o * r));
}
/**
 *
 * @param posPos {@link vec4} Output of FxaaVertexShader interpolated across screen.
 * @param tex {@link sampler2D} The input texture.
 * @param rcpFrame {@link vec2} Constant {1.0/frameWidth, 1.0/frameHeight}.
 */
vec3 FxaaPixelShader(sampler2D tex, vec2 uv, vec2 pos, vec2 rcpFrame) {
/*---------------------------------------------------------*/
    vec3 rgbNW = texture2D(tex, pos).xyz;
    vec3 rgbNE = FxaaTexOff(tex, pos, vec2(1,0), rcpFrame).xyz;
    vec3 rgbSW = FxaaTexOff(tex, pos, vec2(0,1), rcpFrame).xyz;
    vec3 rgbSE = FxaaTexOff(tex, pos, vec2(1,1), rcpFrame).xyz;
    vec3 rgbM  = texture2D(tex, uv).xyz;
/*---------------------------------------------------------*/
    vec3 luma = vec3(0.299, 0.587, 0.114);
    float lumaNW = dot(rgbNW, luma);
    float lumaNE = dot(rgbNE, luma);
    float lumaSW = dot(rgbSW, luma);
    float lumaSE = dot(rgbSE, luma);
    float lumaM  = dot(rgbM,  luma);
/*---------------------------------------------------------*/
    float lumaMin = min(lumaM, min(min(lumaNW, lumaNE), min(lumaSW, lumaSE)));
    float lumaMax = max(lumaM, max(max(lumaNW, lumaNE), max(lumaSW, lumaSE)));
/*---------------------------------------------------------*/
    vec2 dir;
    dir.x = -((lumaNW + lumaNE) - (lumaSW + lumaSE));
    dir.y =  ((lumaNW + lumaSW) - (lumaNE + lumaSE));
/*---------------------------------------------------------*/
    float dirReduce = max((lumaNW + lumaNE + lumaSW + lumaSE) * (0.25 * FXAA_REDUCE_MUL), FXAA_REDUCE_MIN);
    float rcpDirMin = 1.0 / (min(abs(dir.x), abs(dir.y)) + dirReduce);
    dir = min(vec2( FXAA_SPAN_MAX,  FXAA_SPAN_MAX),
          max(vec2(-FXAA_SPAN_MAX, -FXAA_SPAN_MAX),
          dir * rcpDirMin)) * rcpFrame.xy;
/*--------------------------------------------------------*/
    vec3 rgbA = (1.0 / 2.0) * (
        texture2D(tex, uv + dir * (1.0 / 3.0 - 0.5)).xyz +
        texture2D(tex, uv + dir * (2.0 / 3.0 - 0.5)).xyz);
    vec3 rgbB = rgbA * (1.0 / 2.0) + (1.0 / 4.0) * (
        texture2D(tex, uv + dir * (0.0 / 3.0 - 0.5)).xyz +
        texture2D(tex, uv + dir * (3.0 / 3.0 - 0.5)).xyz);
    float lumaB = dot(rgbB, luma);
    if((lumaB < lumaMin) || (lumaB > lumaMax)) {
        return rgbA;
    }
    return rgbB;
}

vec4 PostFX(sampler2D tex, vec2 uv) {
  vec2 rcpFrame = vec2(1.0 / uResolution.x, 1.0 / uResolution.y);
  vec4 c = vec4(0.0);
  vec2 pos = uv - (rcpFrame * (0.5 + FXAA_REDUCE_MUL));
  c.rgb = FxaaPixelShader(tex, uv, pos, rcpFrame);
  c.a = 1.0;
  return c;
}

void main() {
//this is the new line
    vec2 coord = uRrotate == 90.0 ? vec2(vTextureCoord.y, vTextureCoord.x) : vTextureCoord; 
//this was replaced
	gl_FragColor = uAAEnabled == 1.0 ? PostFX(uSampler, coord) : texture2D(uSampler, coord);
}
```
- Add rotation to ScreeenRender:
```java
private int uRotationHandle = -1; //this is the new line

  public void initGl(Context context) {
    GlUtil.checkGlError("initGl start");
    String vertexShader = GlUtil.getStringFromRaw(context, R.raw.simple_vertex);
    String fragmentShader = GlUtil.getStringFromRaw(context, R.raw.fxaa);

    program = GlUtil.createProgram(vertexShader, fragmentShader);
    aPositionHandle = GLES20.glGetAttribLocation(program, "aPosition");
    aTextureHandle = GLES20.glGetAttribLocation(program, "aTextureCoord");
    uMVPMatrixHandle = GLES20.glGetUniformLocation(program, "uMVPMatrix");
    uSTMatrixHandle = GLES20.glGetUniformLocation(program, "uSTMatrix");
    uSamplerHandle = GLES20.glGetUniformLocation(program, "uSampler");
    uResolutionHandle = GLES20.glGetUniformLocation(program, "uResolution");
    uAAEnabledHandle = GLES20.glGetUniformLocation(program, "uAAEnabled");
    uRotationHandle = GLES20.glGetUniformLocation(program, "uRotation"); //this is the new line
    GlUtil.checkGlError("initGl end");
  }

  public void draw(int width, int height, boolean keepAspectRatio, boolean isPreview) {
    GlUtil.checkGlError("drawScreen start");

    PreviewSizeCalculator.calculateViewPort(keepAspectRatio, width, height, streamWidth,
        streamHeight);

    GLES20.glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
    GLES20.glClear(GLES20.GL_DEPTH_BUFFER_BIT | GLES20.GL_COLOR_BUFFER_BIT);

    GLES20.glUseProgram(program);

    squareVertex.position(BaseRenderOffScreen.SQUARE_VERTEX_DATA_POS_OFFSET);
    GLES20.glVertexAttribPointer(aPositionHandle, 3, GLES20.GL_FLOAT, false,
        BaseRenderOffScreen.SQUARE_VERTEX_DATA_STRIDE_BYTES, squareVertex);
    GLES20.glEnableVertexAttribArray(aPositionHandle);

    squareVertex.position(BaseRenderOffScreen.SQUARE_VERTEX_DATA_UV_OFFSET);
    GLES20.glVertexAttribPointer(aTextureHandle, 2, GLES20.GL_FLOAT, false,
        BaseRenderOffScreen.SQUARE_VERTEX_DATA_STRIDE_BYTES, squareVertex);
    GLES20.glEnableVertexAttribArray(aTextureHandle);

    GLES20.glUniformMatrix4fv(uMVPMatrixHandle, 1, false, MVPMatrix, 0);
    GLES20.glUniformMatrix4fv(uSTMatrixHandle, 1, false, STMatrix, 0);
    GLES20.glUniform2f(uResolutionHandle, width, height);
    GLES20.glUniform1f(uAAEnabledHandle, AAEnabled ? 1f : 0f);
    GLES20.glUniform1f(uRotationHandle, isPreview ? 0f : 90f); //this is the new line

    GLES20.glUniform1i(uSamplerHandle, 5);
    GLES20.glActiveTexture(GLES20.GL_TEXTURE5);
    GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, texId);
    //draw
    GLES20.glDrawArrays(GLES20.GL_TRIANGLE_STRIP, 0, 4);

    GlUtil.checkGlError("drawScreen end");
  }
```

**Comment by Radcat501** [comment]
I got error on shader compiling:

```
2019-11-22 13:01:53.875 2985-3258/com.pedro.rtpstreamer E/IMGSRV: :0: DoCompileShader: Failed to compile shader
2019-11-22 13:01:53.875 2985-3258/com.pedro.rtpstreamer E/GlUtil: Could not compile shader 35632:
2019-11-22 13:01:53.875 2985-3258/com.pedro.rtpstreamer E/GlUtil:  Compile failed.
    ERROR: 0:13: 'uniform' : cannot initialize this type of qualifier
    ERROR: 0:13: 'assign' :  cannot convert from 'const int' to 'uniform float'
    ERROR: 0:80: 'uRrotate' : undeclared identifier
    ERROR: 3 compilation errors. No code generated.
2019-11-22 13:01:53.876 2985-3258/com.pedro.rtpstreamer E/GlUtil: initGl end: glError 1281
2019-11-22 13:01:53.877 2985-3258/com.pedro.rtpstreamer E/AndroidRuntime: FATAL EXCEPTION: glThread
    Process: com.pedro.rtpstreamer, PID: 2985
    java.lang.RuntimeException: initGl end: glError 1281
        at com.pedro.encoder.utils.gl.GlUtil.checkGlError(GlUtil.java:127)
        at com.pedro.encoder.input.gl.render.ScreenRender.initGl(ScreenRender.java:89)
        at com.pedro.encoder.input.gl.render.ManagerRender.initGl(ManagerRender.java:56)
        at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:109)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by pedroSG94** [comment]
Ok, Sorry code edited. Copy shader and try

**Comment by Radcat501** [comment]
No problem. I added the code and try it on my stream, but looks like shader work's wrong, the image is noisy and blinking with this and black screen: 

![photo_2019-11-22_14-21-53](https://user-images.githubusercontent.com/11228628/69425726-2812c280-0d34-11ea-8a61-36a5ff67cb86.jpg)

**Comment by pedroSG94** [comment]
This line in the shader was wrong:
```   
 vec2 coord = uRrotate == 90.0 ? vec2(vTextureCoord.y, vTextureCoord.x) : vTextureCoord; 
```
To:
```
   vec2 coord = uRotation == 90.0 ? vec2(vTextureCoord.y, vTextureCoord.x) : vTextureCoord; 
```
I modfied code in my last post, you can copy it.
Remember that you need delete all code related with matrix implementation.

**Comment by Radcat501** [comment]
Thanks, i did all needed fixes and it works. Preview is normal, stream is launching, but stream does not rotated. I tried to modify this strings, choosing different angles:
```
GLES20.glUniform1f(uRotationHandle, isPreview ? 0f : 90f);
...
vec2 coord = uRotation == 90.0 ? vec2(vTextureCoord.y, vTextureCoord.x) : vTextureCoord;
```
But noting happens.

**Comment by pedroSG94** [comment]
Something is not fine because it is working for me. Can you post a copy of your fxaa.glsl and ScreenRender.java files?

**Comment by pedroSG94** [comment]
Here is my copy:
```java
package com.pedro.encoder.input.gl.render;

import android.content.Context;
import android.opengl.GLES20;
import android.opengl.Matrix;
import android.os.Build;
import androidx.annotation.RequiresApi;
import com.pedro.encoder.R;
import com.pedro.encoder.utils.gl.GlUtil;
import com.pedro.encoder.utils.gl.PreviewSizeCalculator;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.FloatBuffer;

/**
 * Created by pedro on 29/01/18.
 */

@RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR2)
public class ScreenRender {

  //rotation matrix
  private final float[] squareVertexData = {
      // X, Y, Z, U, V
      -1f, -1f, 0f, 0f, 0f, //bottom left
      1f, -1f, 0f, 1f, 0f, //bottom right
      -1f, 1f, 0f, 0f, 1f, //top left
      1f, 1f, 0f, 1f, 1f, //top right
  };

  private FloatBuffer squareVertex;

  private float[] MVPMatrix = new float[16];
  private float[] STMatrix = new float[16];
  private boolean AAEnabled = false;  //FXAA enable/disable

  private int texId;

  private int program = -1;
  private int uMVPMatrixHandle = -1;
  private int uSTMatrixHandle = -1;
  private int aPositionHandle = -1;
  private int aTextureHandle = -1;
  private int uSamplerHandle = -1;
  private int uResolutionHandle = -1;
  private int uAAEnabledHandle = -1;

  private int streamWidth;
  private int streamHeight;

  public ScreenRender() {
    squareVertex =
        ByteBuffer.allocateDirect(squareVertexData.length * BaseRenderOffScreen.FLOAT_SIZE_BYTES)
            .order(ByteOrder.nativeOrder())
            .asFloatBuffer();
    squareVertex.put(squareVertexData).position(0);
    Matrix.setIdentityM(MVPMatrix, 0);
    Matrix.setIdentityM(STMatrix, 0);
  }

  private int uRotationHandle = -1; //this is the new line

  public void initGl(Context context) {
    GlUtil.checkGlError("initGl start");
    String vertexShader = GlUtil.getStringFromRaw(context, R.raw.simple_vertex);
    String fragmentShader = GlUtil.getStringFromRaw(context, R.raw.fxaa);

    program = GlUtil.createProgram(vertexShader, fragmentShader);
    aPositionHandle = GLES20.glGetAttribLocation(program, "aPosition");
    aTextureHandle = GLES20.glGetAttribLocation(program, "aTextureCoord");
    uMVPMatrixHandle = GLES20.glGetUniformLocation(program, "uMVPMatrix");
    uSTMatrixHandle = GLES20.glGetUniformLocation(program, "uSTMatrix");
    uSamplerHandle = GLES20.glGetUniformLocation(program, "uSampler");
    uResolutionHandle = GLES20.glGetUniformLocation(program, "uResolution");
    uAAEnabledHandle = GLES20.glGetUniformLocation(program, "uAAEnabled");
    uRotationHandle = GLES20.glGetUniformLocation(program, "uRotation"); //this is the new line
    GlUtil.checkGlError("initGl end");
  }

  public void draw(int width, int height, boolean keepAspectRatio, boolean isPreview) {
    GlUtil.checkGlError("drawScreen start");

    PreviewSizeCalculator.calculateViewPort(keepAspectRatio, width, height, streamWidth,
        streamHeight);

    GLES20.glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
    GLES20.glClear(GLES20.GL_DEPTH_BUFFER_BIT | GLES20.GL_COLOR_BUFFER_BIT);

    GLES20.glUseProgram(program);

    squareVertex.position(BaseRenderOffScreen.SQUARE_VERTEX_DATA_POS_OFFSET);
    GLES20.glVertexAttribPointer(aPositionHandle, 3, GLES20.GL_FLOAT, false,
        BaseRenderOffScreen.SQUARE_VERTEX_DATA_STRIDE_BYTES, squareVertex);
    GLES20.glEnableVertexAttribArray(aPositionHandle);

    squareVertex.position(BaseRenderOffScreen.SQUARE_VERTEX_DATA_UV_OFFSET);
    GLES20.glVertexAttribPointer(aTextureHandle, 2, GLES20.GL_FLOAT, false,
        BaseRenderOffScreen.SQUARE_VERTEX_DATA_STRIDE_BYTES, squareVertex);
    GLES20.glEnableVertexAttribArray(aTextureHandle);

    GLES20.glUniformMatrix4fv(uMVPMatrixHandle, 1, false, MVPMatrix, 0);
    GLES20.glUniformMatrix4fv(uSTMatrixHandle, 1, false, STMatrix, 0);
    GLES20.glUniform2f(uResolutionHandle, width, height);
    GLES20.glUniform1f(uAAEnabledHandle, AAEnabled ? 1f : 0f);
    GLES20.glUniform1f(uRotationHandle, isPreview ? 90f : 0f); //this is the new line

    GLES20.glUniform1i(uSamplerHandle, 5);
    GLES20.glActiveTexture(GLES20.GL_TEXTURE5);
    GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, texId);
    //draw
    GLES20.glDrawArrays(GLES20.GL_TRIANGLE_STRIP, 0, 4);

    GlUtil.checkGlError("drawScreen end");
  }

  public void release() {
    GLES20.glDeleteProgram(program);
  }

  public void setTexId(int texId) {
    this.texId = texId;
  }

  public void setAAEnabled(boolean AAEnabled) {
    this.AAEnabled = AAEnabled;
  }

  public boolean isAAEnabled() {
    return AAEnabled;
  }

  public void setStreamSize(int streamWidth, int streamHeight) {
    this.streamWidth = streamWidth;
    this.streamHeight = streamHeight;
  }
}

```
```glsl
/*
* http://www.geeks3d.com/20110405/fxaa-fast-approximate-anti-aliasing-demo-glsl-opengl-test-radeon-geforce/3/
*/
precision highp float;

#define FXAA_SPAN_MAX 8.0
#define FXAA_REDUCE_MUL (1.0 / 8.0)
#define FXAA_REDUCE_MIN (1.0 / 256.0)

uniform sampler2D uSampler;
uniform vec2 uResolution;
uniform float uAAEnabled;
uniform float uRotation; //this is the new line

varying vec2 vTextureCoord;

vec4 FxaaTexOff(sampler2D tex, vec2 p, vec2 o, vec2 r){
    return texture2D(tex, p + (o * r));
}
/**
 *
 * @param posPos {@link vec4} Output of FxaaVertexShader interpolated across screen.
 * @param tex {@link sampler2D} The input texture.
 * @param rcpFrame {@link vec2} Constant {1.0/frameWidth, 1.0/frameHeight}.
 */
vec3 FxaaPixelShader(sampler2D tex, vec2 uv, vec2 pos, vec2 rcpFrame) {
    /*---------------------------------------------------------*/
    vec3 rgbNW = texture2D(tex, pos).xyz;
    vec3 rgbNE = FxaaTexOff(tex, pos, vec2(1,0), rcpFrame).xyz;
    vec3 rgbSW = FxaaTexOff(tex, pos, vec2(0,1), rcpFrame).xyz;
    vec3 rgbSE = FxaaTexOff(tex, pos, vec2(1,1), rcpFrame).xyz;
    vec3 rgbM  = texture2D(tex, uv).xyz;
    /*---------------------------------------------------------*/
    vec3 luma = vec3(0.299, 0.587, 0.114);
    float lumaNW = dot(rgbNW, luma);
    float lumaNE = dot(rgbNE, luma);
    float lumaSW = dot(rgbSW, luma);
    float lumaSE = dot(rgbSE, luma);
    float lumaM  = dot(rgbM,  luma);
    /*---------------------------------------------------------*/
    float lumaMin = min(lumaM, min(min(lumaNW, lumaNE), min(lumaSW, lumaSE)));
    float lumaMax = max(lumaM, max(max(lumaNW, lumaNE), max(lumaSW, lumaSE)));
    /*---------------------------------------------------------*/
    vec2 dir;
    dir.x = -((lumaNW + lumaNE) - (lumaSW + lumaSE));
    dir.y =  ((lumaNW + lumaSW) - (lumaNE + lumaSE));
    /*---------------------------------------------------------*/
    float dirReduce = max((lumaNW + lumaNE + lumaSW + lumaSE) * (0.25 * FXAA_REDUCE_MUL), FXAA_REDUCE_MIN);
    float rcpDirMin = 1.0 / (min(abs(dir.x), abs(dir.y)) + dirReduce);
    dir = min(vec2( FXAA_SPAN_MAX,  FXAA_SPAN_MAX),
    max(vec2(-FXAA_SPAN_MAX, -FXAA_SPAN_MAX),
    dir * rcpDirMin)) * rcpFrame.xy;
    /*--------------------------------------------------------*/
    vec3 rgbA = (1.0 / 2.0) * (
    texture2D(tex, uv + dir * (1.0 / 3.0 - 0.5)).xyz +
    texture2D(tex, uv + dir * (2.0 / 3.0 - 0.5)).xyz);
    vec3 rgbB = rgbA * (1.0 / 2.0) + (1.0 / 4.0) * (
    texture2D(tex, uv + dir * (0.0 / 3.0 - 0.5)).xyz +
    texture2D(tex, uv + dir * (3.0 / 3.0 - 0.5)).xyz);
    float lumaB = dot(rgbB, luma);
    if((lumaB < lumaMin) || (lumaB > lumaMax)) {
        return rgbA;
    }
    return rgbB;
}

vec4 PostFX(sampler2D tex, vec2 uv) {
    vec2 rcpFrame = vec2(1.0 / uResolution.x, 1.0 / uResolution.y);
    vec4 c = vec4(0.0);
    vec2 pos = uv - (rcpFrame * (0.5 + FXAA_REDUCE_MUL));
    c.rgb = FxaaPixelShader(tex, uv, pos, rcpFrame);
    c.a = 1.0;
    return c;
}

void main() {
    //this is the new line
    vec2 coord = uRotation == 90.0 ? vec2(vTextureCoord.y, vTextureCoord.x) : vTextureCoord;
    //this was replaced
    gl_FragColor = uAAEnabled == 1.0 ? PostFX(uSampler, coord) : texture2D(uSampler, coord);
}
```

**Comment by Radcat501** [comment]
I fully copied yours code and still the same. Maybe problem in this four strings:
// OpenGlView.java
managerRender.drawScreen(previewWidth, previewHeight, keepAspectRatio, true); // is Preview
managerRender.drawScreen(encoderWidth, encoderHeight, false, false); // Not preview

// OffScreenGlThread
textureManager.drawScreen(encoderWidth, encoderHeight, false, true);
textureManager.drawScreen(encoderWidth, encoderHeight, false, true);

**Comment by Radcat501** [comment]
I can make commit and push my fork of your project, so you can see differences with yours version.

**Comment by pedroSG94** [comment]
I did a clone of your fork and this is working in my samsung S7. :(
Also I detected that you did rotate after draw in ManagerRender. Try do it before draw.

**Comment by Radcat501** [comment]
Can you try to connect on stream with VLC player? I tried and VLC shows that picture does not rotated.

> Also I detected that you did rotate after draw in ManagerRender. Try do it before draw.
You mean old rotation version?

```
  screenRender.draw(width, height, keepAspectRatio, isPreview);

//    if(isPreview) {
//      screenRender.setRotation(0);
//    }
//    else {
//      screenRender.setRotation(90);
//    }
```

**Comment by pedroSG94** [comment]
Yes

**Comment by Radcat501** [comment]
Looks like it helped! Rotating before drawing removed the blinking. Thanks a lot!
