### ISSUE TITLE
    android.hardware.camera2.CameraAccessException: CAMERA_DISABLED (1): Camera disabled by policy

### ISSUE THREAD

**Issue by medozeus** [pedroSG94/rtmp-rtsp-stream-client-java#456]
I got this error while try to use api2 for open front camera .. back camera work but when switch to front camera got error 
```
android.hardware.camera2.CameraAccessException: CAMERA_DISABLED (1): Camera disabled by policy
        at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:815)
        at android.hardware.camera2.CameraManager.openCameraDeviceUserAsync(CameraManager.java:449)
        at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:624)
        at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:543)
        at com.pedro.encoder.input.video.Camera2ApiManager.openCameraId(Camera2ApiManager.java:378)
        at com.pedro.encoder.input.video.Camera2ApiManager.openCameraFacing(Camera2ApiManager.java:246)
        at com.pedro.rtplibrary.base.Camera2Base.startPreview(Camera2Base.java:310)
        at com.pedro.rtplibrary.base.Camera2Base.startPreview(Camera2Base.java:324)
        at com.pedro.rtplibrary.base.Camera2Base.startPreview(Camera2Base.java:329)
        at com.mmmm.myApp.camera.CameraPreview.surfaceChanged(CameraPreview.java:123)
        at android.view.SurfaceView.updateSurface(SurfaceView.java:816)
        at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:187)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:991)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3038)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1911)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8526)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7078)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
     Caused by: android.os.ServiceSpecificException: Camera disabled by policy (code 6)
        at android.hardware.camera2.legacy.LegacyExceptionUtils.throwOnServiceError(LegacyExceptionUtils.java:132)
        at android.hardware.camera2.legacy.CameraDeviceUserShim.connectBinderShim(CameraDeviceUserShim.java:378)
        at android.hardware.camera2.CameraManager.openCameraDeviceUserAsync(CameraManager.java:430)
        at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:624) 
        at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:543) 
        at com.pedro.encoder.input.video.Camera2ApiManager.openCameraId(Camera2ApiManager.java:378) 
        at com.pedro.encoder.input.video.Camera2ApiManager.openCameraFacing(Camera2ApiManager.java:246) 
        at com.pedro.rtplibrary.base.Camera2Base.startPreview(Camera2Base.java:310) 
        at com.pedro.rtplibrary.base.Camera2Base.startPreview(Camera2Base.java:324) 
        at com.pedro.rtplibrary.base.Camera2Base.startPreview(Camera2Base.java:329) 
        at com.mmm.myApp.camera.CameraPreview.surfaceChanged(CameraPreview.java:123) 
        at android.view.SurfaceView.updateSurface(SurfaceView.java:816) 
        at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:187) 
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:991) 
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3038) 
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1911) 
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8526) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:761) 
        at android.view.Choreographer.doFrame(Choreographer.java:696) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7078) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974) 
```

**Comment by medozeus** [comment]
android version 9

**Comment by pedroSG94** [comment]
This seems that your device has an app with device owner and that app blocked your camera. Make sure that ou are using a official ROM without device owner apps.

**Comment by medozeus** [comment]
I am using the official ROM and its version 9

**Comment by medozeus** [comment]
might there is some security on the last android version or Samsung software update

**Comment by pedroSG94** [comment]
I think this is not related with Android 9 or Samsung software because I tested with a Samsung A50 with Android 9 and all is working fine at least with this device.
This is the official documentation about your error:
https://developer.android.com/reference/kotlin/android/hardware/camera2/CameraAccessException#CAMERA_DISABLED:kotlin.Int
I recommend you flash your device with official ROM from Samsung official web and retry:
https://www.sammobile.com/firmwares/
Or if you are 100% sure that you have an official ROM you can do a factory reset to delete device policy.
Also try open your preview directly with your front camera to discard switch library bug:
```java
rtmpCamera2.startPreview(CameraHelper.Facing.FRONT);
```
