### ISSUE TITLE
java.net.SocketException: Software caused connection abort

### ISSUE THREAD

**Issue by BrickWorkerKing** [pedroSG94/rtmp-rtsp-stream-client-java#464]
This error occurs when performing a 15-minute RTSP push stream operation on Android 7.0.

error log:

E: send error: 
    java.net.SocketException: Software caused connection abort
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:112)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
        at com.pedro.rtsp.rtp.sockets.RtpSocketTcp.sendFrameTCP(RtpSocketTcp.java:43)
        at com.pedro.rtsp.rtp.sockets.RtpSocketTcp.sendFrame(RtpSocketTcp.java:28)
        at com.pedro.rtsp.rtsp.RtspSender$1.run(RtspSender.java:123)
        at java.lang.Thread.run(Thread.java:761)

E: disconnect error
    java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:112)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.BufferedWriter.flush(BufferedWriter.java:254)
        at com.pedro.rtsp.rtsp.RtspClient$2.run(RtspClient.java:239)
        at java.lang.Thread.run(Thread.java:761)

**Comment by pedroSG94** [comment]
Are you doing RTSPS?
Maybe your problem is related with this (first answer):
https://stackoverflow.com/questions/12986542/how-to-solve-connection-reset-by-peer-socket-write-error
Try disable renegotiation in the server and enable in device:
```java
//call it in onCreate before use the library
System.setProperty("sun.security.ssl.allowUnsafeRenegotiation", "true");
```
