### ISSUE TITLE
SrsFlvMuxer NullPointerException crash on stop

### ISSUE THREAD

**Issue by alexeyvasilyev** [pedroSG94/rtmp-rtsp-stream-client-java#500]
Getting constant crashes when calling srsFlvMuxer.stop() command.

```
2020-02-19 10:50:28.226 4227-4348/com.package I/SrsFlvMuxer: SrsFlvMuxer closed
2020-02-19 10:50:28.227 4227-4348/com.package I/AudioEncoder: stopped
2020-02-19 10:50:28.227 4227-4451/com.packageD/RtmpConnection: closeStream(): setting current stream ID to 0
2020-02-19 10:50:28.228 4227-4451/com.package D/RtmpConnection: wrote packet: RTMP Command (command: closeStream, transaction ID: 0), size: 24
2020-02-19 10:50:28.231 4227-4381/com.package E/AndroidRuntime: FATAL EXCEPTION: Thread-28
    Process: com.package, PID: 4227
    java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Thread.interrupt()' on a null object reference
        at net.ossrs.rtmp.SrsFlvMuxer$2.run(SrsFlvMuxer.java:294)
        at java.lang.Thread.run(Thread.java:919)
```

Fix is instead of
```
          } catch (InterruptedException e) {
            worker.interrupt();
          }
```

make 

```
          } catch (InterruptedException e) {
            Thread t = worker;
            if (t != null)
              t.interrupt();
          }
```

**Comment by pedroSG94** [comment]
Fixed: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/eb869088ecbfcf10d97588181b6da6e5d2349840
