### ISSUE TITLE
Error initializing audio record when a UVC camera is connected.

### ISSUE THREAD

**Issue by ulohani90** [pedroSG94/rtmp-rtsp-stream-client-java#505]
Hi, I am streaming the screen display using this library. Plus I added a USB camera stream in a SurfaceFilterRender as you suggested in a different issue. 

Now I am facing an issue on certain devices(For eg -  Samsung Galaxy M30S, Android version 9). When my usb camera is connected to the phone, the app crashes and gives the following error.

`com.android.teststudio E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.teststudio, PID: 32425
    java.lang.RuntimeException: Unable to start service com.android.teststudio.services.DisplayService@de98f97 with Intent { cmp=com.android.teststudio/.services.DisplayService (has extras) }: java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3958)
        at android.app.ActivityThread.access$1800(ActivityThread.java:248)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1861)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7285)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
     Caused by: java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
        at android.media.AudioRecord.startRecording(AudioRecord.java:992)
        at com.pedro.encoder.input.audio.MicrophoneManager.init(MicrophoneManager.java:141)
        at com.pedro.encoder.input.audio.MicrophoneManager.start(MicrophoneManager.java:120)
        at com.pedro.rtplibrary.base.DisplayBase.startEncoders(DisplayBase.java:293)
        at com.pedro.rtplibrary.base.DisplayBase.startStream(DisplayBase.java:268)
        at com.android.teststudio.services.DisplayService.startStreamRtp(DisplayService.kt:316)
        at com.android.teststudio.services.DisplayService.onStartCommand(DisplayService.kt:83)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3939)
        at android.app.ActivityThread.access$1800(ActivityThread.java:248) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1861) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7285) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975) `

Also I checked logs for any error while initialising the audio record, I found the following error. Stackoverflow reported permission can be an issue but in my case its not. 

`2020-02-24 20:35:28.227 32425-32425/com.android.rheostudio E/IAudioFlinger: createRecord returned error -22
2020-02-24 20:35:28.227 32425-32425/com.android.rheostudio E/AudioRecord: AudioFlinger could not create record track, status: -22
2020-02-24 20:35:28.227 32425-32425/com.android.rheostudio E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
2020-02-24 20:35:28.230 32425-32425/com.android.rheostudio E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.`

What could be the problem and any idea how can this be fixed? Any help would be appreciated!

**Comment by pedroSG94** [comment]
If you haven't problems without camera USB using the same code and same device, maybe your camera block microphone for some reason.
You log is the same that if you try open a microphone in use. Try connect camera and open other app to record audio to discard this problem.
