### ISSUE TITLE
Default RTSP connection issue..Please help...!

### ISSUE THREAD

**Issue by ankitda30** [pedroSG94/rtmp-rtsp-stream-client-java#510]
I'm beginner in development.
I'm not able to establish Default RTSP connection. 
I have tried other rtsp demos they given auto generated rtsp url but here we have to add rtsp url.
I tried as rtsp://ip:port/live/app but still not able to connect...
I'm not able to understand what to put after adding port number and what should be the stream for running Default RTSP demo... 

below is my log....
Please help......

=============================================================
java.lang.IllegalStateException: buffer is inaccessible
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:287)
        at com.pedro.encoder.BaseEncoder.processInput(BaseEncoder.java:73)
        at com.pedro.encoder.BaseEncoder.inputAvailable(BaseEncoder.java:112)
        at com.pedro.encoder.video.VideoEncoder$2.onInputBufferAvailable(VideoEncoder.java:478)
        at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1738)
        at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2020-03-06 11:43:22.946 14224-14635/com.pedro.rtpstreamer E/RtspClient: connection error
    java.net.ConnectException: failed to connect to /192.168.0.92 (port 8080) from /192.168.0.92 (port 38591) after 5000ms: isConnected failed: ECONNREFUSED (Connection refused)
        at libcore.io.IoBridge.isConnected(IoBridge.java:288)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:193)
        at libcore.io.IoBridge.connect(IoBridge.java:135)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
        at java.net.Socket.connect(Socket.java:621)
        at com.pedro.rtsp.rtsp.RtspClient$1.run(RtspClient.java:147)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)

**Comment by pedroSG94** [comment]
As you can see in error. Your server refuse connection, it means that your configuration is not working fine. You should test it with ffmpeg to discard an error in my library and after check all is working, try with my library.

What server are you using?

**Comment by ankitda30** [comment]
Hi PerdroSG94,
Thank you for the reply...
Actually I thought it's a rtsp server application and my mobile phone should act like rtsp server but I was wrong, It's a rtsp client application and we need to setup separate rtsp server like Wowza...
Finally I'm able to run the application after setting Wowza server on my PC successfully.
One final request is please make a manual about connectivity of application using RTSP/RTMP server.
