### ISSUE TITLE
GL error

### ISSUE THREAD

**Issue by mynew-github-account** [pedroSG94/rtmp-rtsp-stream-client-java#570]
Fatal Exception: java.lang.RuntimeException: eglCreateWindowSurface: EGL error: 0x3003
at com.pedro.encoder.utils.gl.GlUtil.checkEglError(GlUtil.java:134)
at com.pedro.encoder.input.gl.SurfaceManager.eglSetup(SurfaceManager.java:132)
at com.pedro.encoder.input.gl.SurfaceManager.(SurfaceManager.java:47)
at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:117)
at java.lang.Thread.run(Thread.java:929)

I know issue but #238 and #150 
But still can't solve an issue 

Brand: HUAWEI
Model: Honor 8x
RAM free: 932.21 MB
Disk free: 848.87 MB
Operating System
Version: 10
Orientation: Portrait

**Comment by pedroSG94** [comment]
Are you testing in app example?
Can you share a code and steps to reproduce this error?
