### ISSUE TITLE
Failed to connect to microsoft azure live event.

### ISSUE THREAD

**Issue by kamiljeglikowski** [pedroSG94/rtmp-rtsp-stream-client-java#588]
Hey i have problem with sending any data to azure microsoft.

I am using rtmp and rtmps (not rtsp)
item url looks like this 
`rtmp://myItemName.channel.media.azure.net:1935/live/authTokenHere`
and 
`rtmps://myItemName.channel.media.azure.net:2935/live/authTokenHere`

Error info when I am trying to connect to rtmp:
"Fail to connect, time out"

Error info when I am trying connect to rtmps: 
"failed to connect to myitemName.channel.media.azure.net/51.124.87.202 (port 2935) from /:: (port 46058): connect failed: ETIMEDOUT (Connection timed out)"
Error stacktrace:
`2020-06-01 21:57:13.270 19911-20118/com.pedro.rtpstreamer E/CreateSSLSocket: Error
    java.net.ConnectException: failed to connect to myItemName.channel.media.azure.net/51.124.87.202 (port 2935) from /:: (port 46052): connect failed: ETIMEDOUT (Connection timed out)
        at libcore.io.IoBridge.connect(IoBridge.java:138)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:357)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:201)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:183)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:357)
        at java.net.Socket.connect(Socket.java:616)
        at com.android.org.conscrypt.AbstractConscryptSocket.connect(AbstractConscryptSocket.java:155)
        at com.android.org.conscrypt.AbstractConscryptSocket.connect(AbstractConscryptSocket.java:139)
        at java.net.Socket.<init>(Socket.java:445)
        at java.net.Socket.<init>(Socket.java:217)
        at javax.net.ssl.SSLSocket.<init>(SSLSocket.java:904)
        at com.android.org.conscrypt.AbstractConscryptSocket.<init>(AbstractConscryptSocket.java:96)
        at com.android.org.conscrypt.OpenSSLSocketImpl.<init>(OpenSSLSocketImpl.java:40)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.<init>(ConscryptFileDescriptorSocket.java:118)
        at com.android.org.conscrypt.OpenSSLSocketFactoryImpl.createSocket(OpenSSLSocketFactoryImpl.java:106)
        at net.ossrs.rtmp.TLSSocketFactory.createSocket(TLSSocketFactory.java:50)
        at net.ossrs.rtmp.CreateSSLSocket.createSSlSocket(CreateSSLSocket.java:25)
        at com.github.faucamp.simplertmp.io.RtmpConnection.connect(RtmpConnection.java:139)
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.connect(DefaultRtmpPublisher.java:21)
        at net.ossrs.rtmp.SrsFlvMuxer.connect(SrsFlvMuxer.java:237)
        at net.ossrs.rtmp.SrsFlvMuxer.access$100(SrsFlvMuxer.java:53)
        at net.ossrs.rtmp.SrsFlvMuxer$2.run(SrsFlvMuxer.java:275)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: android.system.ErrnoException: connect failed: ETIMEDOUT (Connection timed out)
        at libcore.io.Linux.connect(Native Method)
        at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:126)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:152)
        at libcore.io.IoBridge.connect(IoBridge.java:130)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129) 
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:357) 
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:201) 
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:183) 
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:357) 
        at java.net.Socket.connect(Socket.java:616) 
        at com.android.org.conscrypt.AbstractConscryptSocket.connect(AbstractConscryptSocket.java:155) 
        at com.android.org.conscrypt.AbstractConscryptSocket.connect(AbstractConscryptSocket.java:139) 
        at java.net.Socket.<init>(Socket.java:445) 
        at java.net.Socket.<init>(Socket.java:217) 
        at javax.net.ssl.SSLSocket.<init>(SSLSocket.java:904) 
        at com.android.org.conscrypt.AbstractConscryptSocket.<init>(AbstractConscryptSocket.java:96) 
        at com.android.org.conscrypt.OpenSSLSocketImpl.<init>(OpenSSLSocketImpl.java:40) 
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.<init>(ConscryptFileDescriptorSocket.java:118) 
        at com.android.org.conscrypt.OpenSSLSocketFactoryImpl.createSocket(OpenSSLSocketFactoryImpl.java:106) 
        at net.ossrs.rtmp.TLSSocketFactory.createSocket(TLSSocketFactory.java:50) 
        at net.ossrs.rtmp.CreateSSLSocket.createSSlSocket(CreateSSLSocket.java:25) 
        at com.github.faucamp.simplertmp.io.RtmpConnection.connect(RtmpConnection.java:139) 
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.connect(DefaultRtmpPublisher.java:21) 
        at net.ossrs.rtmp.SrsFlvMuxer.connect(SrsFlvMuxer.java:237) 
        at net.ossrs.rtmp.SrsFlvMuxer.access$100(SrsFlvMuxer.java:53) 
        at net.ossrs.rtmp.SrsFlvMuxer$2.run(SrsFlvMuxer.java:275) 
        at java.lang.Thread.run(Thread.java:784) 
2020-06-01 21:57:13.271 19911-20118/com.pedro.rtpstreamer E/RtmpConnection: Error
    java.io.IOException: Socket creation failed
        at com.github.faucamp.simplertmp.io.RtmpConnection.connect(RtmpConnection.java:140)
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.connect(DefaultRtmpPublisher.java:21)
        at net.ossrs.rtmp.SrsFlvMuxer.connect(SrsFlvMuxer.java:237)
        at net.ossrs.rtmp.SrsFlvMuxer.access$100(SrsFlvMuxer.java:53)
        at net.ossrs.rtmp.SrsFlvMuxer$2.run(SrsFlvMuxer.java:275)
        at java.lang.Thread.run(Thread.java:784)`

And also there is is console information about dropped frames.

Do you have any idea how to solve that?

**Comment by pedroSG94** [comment]
I only can see timeout from server.
Make sure that you have access to server in that network (check 1935 and 2935 ports are open).
Try use ffmpeg in your PC with the same network that your device to discard library errors (an easy program that use ffmpeg is OBS)

**Comment by kamiljeglikowski** [comment]
I am able to stream via OBS to azure without any problem. 
I am using the same network on PC and in your library demos.

**Comment by pedroSG94** [comment]
Do you have any way to provide me an endpoint to test it? You can send me info with email if you want. pedrossgg1994@gmail.com

**Comment by kamiljeglikowski** [comment]
@pedroSG94 Hi I can't give you access for some days. I can only give you it for a fe hours. Can we catch on some communicator such as messenger, hangouts or others?
In which timezone you are?

**Comment by pedroSG94** [comment]
My timezone is GMT+2.
You can contact with my using gmail/hangouts if you want in realtime. Send my an email and we can accord the hour to provide my access.

**Comment by kamiljeglikowski** [comment]
@pedroSG94 I have sent you a message on hangout from kamil.jeglikowsi@gmail.com

**Comment by pedroSG94** [comment]
I haven't receive any message. I sent you an invite and an email but for some reason I got an error when I do it.
![Screenshot_20200614-014709](https://user-images.githubusercontent.com/17556876/84581435-00bf3800-ade1-11ea-8117-25396145287b.jpg)

**Comment by kamiljeglikowski** [comment]
omg, sorry there is a typo in my e-mail... There is correct one kamil.jeglikowski@gmail.com
