### ISSUE TITLE
NetworkOnMainThreadException 

### ISSUE THREAD

**Issue by quadri** [pedroSG94/rtmp-rtsp-stream-client-java#6]
Hello,  
Android 4.1.1 

android.os.NetworkOnMainThreadException
                                                                          at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1117)
                                                                          at java.net.InetAddress.lookupHostByName(InetAddress.java:385)
                                                                          at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
                                                                          at java.net.InetAddress.getByName(InetAddress.java:289)
                                                                          at com.pedro.rtsp.rtp.sockets.RtpSocketUdp.setDestination(RtpSocketUdp.java:67)
                                                                          at com.pedro.rtsp.rtp.packets.AccPacket.updateDestinationAudio(AccPacket.java:28)
                                                                          at com.pedro.rtmpstreamer.builders.RtspBuilder.updateDestination(RtspBuilder.java:209)
                                                                          at com.pedro.rtmpstreamer.ui.customexample.RtspActivity$2.run(RtspActivity.java:274)
                                                                          at android.os.Handler.handleCallback(Handler.java:615)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                          at android.os.Looper.loop(Looper.java:137)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:4812)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:511)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by pedroSG94** [comment]
That crash is because you are doing network work in main thread and you need do it in other thread.
Is line in builder?:
accPacket.updateDestinationAudio();

Try create thread in that method. Anyway i will update rtsp updatedestinationport method today

**Comment by quadri** [comment]
Yes, I understand problem. Just wanted to report bug.
I have changed RtspActivity.onConnectionSuccessRtsp, moving  rtspBuilder.updateDestination(); from runOnUiThread: 
```
@Override
  public void onConnectionSuccessRtsp() {
    runOnUiThread(new Runnable() {
      @Override
      public void run() {
        Toast.makeText(RtspActivity.this, "Connection success", Toast.LENGTH_SHORT).show();
      }
    });
    rtspBuilder.updateDestination();  //only for rtsp
  }
```
And let me give small advice about: maybe updateDestinations() must be called by RtspBuilder itself, not in activity user code?

**Comment by pedroSG94** [comment]
Yes, i will use acc and h264 packets in rtspclient. I will develop it today
