### ISSUE TITLE
Stream both front and back camera at the same time

### ISSUE THREAD

**Issue by Marcello09** [pedroSG94/rtmp-rtsp-stream-client-java#612]
Hi, i'd like to stream and preview both front facing camera and back camera at the same time. 

I've tried to implement two RtmpCamera2 instances and set their view to two different OpenGlView. But I'm having issues, one  of the preview shows correctly, and the other don't. How can I do it?

**Comment by pedroSG94** [comment]
The best way is use [SurfaceFilter](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L260).
Instead of Render that surface with MediaPlayer you can use [CameraApiManager](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/encoder/src/main/java/com/pedro/encoder/input/video) to render it.

Normally, you can't open both cameras at same time so this could fail in multiple devices.

**Comment by tareqalbeesh** [comment]
I did it but you need to edit the library to be able to do that, but you should keep in mind that not  all devices support opening two cameras at the same time

**Comment by Marcello09** [comment]
@tareqalbeesh what editions you made? I've already had to edit the library once to keep the screen at the rotation I wanted, so there is no problem doing it again

**Comment by tareqalbeesh** [comment]
you just need to make the camera2Base able to start streaming using a specific Camera, you should do the same for the startPreview,
I did it using two Services, each service able you to stream from a different camera.

**Comment by haseeb362-amoxt** [comment]
@tareqalbeesh Please can you share the code, we are in trouble and working to resolve it for past couple of days.

Regards.

**Comment by haseeb362-amoxt** [comment]
@pedroSG94 Thank you for the amazing library
I have a slight problem I think you can solve it
When using OpenGL example from your repo with Surface Filter The bunny video plays for 3-4 seconds and stops
Similar thing happens when I use the second cam, the front camera plays for some second and then stops the stream

**Comment by haseeb362-amoxt** [comment]
> @pedroSG94 Thank you for the amazing library
> I have a slight problem I think you can solve it
> When using OpenGL example from your repo with Surface Filter The bunny video plays for 3-4 seconds and stops
> A similar thing happens when I use the second cam, the front camera plays for some seconds and then stops the stream.
> 
> The bunny video and back camera both plays smoothly when stream is off, but as soon as I start stream they stop after some time.
> 
> Following is my simple code
> 
> ```
> SurfaceFilterRender surfaceFilterRender =
>               new SurfaceFilterRender(new SurfaceFilterRender.SurfaceReadyCallback() {
>                 @Override
>                 public void surfaceReady(SurfaceTexture surfaceTexture) {
>                   try {
>                     Camera mSecondaryCamera = getCameraInstance(1);
>                     mSecondaryCamera.setPreviewTexture(surfaceTexture);
>                     mSecondaryCamera.startPreview();
>                   } catch (IOException e) {
>                     e.printStackTrace();
>                   }
> 
>                 }
>               });
> ```
> 
> Please help as soon as you can, I would pay/donate in return. Thanks again for the amazing lib.

Okay update on this

SurfaceFilterRender stops the mediaPlayer video after about 15-20 seconds when not recording, and stops it 2-3 seconds when streaming
I think its not an issue with the streaming side of the library
It's related to the GL side of the SurfaceFilterRender

**Comment by haseeb362-amoxt** [comment]
OK I have found the solution
The solution was start mediaPlayer (mediaPlater.startPreview()) again in the rtmpStart method
Meaning whenever the stream gets started you have to run the preview on the surface

Similarly for dual cameras, I started the preview like camera.startPreview() as soon as rtmp feeds gets started

**Comment by pedroSG94** [comment]
Hello,

I was the last week working in this without luck but thanks to your track I found the real error. Call mediaplayer to render texture from glthread produce that stop. I solved it calling surfacefilter callback from main thread and works perfectly. Thank for your colaboration!
Fixed in: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/240dacd5bbdbe1cc334ddb2d962fd35da384cd4d

**Comment by bhavinatharva** [comment]
> [@pedroSG94](https://github.com/pedroSG94) Thank you for the amazing library I have a slight problem I think you can solve it When using OpenGL example from your repo with Surface Filter The bunny video plays for 3-4 seconds and stops A similar thing happens when I use the second cam, the front camera plays for some seconds and then stops the stream.
> 
> The bunny video and back camera both plays smoothly when stream is off, but as soon as I start stream they stop after some time.
> 
> Following is my simple code
> 
> ```
> SurfaceFilterRender surfaceFilterRender =
>               new SurfaceFilterRender(new SurfaceFilterRender.SurfaceReadyCallback() {
>                 @Override
>                 public void surfaceReady(SurfaceTexture surfaceTexture) {
>                   try {
>                     Camera mSecondaryCamera = getCameraInstance(1);
>                     mSecondaryCamera.setPreviewTexture(surfaceTexture);
>                     mSecondaryCamera.startPreview();
>                   } catch (IOException e) {
>                     e.printStackTrace();
>                   }
> 
>                 }
>               });
> ```
> 
> Please help as soon as you can, I would pay/donate in return. Thanks again for the amazing lib.

Hello @haseeb362-amoxt 

can you please share some example for understand, its really helpful

**Comment by pedroSG94** [comment]
Hello,

You have this example code to add surface filter to the stream:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/utils/FilterMenu.kt#L292
You can replace MediaPlayer with any class that allow render a surface. For example andorid camera API. You have a class to do it easier in the library. For example with camera2:
```kotlin
        val surfaceFilterRender = SurfaceFilterRender { surfaceTexture -> //You can render this filter with other api that draw in a surface. for example you can use VLC
          val camera = Camera2Source(context)
          if (camera.init(640, 480, 30, 0)) {
            camera.switchCamera() //by default using back camera, open front camera because back camera is already in use
            camera.start(surfaceTexture)
          }
        }
        glInterface.setFilter(surfaceFilterRender)
        //Resolution is 640x480 so select a percent to keep aspect ratio
        surfaceFilterRender.setScale(50f, 50f)
        surfaceFilterRender.rotation = 90 //we are in vertical stream, rotate camera to fix orientation
        //move to bottom-right
        surfaceFilterRender.setPosition(TranslateTo.BOTTOM_RIGHT)
```
You will need adjust values depend of your use case.

**Comment by bhavinatharva** [comment]
Hello @pedroSG94 

Thanks your sample code, It working.


I am trying to swap camera but i got the issue that used camerasource stuck the view ?

I need also that user can move that in the screen like drag , can you please help me to achieve that ?




```
private fun addDualCameraFilter() {
        // Get screen dimensions
        val displayMetrics = resources.displayMetrics
        val screenWidth = displayMetrics.widthPixels
        val screenHeight = displayMetrics.heightPixels

        // Define the 9:16 aspect ratio
        val aspectRatio = 9f / 16f

        // Calculate the width and height based on screen dimensions while keeping the 9:16 aspect ratio
        // Set the preview width to 20% of the screen width
        var previewWidth = (screenWidth * 0.1).toInt()
        // Calculate the height based on the 9:16 aspect ratio
        var previewHeight = (previewWidth * aspectRatio).toInt()

        // Ensure width and height are divisible by 2
        previewWidth = if (previewWidth % 2 != 0) previewWidth - 1 else previewWidth
        previewHeight = if (previewHeight % 2 != 0) previewHeight - 1 else previewHeight

        // If calculated height exceeds screen height, adjust the height to fit the screen
        if (previewHeight > screenHeight) {
            previewHeight = screenHeight
            previewWidth = (previewHeight / aspectRatio).toInt()

            // Ensure width and height are divisible by 2 after recalculation
            previewWidth = if (previewWidth % 2 != 0) previewWidth - 1 else previewWidth
            previewHeight = if (previewHeight % 2 != 0) previewHeight - 1 else previewHeight
        }

        val surfaceFilterRender =
            SurfaceFilterRender { surfaceTexture -> //You can render this filter with other api that draw in a surface. for example you can use VLC
                val camera = Camera2Source(this@DualCameraActivity)
                val fps = SharePrefUtil.getFrameRate(this)
                if (previewWidth <= 0 || previewHeight <= 0) {
                    // Fallback to a common resolution if calculated resolution is invalid
                    previewWidth = 640
                    previewHeight = 360
                }
                if (camera.init(previewWidth, previewHeight, fps, rotation)) {
                    if (isFrontCamera) {
                        camera.switchCamera() // Switch to the front camera
                    } else {
                        camera.switchCamera() // Switch to the back camera
                    }
                    camera.start(surfaceTexture)
                }
            }
        genericStream.getGlInterface().setFilter(surfaceFilterRender)

        // Set dynamic size based on screen dimensions
        surfaceFilterRender.setScale(50f, 50f)

        surfaceFilterRender.rotation =
            rotation //we are in vertical stream, rotate camera to fix orientation
        //move to bottom-right
        surfaceFilterRender.setPosition(TranslateTo.BOTTOM_RIGHT)
        spriteGestureController.setBaseObjectFilterRender(surfaceFilterRender) //Optional
    }
```

**Comment by pedroSG94** [comment]
The swap is simple. Since you can't use both cameras at the same time you only need to do this:
- Stop camera from filter
- Switch original camera source 
- Open again camera from filter using the other camera.

About the drag and drop you already have spriteGestureController initialized to do it like here:
- Handle the touch event:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/rotation/RotationActivity.kt#L152
- Initialize listener in the preview:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/rotation/CameraFragment.kt#L114

**Comment by bhavinatharva** [comment]
Hello @pedroSG94 

I am able to swap camera using camera source object , but in real device i a getting this error 

```
amera 3 is not available. Ignore physical camera status change
2025-03-04 15:04:41.163 18214-19017 CameraCaptureSession    com...rvasystem.quickscreenrecorder  E  Session 0: Exception while stopping repeating:  (Ask Gemini)
                                                                                                    android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): cancelRequest:612: Camera 0: Error clearing streaming request: Function not implemented (-38)
                                                                                                    	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1410)
                                                                                                    	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:99)
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1375)
                                                                                                    	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:584)
                                                                                                    	at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:795)
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:278)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211)
                                                                                                    	at android.os.Looper.loop(Looper.java:300)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: android.os.ServiceSpecificException: cancelRequest:612: Camera 0: Error clearing streaming request: Function not implemented (-38) (code 10)
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3025)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:2995)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2978)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2920)
                                                                                                    	at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:648)
                                                                                                    	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:97)
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1375) 
                                                                                                    	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:584) 
                                                                                                    	at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:795) 
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:278) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211) 
                                                                                                    	at android.os.Looper.loop(Looper.java:300) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) 
2025-03-04 15:04:41.166 18214-18763 CameraManagerGlobal     com...rvasystem.quickscreenrecorder  E  Camera 3 is not available. Ignore physical camera status change
```

**Comment by bhavinatharva** [comment]
Hello @pedroSG94 

how i can get callback of cameramanageapi 

fun setCameraCallbacks(cameraCallbacks: CameraCallbacks?) {
        this.cameraCallbacks = cameraCallbacks
    }

can you please update camerasource so i can get it in latest code?

**Comment by pedroSG94** [comment]
updated in master branch:
https://github.com/pedroSG94/RootEncoder/commit/ade2163b4ce0b0cdc912c00fa13b7bbcae27ec1c

**Comment by bhavinatharva** [comment]
Hello @pedroSG94 

Thank you for your response..
I have one query for surfaceFilterRender.
if i switch camera2source into this surfaceFilterRender then it show main camera in mirror effect means showing down-to-top

<img src="https://github.com/user-attachments/assets/21410056-f371-465b-9566-fabd5e398f5c" width='40%' height='50%'>
