### ISSUE TITLE
surfaceview rtsp example crashed on Android 6.0.1

### ISSUE THREAD

**Issue by jackjliew** [pedroSG94/rtmp-rtsp-stream-client-java#652]
surfaceview rtsp example crashed on Android 6.0.1

logcat logs: 
[rtsp-logcat.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/5122401/rtsp-logcat.txt)

08-25 16:34:04.266 18455-18466/com.pedro.rtpstreamer E/BufferQueueProducer: [SurfaceTexture-1-18455-0] cancelBuffer: BufferQueue has been abandoned
08-25 16:34:04.270 18455-18548/com.pedro.rtpstreamer E/BufferQueueProducer: [SurfaceTexture-1-18455-0] cancelBuffer: BufferQueue has been abandoned

08-25 16:34:05.157 18455-18615/com.pedro.rtpstreamer E/AndroidRuntime: FATAL EXCEPTION: BaseEncoder
    Process: com.pedro.rtpstreamer, PID: 18455
    java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
        at java.util.regex.Matcher.reset(Matcher.java:177)
        at java.util.regex.Matcher.<init>(Matcher.java:90)
        at java.util.regex.Pattern.matcher(Pattern.java:297)
        at com.pedro.rtsp.rtsp.RtspClient.connect(RtspClient.java:118)
        at com.pedro.rtplibrary.rtsp.RtspCamera2.onSpsPpsVpsRtp(RtspCamera2.java:167)
        at com.pedro.rtplibrary.base.Camera2Base.onSpsPps(Camera2Base.java:811)
        at com.pedro.encoder.video.VideoEncoder.sendSPSandPPS(VideoEncoder.java:274)
        at com.pedro.encoder.video.VideoEncoder.formatChanged(VideoEncoder.java:412)
        at com.pedro.encoder.BaseEncoder$2.onOutputFormatChanged(BaseEncoder.java:205)
        at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1577)
        at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1511)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by pedroSG94** [comment]
Ok, this is a bug when string is null in startStream method. 
Fixed: 
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/86913ae875665c323bd864aa31480a4dffc5c1ab
