### ISSUE TITLE
Sound disappears sometimes

### ISSUE THREAD

**Issue by mkrn** [pedroSG94/rtmp-rtsp-stream-client-java#659]
In my case i was able to reproduce one issue:
- Start stream 
- plug in wired microphone
- unplug 
- plug back in 
- unplug 
- no more audio with or without microphone.

Also, in a couple of instances sound has stopped without apparent reason. Is it possible?

**Comment by mkrn** [comment]
One time I plugged in mic and unplugged once and sound disappeared (0 kbps) 
Also, in one instance it disappeared completely shortly after stream start

**Comment by pedroSG94** [comment]
I never tried this library with external wired microphone, so I don’t know which could be the problem. I will try with a microphone that I have but I can’t promise you nothing.

About audio stopping. Do you means without wired microphone? Can you provide device info?

**Comment by mkrn** [comment]
In one instance user's audio disappeared during stream and was not recorded, nor streamed (video has audio in the beginning for a minute and then nothing at all).. How can it happen?

**Comment by pedroSG94** [comment]
I don't know.

The only possibility could be that user open other app that need microphone, producing that microphone stop, or a crash in audio encoder class. Also this could be a C++ crash implementation in codec.
This last one is really weird if you are recording 1min without problems because encoders normally crash on start or on stop: unsupported configuration, bad initialization, unexpected or malformed input buffer, etc. 
I'm investigating it and I will try fix it in next commit.

**Comment by pedroSG94** [comment]
Hello,

I was testing in my device with a wired microphone and all is working fine after plug in and out multiple times (I tried more than 10 times in multiple streams). If you can, test it with different microphone and different device to discard it.
I used a Samsung S7 and this headphones (include microphone): https://www.amazon.es/gp/product/B01LRX2DSA/ref=ppx_yo_dt_b_asin_title_o08_s00?ie=UTF8&psc=1

Anyway I did a commit with a change in microphone and encoder that could be your problem.
If your problem with microphone persist, let me know if you can see audio packets in logcat after plug in and out your microphone or any log related with encoder or microphone.

**Comment by mkrn** [comment]
Thanks I will test again!

**Comment by mkrn** [comment]
Actually this is connected to https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/665  
Both times it happened the audio stopped and recording was not playable.

This is what video recovery team said:

- Your original broken file contains only few 01:18 of audio. Your device after this timestamp stops recording audio.
- That's why we cannot determine FPS as video and audio are not sync. 
- We recovered your broken file at 25PS, but if you have a video reference file to upload, it can help to sync audio video video.
but more than 80% of audio are missing because audio data doesn't exist.

**Comment by mkrn** [comment]
Here's the logcat output where you see that only Video packets are sent after this issue happens  @pedroSG94 

```
2020-09-04 13:46:03.212 2896-3458/pro.eventlive D/RtmpConnection: wrote packet: RTMP Audio, size: 341
2020-09-04 13:46:03.214 2896-3458/pro.eventlive D/RtmpConnection: wrote packet: RTMP Audio, size: 343
2020-09-04 13:46:03.215 2896-3489/pro.eventlive E/MPEG4Writer: do not support out of order frames (timestamp: 38974693 < last: 38978112 for Audio track
2020-09-04 13:46:03.215 2896-3489/pro.eventlive E/MPEG4Writer: 0 frames to dump timeStamps in Audio track 
2020-09-04 13:46:03.215 2896-3489/pro.eventlive I/MPEG4Writer: Received total/0-length (1814/0) buffers and encoded 1813 frames. - Audio
2020-09-04 13:46:03.215 2896-3489/pro.eventlive I/MPEG4Writer: Audio track drift time: 0 us
2020-09-04 13:46:03.218 2896-3458/pro.eventlive D/RtmpConnection: wrote packet: RTMP Audio, size: 348
2020-09-04 13:46:03.218 2896-3414/pro.eventlive E/MediaAdapter: pushBuffer called before start
2020-09-04 13:46:03.219 2896-3458/pro.eventlive D/RtmpConnection: wrote packet: RTMP Audio, size: 339
2020-09-04 13:46:03.220 2896-3414/pro.eventlive I/BaseEncoder: Encoding error
    java.lang.IllegalStateException: writeSampleData returned an error
        at android.media.MediaMuxer.nativeWriteSampleData(Native Method)
        at android.media.MediaMuxer.writeSampleData(MediaMuxer.java:694)
        at com.pedro.rtplibrary.util.RecordController.recordAudio(RecordController.java:143)
        at com.pedro.rtplibrary.base.Camera2Base.getAacData(Camera2Base.java:810)
        at com.pedro.encoder.audio.AudioEncoder.sendBuffer(AudioEncoder.java:112)
        at com.pedro.encoder.BaseEncoder.processOutput(BaseEncoder.java:142)
        at com.pedro.encoder.BaseEncoder.outputAvailable(BaseEncoder.java:175)
        at com.pedro.encoder.BaseEncoder$2.onOutputBufferAvailable(BaseEncoder.java:194)
        at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1749)
        at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2020-09-04 13:46:03.221 2896-3414/pro.eventlive E/MediaAdapter: pushBuffer called before start
2020-09-04 13:46:03.222 2896-3458/pro.eventlive D/RtmpConnection: wrote packet: RTMP Audio, size: 346
2020-09-04 13:46:03.223 2896-3414/pro.eventlive I/BaseEncoder: Encoding error
    java.lang.IllegalStateException: writeSampleData returned an error
        at android.media.MediaMuxer.nativeWriteSampleData(Native Method)
        at android.media.MediaMuxer.writeSampleData(MediaMuxer.java:694)
        at com.pedro.rtplibrary.util.RecordController.recordAudio(RecordController.java:143)
        at com.pedro.rtplibrary.base.Camera2Base.getAacData(Camera2Base.java:810)
        at com.pedro.encoder.audio.AudioEncoder.sendBuffer(AudioEncoder.java:112)
        at com.pedro.encoder.BaseEncoder.processOutput(BaseEncoder.java:142)
        at com.pedro.encoder.BaseEncoder.outputAvailable(BaseEncoder.java:175)
        at com.pedro.encoder.BaseEncoder$2.onOutputBufferAvailable(BaseEncoder.java:194)
        at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1749)
        at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2020-09-04 13:46:03.223 2896-3414/pro.eventlive E/MediaAdapter: pushBuffer called before start
2020-09-04 13:46:03.225 2896-3414/pro.eventlive I/BaseEncoder: Encoding error
    java.lang.IllegalStateException: writeSampleData returned an error
        at android.media.MediaMuxer.nativeWriteSampleData(Native Method)
        at android.media.MediaMuxer.writeSampleData(MediaMuxer.java:694)
        at com.pedro.rtplibrary.util.RecordController.recordAudio(RecordController.java:143)
        at com.pedro.rtplibrary.base.Camera2Base.getAacData(Camera2Base.java:810)
        at com.pedro.encoder.audio.AudioEncoder.sendBuffer(AudioEncoder.java:112)
        at com.pedro.encoder.BaseEncoder.processOutput(BaseEncoder.java:142)
        at com.pedro.encoder.BaseEncoder.outputAvailable(BaseEncoder.java:175)
        at com.pedro.encoder.BaseEncoder$2.onOutputBufferAvailable(BaseEncoder.java:194)
        at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1749)
        at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2020-09-04 13:46:03.227 2896-3458/pro.eventlive D/RtmpConnection: wrote packet: RTMP Video, size: 4901
2020-09-04 13:46:03.257 2896-3458/pro.eventlive D/RtmpConnection: wrote packet: RTMP Video, size: 4229
2020-09-04 13:46:03.284 2896-3458/pro.eventlive D/RtmpConnection: wrote packet: RTMP Video, size: 5557
2020-09-04 13:46:03.313 2896-3458/pro.eventlive D/RtmpConnection: wrote packet: RTMP Video, size: 12997
2020-09-04 13:46:03.327 2896-2896/pro.eventlive D/DecorView: semSetRoundedCorners: 5
2020-09-04 13:46:03.342 2896-3458/pro.eventlive D/RtmpConnection: wrote packet: RTMP Video, size: 6133
2020-09-04 13:46:03.370 2896-3458/pro.eventlive D/RtmpConnection: wrote packet: RTMP Video, size: 6693
2020-09-04 13:46:03.400 2896-3458/pro.eventlive D/RtmpConnection: wrote packet: RTMP Video, size: 8613
2020-09-04 13:46:03.408 2896-3414/pro.eventlive E/MediaAdapter: pushBuffer called before start
2020-09-04 13:46:03.409 2896-3414/pro.eventlive I/BaseEncoder: Encoding error
    java.lang.IllegalStateException: writeSampleData returned an error
        at android.media.MediaMuxer.nativeWriteSampleData(Native Method)
        at android.media.MediaMuxer.writeSampleData(MediaMuxer.java:694)
        at com.pedro.rtplibrary.util.RecordController.recordAudio(RecordController.java:143)
        at com.pedro.rtplibrary.base.Camera2Base.getAacData(Camera2Base.java:810)
        at com.pedro.encoder.audio.AudioEncoder.sendBuffer(AudioEncoder.java:112)
        at com.pedro.encoder.BaseEncoder.processOutput(BaseEncoder.java:142)
        at com.pedro.encoder.BaseEncoder.outputAvailable(BaseEncoder.java:175)
        at com.pedro.encoder.BaseEncoder$2.onOutputBufferAvailable(BaseEncoder.java:194)
        at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1749)
        at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2020-09-04 13:46:03.438 2896-3458/pro.eventlive D/RtmpConnection: wrote packet: RTMP Video, size: 4917
2020-09-04 13:46:03.469 2896-3458/pro.eventlive D/RtmpConnection: wrote packet: RTMP Video, size: 10101
2020-09-04 13:46:03.502 2896-3458/pro.eventlive D/RtmpConnection: wrote packet: RTMP Video, size: 5701
2020-09-04 13:46:03.536 2896-3458/pro.eventlive D/RtmpConnection: wrote packet: RTMP Video, size: 12421
2020-09-04 13:46:03.569 2896-3458/pro.eventlive D/RtmpConnection: wrote packet: RTMP Video, size: 9989
```

**Comment by pedroSG94** [comment]
I could reproduce this error under an emulator and I did a fix for it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/f89563bbf257a719d0bddc5b85695833ede75e13
Use this gradle until I upload 1.9.0 version (I will develop other feature before upload it):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/f89563bbf257a719d0bddc5b85695833ede75e13
```gradle
implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:f89563bbf2
```
This fix should solve both audio problems that you mentioned.

**Comment by mkrn** [comment]
Hi @pedroSG94 I tried it with 1.9.1 and can't seem to be able to break it anymore! It's great!
