### ISSUE TITLE
Problem to connect Red5 with rtmp

### ISSUE THREAD

**Issue by ozankonur** [pedroSG94/rtmp-rtsp-stream-client-java#66]
when I try to connect red5 ( rtmp://192.168.56.1/oflaDemo ) , I am getting null pointer;

10-11 15:37:43.352 24153-25263/com.pedro.rtmpstreamer E/AndroidRuntime: FATAL EXCEPTION: Thread-10124
                                                                        Process: com.pedro.rtmpstreamer, PID: 24153
                                                                        java.lang.NullPointerException
                                                                            at com.github.faucamp.simplertmp.amf.AmfString.writeTo(AmfString.java:60)
                                                                            at com.github.faucamp.simplertmp.packets.VariableBodyRtmpPacket.writeVariableData(VariableBodyRtmpPacket.java:71)
                                                                            at com.github.faucamp.simplertmp.packets.Command.writeBody(Command.java:74)
                                                                            at com.github.faucamp.simplertmp.packets.RtmpPacket.writeTo(RtmpPacket.java:36)
                                                                            at com.github.faucamp.simplertmp.io.RtmpConnection.sendRtmpPacket(RtmpConnection.java:508)
                                                                            at com.github.faucamp.simplertmp.io.RtmpConnection.createStream(RtmpConnection.java:295)
                                                                            at com.github.faucamp.simplertmp.io.RtmpConnection.publish(RtmpConnection.java:278)
                                                                            at com.github.faucamp.simplertmp.DefaultRtmpPublisher.publish(DefaultRtmpPublisher.java:31)
                                                                            at net.ossrs.rtmp.SrsFlvMuxer.connect(SrsFlvMuxer.java:124)
                                                                            at net.ossrs.rtmp.SrsFlvMuxer.access$000(SrsFlvMuxer.java:46)
                                                                            at net.ossrs.rtmp.SrsFlvMuxer$1.run(SrsFlvMuxer.java:159)
                                                                            at java.lang.Thread.run(Thread.java:864)

**Comment by pedroSG94** [comment]
I think your url is bad. You missed stream name.
For example:
`rtmp://192.168.1.1:1935/app/pedro`
In your case should be:
`rtmp://192.168.56.1/oflaDemo/streamname`
If you are using Linux server, Red5 open code has a configuration bug:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/39
You should use Windows or Mac like server (Tested on Mac by @MikeMannox)

**Comment by ozankonur** [comment]
Thank you for quick answers. I think there is an error on red5 side.
