### ISSUE TITLE
After a few minutes app gives null pointer

### ISSUE THREAD

**Issue by ozankonur** [pedroSG94/rtmp-rtsp-stream-client-java#68]
Hi I am using client with  a server (https://github.com/iizukanao/node-rtsp-rtmp-server), after a few minutes I am getting this;

10-16 10:55:23.099 25505-25781/com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Audio, size: 377
10-16 10:55:23.099 25505-25781/com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Audio, size: 381
10-16 10:55:23.099 25505-25782/com.pedro.rtmpstreamer E/AndroidRuntime: FATAL EXCEPTION: Thread-18913
                                                                        Process: com.pedro.rtmpstreamer, PID: 25505
                                                                        java.lang.NullPointerException
                                                                            at net.ossrs.rtmp.SrsFlvMuxer$SrsFlv.writeVideoSample(SrsFlvMuxer.java:795)
                                                                            at net.ossrs.rtmp.SrsFlvMuxer.sendVideo(SrsFlvMuxer.java:218)
                                                                            at com.pedro.rtplibrary.rtmp.RtmpCamera1.getH264DataRtp(RtmpCamera1.java:85)
                                                                            at com.pedro.rtplibrary.base.Camera1Base.getH264Data(Camera1Base.java:370)
                                                                            at com.pedro.encoder.video.VideoEncoder.getDataFromEncoder(VideoEncoder.java:458)
                                                                            at com.pedro.encoder.video.VideoEncoder.access$1100(VideoEncoder.java:30)
                                                                            at com.pedro.encoder.video.VideoEncoder$1.run(VideoEncoder.java:244)
                                                                            at java.lang.Thread.run(Thread.java:864)

**Comment by pedroSG94** [comment]
Can you see in log the error when your app crash?:
`"annexb not match."`

**Comment by pedroSG94** [comment]
If you go to:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L795

And replace with:
```java
if (frame_pps.size > 0 && !frame_pps.data.equals(Pps)) {
```
This should be solved. Do it and test then let me know if the problem is solved.

**Comment by ozankonur** [comment]
yes, the bug fixed
