### ISSUE TITLE
After no successful match, app crash

### ISSUE THREAD

**Issue by ozankonur** [pedroSG94/rtmp-rtsp-stream-client-java#69]
E/AndroidRuntime: FATAL EXCEPTION: Thread-21629
                                                                        Process: com.pedro.rtmpstreamer, PID: 16725
                                                                        java.lang.IllegalStateException: No successful match so far
                                                                            at java.util.regex.Matcher.ensureMatch(Matcher.java:596)
                                                                            at java.util.regex.Matcher.group(Matcher.java:357)
                                                                            at com.pedro.rtsp.rtsp.RtspClient.getResponseStatus(RtspClient.java:479)
                                                                            at com.pedro.rtsp.rtsp.RtspClient.access$1000(RtspClient.java:29)
                                                                            at com.pedro.rtsp.rtsp.RtspClient$1.run(RtspClient.java:172)
                                                                            at java.lang.Thread.run(Thread.java:864)
10-17 17:12:15.179 1009-1023/? E/ActivityManager: App crashed! Process: com.pedro.rtmpstreamer

**Comment by pedroSG94** [comment]
Are you using?:
https://github.com/iizukanao/node-rtsp-rtmp-server

In this case I know the issue. I tried solved it without luck. I can do other try but no promise you anything

**Comment by ozankonur** [comment]
Yes.

**Comment by pedroSG94** [comment]
Fixed. RTSP is working with node-rtsp-rtmp now. Get last commit to test

**Comment by pedroSG94** [comment]
https://github.com/iizukanao/node-rtsp-rtmp-server is now working with rtsp (in TCP and UDP).
Get last commit: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/f22f5a46972bd1c53042d38d72153d9670915ba6
