### ISSUE TITLE
IllegalStateException at rtspFromFile.stopStream()

### ISSUE THREAD

**Issue by Fruchtzwerg94** [pedroSG94/rtmp-rtsp-stream-client-java#695]
Hi @pedroSG94 

after calling `rtspFromFile.stopStream()` when streaming, the following exception occurs:
```
I/CommandsManager: TEARDOWN rtsp://192.168.26.39:8554/app/stream RTSP/1.0
    CSeq: 5
    Session: 12345678
I/ACodec: [OMX.SEC.mp3.dec] Now Executing->Idle
I/ACodec: [OMX.SEC.mp3.dec] Now Idle->Loaded
    [OMX.SEC.mp3.dec] Now Loaded
     [OMX.SEC.mp3.dec] Now kWhatShutdownCompleted event : 8508
I/ACodec:  [OMX.SEC.mp3.dec] Now uninitialized
     [] Now kWhatShutdownCompleted event : 8508
I/MediaCodec: Codec shutdown complete
I/AudioEncoder: stopped
I/MediaCodec: Codec shutdown complete
I/BaseEncoder: Encoding error
    java.lang.IllegalStateException
        at android.media.MediaCodec.getBuffer(Native Method)
        at android.media.MediaCodec.getOutputBuffer(MediaCodec.java:3270)
        at com.pedro.encoder.BaseEncoder.outputAvailable(BaseEncoder.java:187)
        at com.pedro.encoder.BaseEncoder$2.onOutputBufferAvailable(BaseEncoder.java:211)
        at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1749)
        at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

Do you have an idea what could be the problem?

**Comment by pedroSG94** [comment]
You can ignore it. Library should work without problems.

That logcat is because sometimes a method of mediacodec is called after stop encoder. If you experiment a crash, the problem should be in other side

**Comment by Fruchtzwerg94** [comment]
Thanks for the info! No crash for me, so no problem! Just wanted to know if this is the right behaviour.
