### ISSUE TITLE
App crash when capturing audio from internal

### ISSUE THREAD

**Issue by svprdga** [pedroSG94/rtmp-rtsp-stream-client-java#703]
I got the following crash when trying to stream with the audio of the internal microphone:

> 2020-10-12 12:05:34.371 8358-10047/com.my.app E/AndroidRuntime: FATAL EXCEPTION: BaseEncoder
>     Process: com.my.app, PID: 8358
>     java.nio.BufferOverflowException
>         at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:298)
>         at com.pedro.encoder.BaseEncoder.processInput(BaseEncoder.java:136)
>         at com.pedro.encoder.BaseEncoder.inputAvailable(BaseEncoder.java:177)
>         at com.pedro.encoder.BaseEncoder$2.onInputBufferAvailable(BaseEncoder.java:201)
>         at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1738)
>         at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1696)
>         at android.os.Handler.dispatchMessage(Handler.java:107)
>         at android.os.Looper.loop(Looper.java:237)
>         at android.os.HandlerThread.run(HandlerThread.java:67)

- Library version: 1.9.3
- Streaming with DisplayBase
- Set audio to internal
- Affected devices: Galaxy Note 10+, Galaxy S10, Galaxy S20+

The app crashes as soon as I start the broadcast.

**Comment by pedroSG94** [comment]
This should be fixed now:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/3616ada83a650a00eda69fe4ac3cc60473535458

**Comment by svprdga** [comment]
I have tried the fix, now the initial crash is fixed, but the app is crashing when I stop the broadcast.

Logcat:

```
2020-10-15 18:35:00.736 8537-8537/com.svprdga.screenshare E/StreamService$stopScreencast$$inlined$let$lambda: Error while closing streaming session: End of input at line 1 column 1 path $
2020-10-15 18:35:00.737 8537-8537/com.svprdga.screenshare I/SrsFlvMuxer: SrsFlvMuxer closed
2020-10-15 18:35:00.738 8537-15835/com.svprdga.screenshare D/RtmpConnection: closeStream(): setting current stream ID to 0
2020-10-15 18:35:00.739 8537-15835/com.svprdga.screenshare D/RtmpConnection: socket closed
2020-10-15 18:35:00.740 8537-15835/com.svprdga.screenshare D/StreamService$connectCheckerRtp: Disconnected
2020-10-15 18:35:00.740 8537-15835/com.svprdga.screenshare I/SrsFlvMuxer: worker: disconnect ok.
2020-10-15 18:35:00.762 8537-12607/com.svprdga.screenshare E/AndroidRuntime: FATAL EXCEPTION: BaseEncoder
    Process: com.svprdga.screenshare, PID: 8537
    java.lang.IndexOutOfBoundsException: off=4, len=-3 out of bounds (size=5127)
        at java.nio.Buffer.checkBounds(Buffer.java:587)
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:292)
        at com.pedro.encoder.BaseEncoder.processInput(BaseEncoder.java:136)
        at com.pedro.encoder.BaseEncoder.inputAvailable(BaseEncoder.java:177)
        at com.pedro.encoder.BaseEncoder$2.onInputBufferAvailable(BaseEncoder.java:201)
        at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1738)
        at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2020-10-15 18:35:00.763 8537-8537/com.svprdga.screenshare I/MicrophoneManager: Microphone stopped
2020-10-15 18:35:00.763 8537-8537/com.svprdga.screenshare I/mali_egl: eglDestroySurface() in
2020-10-15 18:35:00.763 8537-8537/com.svprdga.screenshare I/mali_egl: eglDestroySurface() out
2020-10-15 18:35:00.865 8537-8537/com.svprdga.screenshare I/VideoEncoder: stopped
```

**Comment by pedroSG94** [comment]
I cant reproduce the error but this should fix your problem:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/b60bc6dc3cc5ca07707caa372dc8cbae74c8fb00

**Comment by svprdga** [comment]
Tested version 1.9.5, fixed.
