### ISSUE TITLE
Crash when stream on Emulator (NOX)

### ISSUE THREAD

**Issue by dangvanlinh** [pedroSG94/rtmp-rtsp-stream-client-java#704]
I got the following crash when trying to stream on NOX Emulator (ver.6.6.1.2)

`10-13 17:40:41.706 16272-16347/com.pedro.rtpstreamer E/SoftAVCEncoder: ConvertAvcSpecLevelToOmxAvcLevel: 31 level not supported
10-13 17:40:41.706 16272-16347/com.pedro.rtpstreamer E/OMXNodeInstance: getParameter(1:google.h264.encoder, ParamVideoAvc(0x600000d)) ERROR: Undefined(0x80001001)
10-13 17:40:41.706 16272-16347/com.pedro.rtpstreamer I/ACodec: setupVideoEncoder succeeded
10-13 17:40:41.706 16272-16347/com.pedro.rtpstreamer E/ACodec: [OMX.google.h264.encoder] configureCodec returning error -2147483648
10-13 17:40:41.706 16272-16347/com.pedro.rtpstreamer E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
10-13 17:40:41.706 16272-16346/com.pedro.rtpstreamer E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 3
10-13 17:40:41.706 16272-16272/com.pedro.rtpstreamer E/MediaCodec: configure failed with err 0x80001001, resetting...
10-13 17:40:41.706 16272-16347/com.pedro.rtpstreamer I/OMXClient: Using client-side OMX mux.
10-13 17:40:41.707 16272-16347/com.pedro.rtpstreamer I/SoftAVCEncoder: Construct SoftAVCEncoder
10-13 17:40:41.707 16272-16272/com.pedro.rtpstreamer E/VideoEncoder: Create VideoEncoder failed.
    android.media.MediaCodec$CodecException: Error 0x80001001
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:577)
        at com.pedro.encoder.video.VideoEncoder.prepareVideoEncoder(VideoEncoder.java:122)
        at com.pedro.rtplibrary.base.DisplayBase.prepareVideo(DisplayBase.java:121)
        at com.pedro.rtplibrary.base.DisplayBase.prepareVideo(DisplayBase.java:136)
        at com.pedro.rtplibrary.base.DisplayBase.prepareVideo(DisplayBase.java:208)
        at com.pedro.rtpstreamer.displayexample.DisplayService.startStreamRtp(DisplayService.kt:166)
        at com.pedro.rtpstreamer.displayexample.DisplayService.onStartCommand(DisplayService.kt:61)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2899)
        at android.app.ActivityThread.access$2100(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5307)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

**Comment by pedroSG94** [comment]
Can you share me video configuration?
I will check it but It will take time. This emulator is only for windows and actually I'm wokring on Linux so I need configure all to test.

**Comment by pedroSG94** [comment]
I was doing tests with NOX emulator but avc encoder is not working. This is an emulator problem, nothing to do here. 
For example, you have an issue with same codec error that you have in Exoplayer library:
https://github.com/google/ExoPlayer/issues/1785
Also this codec is so limitated. Of course, I tried configure codec using this params but not working. Codec info:
```
    OMX.google.h264.encoder
    Type: video/avc
    ----- Encoder info -----
    Complexity range: 0 - 0
    CBR supported: false
    VBR supported: true
    CQ supported: false
    ----- -----
    ----- Video info -----
    Supported colors: 
    2135033992
    19
    21
    2130708361
    Profile: 1, level: 32
    Bitrate range: 1 - 2000000
    Frame rate range: 0 - 960
    Width range: 2 - 896
    Height range: 2 - 896
```
