### ISSUE TITLE
NullPointerException when RtspSender.stop

### ISSUE THREAD

**Issue by 279154451** [pedroSG94/rtmp-rtsp-stream-client-java#733]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.pedro.rtsp.rtcp.BaseSenderReport.reset()' on a null object reference
        at com.pedro.rtsp.rtsp.RtspSender.stop(RtspSender.java:157)
        at com.pedro.rtspserver.RtspServer$Client.stopClient(RtspServer.kt:199)
        at com.pedro.rtspserver.RtspServer.stopServer(RtspServer.kt:63)
        at com.pedro.rtspserver.xrtsp.XRtspServerCamera1.stopStreamRtp(XRtspServerCamera1.kt:79)
        at com.pedro.rtspserver.xrtsp.XCamera1Base.stopStream(XCamera1Base.java:572)
        at com.pedro.sample.CameraDemoActivity$onConnectionFailedRtsp$1.run(CameraDemoActivity.kt:66)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6581)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Run

**Comment by pedroSG94** [comment]
Rtsp module was migrated to kotlin. Try update my library to this gradle (last master commit):
```gradle
	        implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:602d359f18'

```
