### ISSUE TITLE
We want to broadcast same camera stream on to 2 streaming urls simultaneously .

### ISSUE THREAD

**Issue by bharat-supekar** [pedroSG94/rtmp-rtsp-stream-client-java#735]
I want to broadcast same camera stream on to 2 streaming urls simultaneously .
I created two below instance -

RtmpCamera1 rtmpCamera1 = new RtmpCamera1(surfaceView, this);
RtmpCamera1    rtmpCamera2 = new RtmpCamera1(surfaceView, this);

and to start streaming I added  below code for both this streams.

if (!rtmpCamera1.isStreaming()) {
          if (rtmpCamera1.isRecording()
              || rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo()) {

            rtmpCamera1.startStream(etUrlLageView.getText().toString());
 rtmpCamera11.startStream(etUrlPIPMode.getText().toString());
          } else {
            Toast.makeText(this, "Error preparing stream, This device cant do it",
                Toast.LENGTH_SHORT).show();
          }
        } else {
          rtmpCamera1.stopStream();
        }

for same camera stream is working for one  url but for 2 streaming url at simultaneously its not working , it getting crashed, 
below is the crash we are getting by adding above code -- 

  Process: com.harman.dashcam, PID: 12462
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaCodec.setCallback(android.media.MediaCodec$Callback, android.os.Handler)' on a null object reference
        at com.pedro.encoder.BaseEncoder.initCodec(BaseEncoder.java:52)
        at com.pedro.encoder.BaseEncoder.start(BaseEncoder.java:42)
        at com.pedro.rtplibrary.base.Camera1Base.startEncoders(Camera1Base.java:510)
        at com.pedro.rtplibrary.base.Camera1Base.startStream(Camera1Base.java:501)
        at com.pedro.rtpstreamer.defaultexample.ExampleRtmpActivity.onClick(ExampleRtmpActivity.java:166)
        at android.view.View.performClick(View.java:6600)
        at com.pedro.rtpstreamer.defaultexample.ExampleRtmpActivity$1.run(ExampleRtmpActivity.java:81)

**Comment by pedroSG94** [comment]
You need do it like here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/549
