### ISSUE TITLE
Retry feature doesn't work with Limelight

### ISSUE THREAD

**Issue by marcin-adamczewski** [pedroSG94/rtmp-rtsp-stream-client-java#779]
Hi @pedroSG94 

I'm migrating from Vimeo to Limelight and I found that the retry feature doesn't work with Limelight. Regular streaming works well but when e.g. I turn off the Internet for a second, then turn it on, it tries to re-connect, doing authorization again, sends a few video/audio packets and then hangs...Sometimes after ~2 minutes it's getting connection timeout and authorize again, and then successfully sends video/audio packets. So it either hangs forever or for 2 minutes.
When I re-enter the Activity I can succesfully connect again.
The same situation happens when I start stream on one device and then try to stream from another device. On the second device I'm having the same problem. 
I've tested the same case in the OBS app (MacOS) and in the Larix Broadcaster app (Android) and both worked fine.

I can't figure out what may be the cause. Do you have any clue?
Below are the logs from this scenario. I removed unnecessery logs.

```
// First time connection
13:18:00.025 484/ I/SrsFlvMuxer: worker: connecting to RTMP server by url=rtmp://xxx-testuser-pri-rts.llnw.net/xxx/testuser_2400
13:18:00.026 484/ D/RtmpConnection: connect() called. Host: xxx-testuser-pri-rts.llnw.net, port: 1935, appName: xxx, publishPath: testuser_2400
13:18:00.026 484/ D/RtmpConnection: NEW SOCKET3
13:18:00.065 467/ I/SrsFlvMuxer: annexb not match, Trying without it. Maybe isn't h264 buffer
13:18:00.066 467/ I/SrsFlvMuxer: flv: h264 sps/pps sent, sps=18B, pps=5B
13:18:00.535 484/ D/RtmpConnection: Send buffer size: 1048576
13:18:00.535 484/ D/RtmpConnection: connect(): socket connection established, doing handhake...
13:18:00.683 484/ D/RtmpConnection: connect(): handshake done
13:18:00.683 487/ D/RtmpConnection: starting main rx handler loop
13:18:00.683 484/ D/RtmpConnection: rtmpConnect(): Building 'connect' invoke packet
13:18:00.685 484/ D/RtmpConnection: wrote packet: RTMP Command (command: connect, transaction ID: 1), size: 348
13:18:00.972 487/ I/RtmpConnection: [ AccessManager.Reject ] : [ authmod=adobe ] : ?reason=needauth&user=testuser&salt=h2N6MeU=&challenge=DzNSMZQ=
13:18:00.974 487/ D/RtmpConnection: socket closed
13:18:01.060 468/ I/SrsFlvMuxer: frame discarded
13:18:01.061 468/ I/SrsFlvMuxer: frame discarded
13:18:01.118 487/ D/RtmpConnection: NEW SOCKET1
13:18:01.119 487/ D/RtmpConnection: connect(): socket connection established, doing handshake...
13:18:01.140 468/ I/SrsFlvMuxer: frame discarded
13:18:01.223 468/ I/SrsFlvMuxer: frame discarded
13:18:01.267 487/ D/RtmpConnection: rtmpConnect(): Building 'connect' invoke packet
13:18:01.267 487/ D/RtmpConnection: wrote packet: RTMP Command (command: connect, transaction ID: 2), size: 454
13:18:01.300 468/ I/SrsFlvMuxer: frame discarded
13:18:01.622 468/ I/SrsFlvMuxer: frame discarded
13:18:01.624 488/ I/RtmpConnection: handleRxInvoke: Got result for invoked method: connect
13:18:01.625 484/ D/RtmpConnection: createStream(): Sending releaseStream command...
13:18:01.625 484/ D/RtmpConnection: wrote packet: RTMP Command (command: releaseStream, transaction ID: 3), size: 40
13:18:01.625 484/ D/RtmpConnection: createStream(): Sending FCPublish command...
13:18:01.625 484/ D/RtmpConnection: wrote packet: RTMP Command (command: FCPublish, transaction ID: 4), size: 36
13:18:01.626 484/ D/RtmpConnection: createStream(): Sending createStream command...
13:18:01.626 484/ D/RtmpConnection: wrote packet: RTMP Command (command: createStream, transaction ID: 5), size: 25
13:18:01.700 468/ I/SrsFlvMuxer: frame discarded
13:18:01.702 468/ I/SrsFlvMuxer: frame discarded
13:18:01.777 488/ I/RtmpConnection: handleRxInvoke: Got result for invoked method: releaseStream
13:18:01.777 488/ D/RtmpConnection: handleRxInvoke(): 'releaseStream'
13:18:01.780 468/ I/SrsFlvMuxer: frame discarded
13:18:01.861 468/ I/SrsFlvMuxer: frame discarded
13:18:01.923 488/ D/RtmpConnection: handleRxInvoke(): 'onFCPublish'
13:18:01.923 488/ I/RtmpConnection: handleRxInvoke: Got result for invoked method: FCPublish
13:18:01.923 488/ D/RtmpConnection: handleRxInvoke(): 'FCPublish'
13:18:01.924 488/ I/RtmpConnection: handleRxInvoke: Got result for invoked method: createStream
13:18:01.924 488/ D/RtmpConnection: handleRxInvoke(): Stream ID to publish: 1
13:18:01.924 488/ D/RtmpConnection: fmlePublish(): Sending publish command...
13:18:01.924 488/ D/RtmpConnection: wrote packet: RTMP Command (command: publish, transaction ID: 6), size: 41
13:18:01.940 468/ I/SrsFlvMuxer: frame discarded
13:18:02.130 467/ I/SrsFlvMuxer: frame discarded
13:18:02.135 488/ D/RtmpConnection: handleRxInvoke(): onStatus NetStream.Publish.Start
13:18:02.135 488/ D/RtmpConnection: onMetaData(): Sending empty onMetaData...
13:18:02.135 488/ D/RtmpConnection: wrote packet: com.github.faucamp.simplertmp.packets.Data@14ff4e6, size: 284
// Connected and properly sending video and audio frames
13:18:02.143 484/ D/RtmpConnection: wrote packet: RTMP Audio, size: 11
13:18:02.143 484/ I/SrsFlvMuxer: worker: send frame type=9, dts=228, size=131072B
13:18:02.147 484/ D/RtmpConnection: wrote packet: RTMP Video, size: 39
13:18:02.147 484/ D/RtmpConnection: wrote packet: RTMP Audio, size: 264
13:18:02.148 484/ I/SrsFlvMuxer: worker: send frame type=9, dts=232, size=131072B
13:18:02.148 484/ D/RtmpConnection: wrote packet: RTMP Video, size: 213
13:18:02.148 484/ D/RtmpConnection: wrote packet: RTMP Audio, size: 264
13:18:02.148 484/ D/RtmpConnection: wrote packet: RTMP Video, size: 3557
13:18:02.148 484/ D/RtmpConnection: wrote packet: RTMP Audio, size: 418
13:18:02.148 484/ D/RtmpConnection: wrote packet: RTMP Video, size: 597
13:18:02.148 484/ D/RtmpConnection: wrote packet: RTMP Audio, size: 359
//...Many more Video and Audio frames
13:18:06.547 484/ I/SrsFlvMuxer: worker: send frame type=9, dts=6708, size=131072B
13:18:06.549 484/ D/RtmpConnection: wrote packet: RTMP Video, size: 70997
13:18:06.583 484/ D/RtmpConnection: wrote packet: RTMP Audio, size: 260
13:18:10.986 484/ D/RtmpConnection: wrote packet: RTMP Audio, size: 249
13:18:11.001 484/ D/RtmpConnection: wrote packet: RTMP Video, size: 59045
13:18:11.064 484/ D/RtmpConnection: wrote packet: RTMP Video, size: 27269
//...Here I switched Internet from WiFi to LTE
13:18:11.130 488/ E/RtmpConnection: Caught SocketException while reading/decoding packet, shutting down: Software caused connection abort
13:18:11.140 484/ D/RtmpConnection: wrote packet: RTMP Audio, size: 254
13:18:11.140 484/ E/RtmpConnection: Caught IOException during write loop, shutting down: Broken pipe
13:18:11.243 209/ I/SrsFlvMuxer: SrsFlvMuxer closed
13:18:11.244 523/ D/RtmpConnection: closeStream(): setting current stream ID to 0
13:18:11.244 523/ D/RtmpConnection: wrote packet: RTMP Command (command: closeStream, transaction ID: 7), size: 24
13:18:11.244 523/ E/RtmpConnection: Caught IOException during write loop, shutting down: Broken pipe
13:18:11.248 523/ E/RtmpConnection: Shutdown socket
    java.io.IOException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:283)
        at java.net.AbstractPlainSocketImpl.shutdownInput(AbstractPlainSocketImpl.java:622)
        at java.net.Socket.shutdownInput(Socket.java:1570)
        at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:403)
        at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:383)
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:31)
        at net.ossrs.rtmp.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:210)
        at net.ossrs.rtmp.SrsFlvMuxer.access$900(SrsFlvMuxer.java:53)
        at net.ossrs.rtmp.SrsFlvMuxer$3.run(SrsFlvMuxer.java:365)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: android.system.ErrnoException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at libcore.io.Linux.shutdown(Native Method)
        at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:216)
        at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:216)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:281)
        at java.net.AbstractPlainSocketImpl.shutdownInput(AbstractPlainSocketImpl.java:622) 
        at java.net.Socket.shutdownInput(Socket.java:1570) 
        at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:403) 
        at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:383) 
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:31) 
        at net.ossrs.rtmp.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:210) 
        at net.ossrs.rtmp.SrsFlvMuxer.access$900(SrsFlvMuxer.java:53) 
        at net.ossrs.rtmp.SrsFlvMuxer$3.run(SrsFlvMuxer.java:365) 
        at java.lang.Thread.run(Thread.java:919) 
13:18:11.248 523/ D/RtmpConnection: socket closed
13:18:11.248 523/ I/SrsFlvMuxer: worker: disconnect ok.
13:18:11.355 209/ I/SrsFlvMuxer: SrsFlvMuxer closed
13:18:11.356 549/ I/SrsFlvMuxer: worker: disconnect ok.
13:18:11.465 209/ I/SrsFlvMuxer: SrsFlvMuxer closed
13:18:11.466 566/ I/SrsFlvMuxer: worker: disconnect ok.
13:18:11.560 562/ I/SrsFlvMuxer: annexb not match, Trying without it. Maybe isn't h264 buffer
13:18:11.561 562/ I/SrsFlvMuxer: flv: h264 sps/pps sent, sps=18B, pps=5B
13:18:12.422 468/ I/SrsFlvMuxer: frame discarded
13:18:12.501 468/ I/SrsFlvMuxer: frame discarded
// ...many discarded frames
13:18:15.386 468/ I/SrsFlvMuxer: frame discarded
13:18:15.457 562/ I/SrsFlvMuxer: frame discarded
13:18:15.467 681/ I/SrsFlvMuxer: worker: connecting to RTMP server by url=rtmp://xxx-testuser-pri-rts.llnw.net/xxx/testuser_2400
13:18:15.467 681/ D/RtmpConnection: connect() called. Host: xxx-testuser-pri-rts.llnw.net, port: 1935, appName: xxx, publishPath: testuser_2400
13:18:15.467 681/ D/RtmpConnection: NEW SOCKET3
13:18:15.519 562/ I/SrsFlvMuxer: frame discarded
13:18:15.583 468/ I/SrsFlvMuxer: frame discarded
// ...many discarded frames
13:18:16.187 562/ I/SrsFlvMuxer: frame discarded
13:18:16.255 562/ I/SrsFlvMuxer: frame discarded
13:18:16.292 681/ D/RtmpConnection: Send buffer size: 524288
13:18:16.292 681/ D/RtmpConnection: connect(): socket connection established, doing handhake...
13:18:16.324 562/ I/SrsFlvMuxer: frame discarded
13:18:16.463 468/ I/SrsFlvMuxer: frame discarded
13:18:16.463 681/ D/RtmpConnection: connect(): handshake done
13:18:16.463 468/ I/SrsFlvMuxer: frame discarded
13:18:16.464 468/ I/SrsFlvMuxer: frame discarded
13:18:16.464 681/ D/RtmpConnection: rtmpConnect(): Building 'connect' invoke packet
13:18:16.464 468/ I/SrsFlvMuxer: frame discarded
13:18:16.464 700/ D/RtmpConnection: starting main rx handler loop
13:18:16.465 468/ I/SrsFlvMuxer: frame discarded
13:18:16.466 681/ D/RtmpConnection: wrote packet: RTMP Command (command: connect, transaction ID: 1), size: 348
13:18:16.519 562/ I/SrsFlvMuxer: frame discarded
13:18:16.788 562/ I/SrsFlvMuxer: frame discarded
13:18:16.804 700/ I/RtmpConnection: [ AccessManager.Reject ] : [ authmod=adobe ] : ?reason=needauth&user=testuser&salt=ibxUxsw=&challenge=2qzchw4=
13:18:16.805 700/ D/RtmpConnection: socket closed
13:18:16.855 562/ I/SrsFlvMuxer: frame discarded
13:18:16.943 468/ I/SrsFlvMuxer: frame discarded
13:18:16.961 700/ D/RtmpConnection: NEW SOCKET1
13:18:16.961 700/ D/RtmpConnection: connect(): socket connection established, doing handshake...
13:18:16.981 468/ I/SrsFlvMuxer: frame discarded
13:18:17.117 562/ I/SrsFlvMuxer: frame discarded
13:18:17.143 700/ D/RtmpConnection: rtmpConnect(): Building 'connect' invoke packet
13:18:17.144 700/ D/RtmpConnection: wrote packet: RTMP Command (command: connect, transaction ID: 2), size: 454
13:18:17.188 562/ I/SrsFlvMuxer: frame discarded
13:18:17.502 468/ I/SrsFlvMuxer: frame discarded
13:18:17.519 701/ I/RtmpConnection: handleRxInvoke: Got result for invoked method: connect
13:18:17.519 562/ I/SrsFlvMuxer: frame discarded
13:18:17.520 681/ D/RtmpConnection: createStream(): Sending releaseStream command...
13:18:17.520 681/ D/RtmpConnection: wrote packet: RTMP Command (command: releaseStream, transaction ID: 3), size: 40
13:18:17.520 681/ D/RtmpConnection: createStream(): Sending FCPublish command...
13:18:17.520 681/ D/RtmpConnection: wrote packet: RTMP Command (command: FCPublish, transaction ID: 4), size: 36
13:18:17.521 681/ D/RtmpConnection: createStream(): Sending createStream command...
13:18:17.521 681/ D/RtmpConnection: wrote packet: RTMP Command (command: createStream, transaction ID: 5), size: 25
13:18:17.541 468/ I/SrsFlvMuxer: frame discarded
13:18:17.652 562/ I/SrsFlvMuxer: frame discarded
13:18:17.681 701/ I/RtmpConnection: handleRxInvoke: Got result for invoked method: releaseStream
13:18:17.681 701/ D/RtmpConnection: handleRxInvoke(): 'releaseStream'
13:18:17.718 562/ I/SrsFlvMuxer: frame discarded
13:18:17.821 468/ I/SrsFlvMuxer: frame discarded
13:18:17.828 701/ D/RtmpConnection: handleRxInvoke(): 'onFCPublish'
13:18:17.834 701/ I/RtmpConnection: handleRxInvoke: Got result for invoked method: FCPublish
13:18:17.834 701/ D/RtmpConnection: handleRxInvoke(): 'FCPublish'
13:18:17.834 701/ I/RtmpConnection: handleRxInvoke: Got result for invoked method: createStream
13:18:17.834 701/ D/RtmpConnection: handleRxInvoke(): Stream ID to publish: 1
13:18:17.834 701/ D/RtmpConnection: fmlePublish(): Sending publish command...
13:18:17.835 701/ D/RtmpConnection: wrote packet: RTMP Command (command: publish, transaction ID: 6), size: 41
13:18:17.855 562/ I/SrsFlvMuxer: frame discarded
13:18:18.061 468/ I/SrsFlvMuxer: frame discarded
13:18:18.081 701/ D/RtmpConnection: handleRxInvoke(): onStatus NetStream.Publish.Start
13:18:18.082 701/ D/RtmpConnection: onMetaData(): Sending empty onMetaData...
// ..Authorized and Reconnected and sending out some video and audio frames
13:18:18.082 701/ D/RtmpConnection: wrote packet: com.github.faucamp.simplertmp.packets.Data@cff6e9, size: 284
13:18:18.084 681/ D/RtmpConnection: wrote packet: RTMP Audio, size: 11
13:18:18.085 681/ I/SrsFlvMuxer: worker: send frame type=9, dts=11723, size=131072B
13:18:18.085 681/ D/RtmpConnection: wrote packet: RTMP Video, size: 39
13:18:18.086 681/ D/RtmpConnection: wrote packet: RTMP Audio, size: 258
13:18:18.086 681/ I/SrsFlvMuxer: worker: send frame type=9, dts=11724, size=131072B
13:18:18.087 681/ D/RtmpConnection: wrote packet: RTMP Video, size: 18005
13:18:18.087 681/ D/RtmpConnection: wrote packet: RTMP Audio, size: 254
13:18:18.087 681/ D/RtmpConnection: wrote packet: RTMP Video, size: 3221
13:18:18.087 681/ D/RtmpConnection: wrote packet: RTMP Audio, size: 251
13:18:18.088 681/ D/RtmpConnection: wrote packet: RTMP Video, size: 4693
13:18:18.088 681/ D/RtmpConnection: wrote packet: RTMP Audio, size: 271
13:18:18.088 681/ D/RtmpConnection: wrote packet: RTMP Video, size: 7989
13:18:18.088 681/ D/RtmpConnection: wrote packet: RTMP Audio, size: 269
13:18:18.088 681/ D/RtmpConnection: wrote packet: RTMP Video, size: 15045
13:18:18.088 681/ D/RtmpConnection: wrote packet: RTMP Audio, size: 259
13:18:18.088 681/ D/RtmpConnection: wrote packet: RTMP Video, size: 22277
13:18:18.089 681/ D/RtmpConnection: wrote packet: RTMP Audio, size: 269
13:18:18.089 681/ D/RtmpConnection: wrote packet: RTMP Video, size: 25125
13:18:18.089 681/ D/RtmpConnection: wrote packet: RTMP Audio, size: 261
13:18:18.093 681/ D/RtmpConnection: wrote packet: RTMP Video, size: 31381
13:18:18.093 681/ D/RtmpConnection: wrote packet: RTMP Audio, size: 274
13:18:18.093 681/ D/RtmpConnection: wrote packet: RTMP Video, size: 46597
13:18:18.094 681/ D/RtmpConnection: wrote packet: RTMP Audio, size: 257
13:18:18.094 681/ D/RtmpConnection: wrote packet: RTMP Video, size: 28213
13:18:18.094 681/ D/RtmpConnection: wrote packet: RTMP Audio, size: 264
13:18:18.094 681/ D/RtmpConnection: wrote packet: RTMP Video, size: 18053
// ...but after a while it stops sending out the frames
13:18:18.823 468/ I/SrsFlvMuxer: frame discarded
13:18:19.141 468/ I/SrsFlvMuxer: frame discarded
// ...a lot of discarded frames! Almost 2 minutes of discarded frames.
13:20:01.654 562/ I/SrsFlvMuxer: frame discarded
13:20:01.783 468/ I/SrsFlvMuxer: frame discarded
13:20:01.812 681/ E/RtmpConnection: Caught IOException during write loop, shutting down: Connection timed out
13:20:01.861 468/ I/SrsFlvMuxer: frame discarded
13:20:01.863 468/ I/SrsFlvMuxer: frame discarded
13:20:01.912 209/ I/SrsFlvMuxer: SrsFlvMuxer closed
13:20:01.913 771/ D/RtmpConnection: closeStream(): setting current stream ID to 0
13:20:01.914 771/ D/RtmpConnection: wrote packet: RTMP Command (command: closeStream, transaction ID: 7), size: 24
13:20:01.914 771/ E/RtmpConnection: Caught IOException during write loop, shutting down: Broken pipe
13:20:01.915 771/ E/RtmpConnection: Shutdown socket
    java.io.IOException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:283)
        at java.net.AbstractPlainSocketImpl.shutdownInput(AbstractPlainSocketImpl.java:622)
        at java.net.Socket.shutdownInput(Socket.java:1570)
        at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:403)
        at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:383)
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:31)
        at net.ossrs.rtmp.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:210)
        at net.ossrs.rtmp.SrsFlvMuxer.access$900(SrsFlvMuxer.java:53)
        at net.ossrs.rtmp.SrsFlvMuxer$3.run(SrsFlvMuxer.java:365)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: android.system.ErrnoException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at libcore.io.Linux.shutdown(Native Method)
        at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:216)
        at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:216)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:281)
        at java.net.AbstractPlainSocketImpl.shutdownInput(AbstractPlainSocketImpl.java:622) 
        at java.net.Socket.shutdownInput(Socket.java:1570) 
        at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:403) 
        at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:383) 
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:31) 
        at net.ossrs.rtmp.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:210) 
        at net.ossrs.rtmp.SrsFlvMuxer.access$900(SrsFlvMuxer.java:53) 
        at net.ossrs.rtmp.SrsFlvMuxer$3.run(SrsFlvMuxer.java:365) 
        at java.lang.Thread.run(Thread.java:919) 
13:20:01.916 771/ D/RtmpConnection: socket closed
13:20:01.917 771/ I/SrsFlvMuxer: worker: disconnect ok.
13:20:02.006 209/ I/SrsFlvMuxer: SrsFlvMuxer closed
13:20:02.007 778/ I/SrsFlvMuxer: worker: disconnect ok.
13:20:02.071 777/ I/SrsFlvMuxer: annexb not match, Trying without it. Maybe isn't h264 buffer
13:20:02.071 777/ I/SrsFlvMuxer: flv: h264 sps/pps sent, sps=18B, pps=5B
13:20:02.981 468/ I/SrsFlvMuxer: frame discarded
// Many discarded frames
13:20:05.941 468/ I/SrsFlvMuxer: frame discarded
13:20:05.979 777/ I/SrsFlvMuxer: frame discarded
13:20:06.009 785/ I/SrsFlvMuxer: worker: connecting to RTMP server by url=rtmp://xxx-testuser-pri-rts.llnw.net/xxx/testuser_2400
13:20:06.009 785/ D/RtmpConnection: connect() called. Host: xxx-testuser-pri-rts.llnw.net, port: 1935, appName: xxx, publishPath: testuser_2400
13:20:06.009 785/ D/RtmpConnection: NEW SOCKET3
13:20:06.021 468/ I/SrsFlvMuxer: frame discarded
13:20:06.023 468/ I/SrsFlvMuxer: frame discarded
// Many discarded frames
13:20:06.742 468/ I/SrsFlvMuxer: frame discarded
13:20:06.784 777/ I/SrsFlvMuxer: frame discarded
13:20:06.795 785/ D/RtmpConnection: Send buffer size: 524288
13:20:06.795 785/ D/RtmpConnection: connect(): socket connection established, doing handhake...
13:20:06.821 468/ I/SrsFlvMuxer: frame discarded
13:20:06.984 468/ I/SrsFlvMuxer: frame discarded
13:20:06.988 785/ D/RtmpConnection: connect(): handshake done
13:20:06.988 785/ D/RtmpConnection: rtmpConnect(): Building 'connect' invoke packet
13:20:06.989 787/ D/RtmpConnection: starting main rx handler loop
13:20:06.989 785/ D/RtmpConnection: wrote packet: RTMP Command (command: connect, transaction ID: 1), size: 348
13:20:07.047 777/ I/SrsFlvMuxer: frame discarded
13:20:07.313 777/ I/SrsFlvMuxer: frame discarded
13:20:07.330 787/ I/RtmpConnection: [ AccessManager.Reject ] : [ authmod=adobe ] : ?reason=needauth&user=testuser&salt=n7S8IJY=&challenge=CCony5g=
13:20:07.331 787/ D/RtmpConnection: socket closed
13:20:07.379 777/ I/SrsFlvMuxer: frame discarded
13:20:07.464 468/ I/SrsFlvMuxer: frame discarded
13:20:07.495 787/ D/RtmpConnection: NEW SOCKET1
13:20:07.496 787/ D/RtmpConnection: connect(): socket connection established, doing handshake...
13:20:07.515 777/ I/SrsFlvMuxer: frame discarded
13:20:07.647 777/ I/SrsFlvMuxer: frame discarded
13:20:07.674 787/ D/RtmpConnection: rtmpConnect(): Building 'connect' invoke packet
13:20:07.676 787/ D/RtmpConnection: wrote packet: RTMP Command (command: connect, transaction ID: 2), size: 454
13:20:07.701 468/ I/SrsFlvMuxer: frame discarded
13:20:08.047 777/ I/SrsFlvMuxer: frame discarded
13:20:08.049 788/ I/RtmpConnection: handleRxInvoke: Got result for invoked method: connect
13:20:08.050 785/ D/RtmpConnection: createStream(): Sending releaseStream command...
13:20:08.050 785/ D/RtmpConnection: wrote packet: RTMP Command (command: releaseStream, transaction ID: 3), size: 40
13:20:08.050 785/ D/RtmpConnection: createStream(): Sending FCPublish command...
13:20:08.051 785/ D/RtmpConnection: wrote packet: RTMP Command (command: FCPublish, transaction ID: 4), size: 36
13:20:08.051 785/ D/RtmpConnection: createStream(): Sending createStream command...
13:20:08.051 785/ D/RtmpConnection: wrote packet: RTMP Command (command: createStream, transaction ID: 5), size: 25
13:20:08.101 468/ I/SrsFlvMuxer: frame discarded
13:20:08.188 777/ I/SrsFlvMuxer: frame discarded
13:20:08.202 788/ I/RtmpConnection: handleRxInvoke: Got result for invoked method: releaseStream
13:20:08.203 788/ D/RtmpConnection: handleRxInvoke(): 'releaseStream'
13:20:08.244 777/ I/SrsFlvMuxer: frame discarded
13:20:08.341 468/ I/SrsFlvMuxer: frame discarded
13:20:08.355 788/ D/RtmpConnection: handleRxInvoke(): 'onFCPublish'
13:20:08.355 788/ I/RtmpConnection: handleRxInvoke: Got result for invoked method: FCPublish
13:20:08.355 788/ D/RtmpConnection: handleRxInvoke(): 'FCPublish'
13:20:08.367 788/ I/RtmpConnection: handleRxInvoke: Got result for invoked method: createStream
13:20:08.367 788/ D/RtmpConnection: handleRxInvoke(): Stream ID to publish: 1
13:20:08.367 788/ D/RtmpConnection: fmlePublish(): Sending publish command...
13:20:08.368 788/ D/RtmpConnection: wrote packet: RTMP Command (command: publish, transaction ID: 6), size: 41
13:20:08.378 777/ I/SrsFlvMuxer: frame discarded
13:20:08.582 468/ I/SrsFlvMuxer: frame discarded
13:20:08.603 788/ D/RtmpConnection: handleRxInvoke(): onStatus NetStream.Publish.Start
13:20:08.603 788/ D/RtmpConnection: onMetaData(): Sending empty onMetaData...
13:20:08.603 788/ D/RtmpConnection: wrote packet: com.github.faucamp.simplertmp.packets.Data@d92701e, size: 284
// !!! Finally connected again and works fine. Sending out audio and video frames.
13:20:08.611 785/ D/RtmpConnection: wrote packet: RTMP Audio, size: 11
13:20:08.612 785/ I/SrsFlvMuxer: worker: send frame type=9, dts=122233, size=131072B
13:20:08.613 785/ D/RtmpConnection: wrote packet: RTMP Video, size: 39
13:20:08.614 785/ D/RtmpConnection: wrote packet: RTMP Audio, size: 251
13:20:08.614 785/ I/SrsFlvMuxer: worker: send frame type=9, dts=122238, size=131072B
13:20:08.614 785/ D/RtmpConnection: wrote packet: RTMP Video, size: 3477
13:20:08.615 785/ D/RtmpConnection: wrote packet: RTMP Audio, size: 242
13:20:08.615 785/ D/RtmpConnection: wrote packet: RTMP Video, size: 293
13:20:08.616 785/ D/RtmpConnection: wrote packet: RTMP Audio, size: 256
13:24:16.864 785/ D/RtmpConnection: wrote packet: RTMP Video, size: 27605
13:24:16.904 785/ D/RtmpConnection: wrote packet: RTMP Audio, size: 252
13:24:16.906 785/ D/RtmpConnection: wrote packet: RTMP Audio, size: 274
13:24:16.907 785/ D/RtmpConnection: wrote packet: RTMP Audio, size: 254
13:24:16.933 785/ D/RtmpConnection: wrote packet: RTMP Video, size: 15285
// Manually disconnected
13:24:16.964 209/ I/SrsFlvMuxer: SrsFlvMuxer closed
13:24:16.965 960/ D/RtmpConnection: closeStream(): setting current stream ID to 0
13:24:16.966 960/ D/RtmpConnection: wrote packet: RTMP Command (command: closeStream, transaction ID: 7), size: 24
13:24:16.967 960/ D/RtmpConnection: socket closed
13:24:16.968 960/ I/SrsFlvMuxer: worker: disconnect ok.
```

**Comment by pedroSG94** [comment]
I see. This look that your stream is in use and you can't connect to it properly.
I want to fix it but I have a problem. I tried send an email to limelight looking for a trial to test [auth](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/766) (1 week ago) but I don't receive any response so I can't test it.
Same with your problem. I can't reproduce it because I haven't a trial to test.
