### ISSUE TITLE
RMTP 只做音频推送，在连麦中，关闭麦克风的时候程序直接崩溃，已下是日志，请博主指点一二谢谢，实在是没头绪

### ISSUE THREAD

**Issue by ILoveLin** [pedroSG94/rtmp-rtsp-stream-client-java#832]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2726)
        at com.pedro.encoder.audio.AudioEncoder.getDataFromEncoderAPI21(AudioEncoder.java:139)
        at com.pedro.encoder.audio.AudioEncoder.inputPCMData(AudioEncoder.java:131)
        at com.pedro.rtplibrary.base.Camera3Base.inputPCMData(Camera3Base.java:813)
        at com.pedro.encoder.input.audio.MicrophoneManager$1.run(MicrophoneManager.java:85)
        at java.lang.Thread.run(Thread.java:929)

**Comment by pedroSG94** [comment]
I can see that you modified the library. 
Use my app example and try reproduce it. After that report me steps to reproduce and share me a full logcat

**Comment by ILoveLin** [comment]
I want to push only RTMP audio stream, what should I do to realize the voice call function?

**Comment by pedroSG94** [comment]
You can use RtmpOnlyAudio

**Comment by ILoveLin** [comment]
I ran the Demo and selected Custom RTMP type to test, but I couldn't find RTMponlyAudio, how should I start?

**Comment by pedroSG94** [comment]
Try this:
```java
RtmpOnlyAudio rtmpOnlyAudio = new RtmpOnlyAudio(connectCheckerRtmp);
    if (rtmpOnlyAudio.prepareAudio()) {
      rtmpOnlyAudio.startStream("endpoint");
    }
```

**Comment by ILoveLin** [comment]
OK. I'll have a try

**Comment by ILoveLin** [comment]
Hello blogger,I wrote a Demo to test it out,When I send RTMP audio push stream, I report an error directly.The following is the error log


`2021-05-10 09:54:35.621 27648-27648/com.company.micdemo E/TAG====: Start=====onResponse==mPusherUrl==rtmp://192.168.66.42:8350/live/39586
2021-05-10 09:54:35.623 27648-27648/com.company.micdemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.company.micdemo, PID: 27648
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaCodec.setCallback(android.media.MediaCodec$Callback, android.os.Handler)' on a null object reference
        at com.pedro.encoder.BaseEncoder.initCodec(BaseEncoder.java:54)
        at com.pedro.encoder.BaseEncoder.start(BaseEncoder.java:45)
        at com.pedro.rtplibrary.base.OnlyAudioBase.startEncoders(OnlyAudioBase.java:206)
        at com.pedro.rtplibrary.base.OnlyAudioBase.startStream(OnlyAudioBase.java:187)
        at com.company.micdemo.MainActivity.gotoStart(MainActivity.java:112)
        at com.company.micdemo.MainActivity.access$200(MainActivity.java:25)
        at com.company.micdemo.MainActivity$2.onResponse(MainActivity.java:99)
        at com.company.micdemo.MainActivity$2.onResponse(MainActivity.java:83)
        at com.zhy.http.okhttp.OkHttpUtils$3.run(OkHttpUtils.java:186)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)`
