### ISSUE TITLE
Broken pipe error

### ISSUE THREAD

**Issue by mustafaboleken** [pedroSG94/rtmp-rtsp-stream-client-java#843]
Hi, I use Ant Media Server and everything is ok. But now, After 3 minutes of streaming I get this error. I try Custom RTMP and OpenGl RTMP on demo app but got same error..

2021-04-23 11:47:57.291 10685-10958/com.pedro.rtpstreamer E/RtmpConnection: Caught IOException during write loop, shutting down: Broken pipe
2021-04-23 11:47:57.293 10685-10958/com.pedro.rtpstreamer E/RtmpConnection: Shutdown socket
    java.io.IOException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:283)
        at java.net.AbstractPlainSocketImpl.shutdownInput(AbstractPlainSocketImpl.java:622)
        at java.net.Socket.shutdownInput(Socket.java:1580)
        at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:412)
        at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:392)
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:31)
        at net.ossrs.rtmp.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:197)
        at net.ossrs.rtmp.SrsFlvMuxer.access$900(SrsFlvMuxer.java:53)
        at net.ossrs.rtmp.SrsFlvMuxer$3.run(SrsFlvMuxer.java:339)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: android.system.ErrnoException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at libcore.io.Linux.shutdown(Native Method)
        at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:216)
        at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:216)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:281)
        at java.net.AbstractPlainSocketImpl.shutdownInput(AbstractPlainSocketImpl.java:622) 
        at java.net.Socket.shutdownInput(Socket.java:1580) 
        at com.github.faucamp.simplertmp.io.RtmpConnection.shutdown(RtmpConnection.java:412) 
        at com.github.faucamp.simplertmp.io.RtmpConnection.close(RtmpConnection.java:392) 
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.close(DefaultRtmpPublisher.java:31) 
        at net.ossrs.rtmp.SrsFlvMuxer.disconnect(SrsFlvMuxer.java:197) 
        at net.ossrs.rtmp.SrsFlvMuxer.access$900(SrsFlvMuxer.java:53) 
        at net.ossrs.rtmp.SrsFlvMuxer$3.run(SrsFlvMuxer.java:339) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by pedroSG94** [comment]
That error is because client or server close connection.
In my side, I only close socket in this method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L408
You can check your device logcat and filter to find that logs. I think that server close connection.
Do you have any way to check logs from server?

Also, make sure that you have a stable connection and disable proxy if you are using one t discard it.

**Comment by mustafaboleken** [comment]
I try lots thing  finallly solved by resetting all server settings

**Comment by hemant-novotrax** [comment]
> I try lots thing finallly solved by resetting all server settings

@mustafaboleken plz let me know the setting on server side.
