### ISSUE TITLE
Encoder is not supported resolution 4224x2376

### ISSUE THREAD

**Issue by chauvansang1997** [pedroSG94/rtmp-rtsp-stream-client-java#854]
This is my log.
```
I/AudioPostProcessEffect: NoiseSuppressor enabled
I/MicrophoneManager: Microphone created, 32000hz, Stereo
W/VideoCapabilities: Unsupported mime video/divx
W/VideoCapabilities: Unsupported mime video/divx311
W/VideoCapabilities: Unsupported mime video/divx4
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities: Unsupported mime video/x-ms-wmv
W/VideoCapabilities: Unsupported mime video/x-ms-wmv
W/Utils: could not parse long range '175-174'
D/CCodec: allocate(c2.android.aac.encoder)
I/Codec2Client: Available Codec2 services: "software"
    Creating a Codec2 client to service "software"
I/Codec2Client: Client to Codec2 service "software" created
I/n.tpos.tposliv: Background concurrent copying GC freed 21978(876KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 3840KB/7681KB, paused 21.053ms total 165.576ms
I/CCodec: Created component [c2.android.aac.encoder]
D/CCodecConfig: read media type: audio/mp4a-latm
D/ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.max-count.values
    extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater: extent() != 1 for single value type: input.buffers.allocator-ids.values
    extent() != 1 for single value type: output.buffers.allocator-ids.values
    extent() != 1 for single value type: algo.buffers.allocator-ids.values
    extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig: query failed after returning 9 values (BAD_INDEX)
D/CCodecConfig: c2 config is Dict {
      c2::u32 coded.bitrate.value = 64000
      c2::u32 coded.pl.level = 0
      c2::u32 coded.pl.profile = 8192
      c2::u32 coding.aac-sbr-mode.value = 3
      c2::u32 input.buffers.max-size.value = 2048
      c2::u32 input.delay.value = 0
      string input.media-type.value = "audio/raw"
      string output.media-type.value = "audio/mp4a-latm"
      c2::u32 raw.channel-count.value = 1
      c2::u32 raw.sample-rate.value = 44100
    }
D/CCodecConfig: no c2 equivalents for aac-profile
    no c2 equivalents for encoder
D/CCodecConfig: c2 config is Dict {
      c2::u32 coded.bitrate.value = 65536
      c2::u32 coded.pl.level = 0
      c2::u32 coded.pl.profile = 8192
      c2::u32 coding.aac-sbr-mode.value = 3
      c2::u32 input.buffers.max-size.value = 4096
      c2::u32 input.delay.value = 0
      string input.media-type.value = "audio/raw"
      string output.media-type.value = "audio/mp4a-latm"
      c2::u32 raw.channel-count.value = 2
      c2::u32 raw.sample-rate.value = 32000
    }
W/Codec2Client: query -- param skipped: index = 1107298332.
D/CCodec: setup formats input: AMessage(what = 0x00000000) = {
      int32_t channel-count = 2
      int32_t max-input-size = 5120
      string mime = "audio/raw"
      int32_t sample-rate = 32000
    } and output: AMessage(what = 0x00000000) = {
      int32_t bitrate = 65536
      int32_t channel-count = 2
      int32_t level = 0
      int32_t max-bitrate = 65536
      string mime = "audio/mp4a-latm"
      int32_t profile = 2
      int32_t sample-rate = 32000
    }
I/AudioEncoder: prepared
I/VideoEncoder: VideoEncoder OMX.qcom.video.encoder.avc
    Color supported: 2141391876
    Color supported: 2130708361
I/OMXClient: IOmx service obtained
I/VideoEncoder: Prepare video info: SURFACE, 2376x4224
    bitrate mode CBR not supported using default mode
I/ExtendedACodec: setupVideoEncoder()
W/OMXUtils: do not know color format 0x7fa30c04 = 2141391876
W/OMXUtils: do not know color format 0x7f000789 = 2130708361
I/ACodec: setupAVCEncoderParameters with [profile: High] [level: Level11]
E/ExtendedACodec: [OMX.qcom.video.encoder.avc] configureCodec returning error -1010
E/ACodec: signalError(omxError 0x80001001, internalError -1010)
    [OMX.qcom.video.encoder.avc] configureCodec returning error -1010
    signalError(omxError 0x80001001, internalError -1010)
E/MediaCodec: Codec reported err 0xfffffc0e, actionCode 0, while in state 3
E/MediaCodec: Codec reported err 0xfffffc0e, actionCode 0, while in state 0
E/MediaCodec: configure failed with err 0xfffffc0e, resetting...
I/OMXClient: IOmx service obtained
E/VideoEncoder: Create VideoEncoder failed.
    android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2023)
        at android.media.MediaCodec.configure(MediaCodec.java:1951)
        at vn.tpos.stream_with_rtmp.AppVideoEncoder.prepareVideoEncoder(AppVideoEncoder.java:218)
        at vn.tpos.stream_with_rtmp.EncoderManager.prepareVideo(EncoderManager.kt:239)
        at vn.tpos.stream_with_rtmp.EncoderManager.prepareVideo$default(EncoderManager.kt:231)
        at vn.tpos.stream_with_rtmp.EncoderManager.prepareVideo(EncoderManager.kt:301)
        at vn.tpos.stream_with_rtmp.CameraEncoderManager.prepareEncoder(CameraEncoderManager.kt:90)
        at vn.tpos.stream_with_rtmp.RtmpManager.startListConnection(RtmpManager.kt:160)
        at vn.tpos.stream_with_rtmp.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.kt:218)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:181)
        at android.app.ActivityThread.main(ActivityThread.java:7590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/VideoEncoder: stopped
I/VideoEncoder: started
E/MethodChannel#plugins.flutter.io/camera_with_rtmp: Failed to handle method call
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaCodec.setCallback(android.media.MediaCodec$Callback, android.os.Handler)' on a null object reference
        at com.pedro.encoder.BaseEncoder.initCodec(BaseEncoder.java:49)
        at com.pedro.encoder.BaseEncoder.start(BaseEncoder.java:40)
        at vn.tpos.stream_with_rtmp.EncoderManager.startEncoders(EncoderManager.kt:462)
        at vn.tpos.stream_with_rtmp.RtmpManager.startListConnection(RtmpManager.kt:164)
        at vn.tpos.stream_with_rtmp.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.kt:218)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:181)
        at android.app.ActivityThread.main(ActivityThread.java:7590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by pedroSG94** [comment]
I can see in logs that prepareVideo return false. Are you using a resolution provided by this methods?:
```java
rtmpCamera2.getResolutionsBack();
rtmpCamera2.getResolutionsFront();
```
If you are using a resolution provided by that methods, prepareVideo method never should return false. Anyway maybe the encoder selected is not the best in your case and that could be the problem.
Can you show me logcat using this code?:
```java
for (String s: CodecUtil.showAllCodecsInfo()) Log.e("Pedro", s);
```

**Comment by chauvansang1997** [comment]
Thanks you for you help.
