### ISSUE TITLE
Crash: invalid face detection type=0

### ISSUE THREAD

**Issue by AlexUrrutia** [pedroSG94/rtmp-rtsp-stream-client-java#863]
Hello Pedro, I am getting this crash on the Crashlytics console on different HUAWEI and Samsung devices:

Any info? Thanks!

```
Fatal Exception: java.lang.IllegalArgumentException: invalid face detection type=0
       at android.hardware.Camera._startFaceDetection(Camera.java)
       at android.hardware.Camera.startFaceDetection(Camera.java:1782)
       at com.pedro.encoder.input.video.Camera1ApiManager.enableFaceDetection(Camera1ApiManager.java:549)
       at com.pedro.rtplibrary.base.Camera1Base.enableFaceDetection(Camera1Base.java:166)
       at android.os.AsyncTask.finish(AsyncTask.java:727)
       at android.os.AsyncTask.-wrap1()
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:744)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by pedroSG94** [comment]
Hello,

This means that your device don't support face detection. I will handle with this and return you boolean to know if success.
https://developer.android.com/reference/android/hardware/Camera#startFaceDetection()

**Comment by AlexUrrutia** [comment]
Thank you!
