### ISSUE TITLE
When should OpenGL be used?

### ISSUE THREAD

**Issue by HirogaKatageri** [pedroSG94/rtmp-rtsp-stream-client-java#866]
We've been getting an error regarding OpenGL using RtmpDisplay.

```
eglCreateWindowSurface. EGL error: 12291
```

- Is OpenGL necessary, If not when should I use it? 
- Is there a way to check if it can be enabled?

**Comment by pedroSG94** [comment]
Hello,

Opengl is not necessary but it allow you to use multiple features like filters.

About the error:
Can you share a full logcat error to know crash line?
Also, let me know device info (model and api).
Is it 100% reproducible? can you share steps to reproduce it (if you can include code)?

**Comment by HirogaKatageri** [comment]
It is actually 100% reproducible but only on a handful of devices.
- Huawei Honor Play (API 28
- RealMe C12 (API 29)

Here's the stack from Crashlytics

For Honor Play (API 28)
```
Fatal Exception: java.lang.RuntimeException: eglCreateWindowSurface. EGL error: 12291
       at com.pedro.encoder.utils.gl.GlUtil.checkEglError(GlUtil.java:133)
       at com.pedro.encoder.input.gl.SurfaceManager.eglSetup(SurfaceManager.java:161)
       at com.pedro.encoder.input.gl.SurfaceManager.<init>(SurfaceManager.java:32)
       at com.pedro.rtplibrary.view.OffScreenGlThread.addMediaCodecSurface(OffScreenGlThread.java:113)
       at com.pedro.rtplibrary.base.DisplayBase.resetVideoEncoder(DisplayBase.java:416)
       at com.pedro.rtplibrary.base.DisplayBase.reTry(DisplayBase.java:461)
       at com.pedro.rtplibrary.base.DisplayBase.reTry(DisplayBase.java:451)
       at tv.nexusgaming.streaming.mvp.main.dashboard.LiveStreamManager$RtmpConnectionListener$retryConnection$2.invokeSuspend(LiveStreamManager.kt:1055)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

For RealMe C12 (API 29)
```
Fatal Exception: java.lang.RuntimeException: drawFilter end. GL error: 1281
       at com.pedro.encoder.utils.gl.GlUtil.checkGlError(GlUtil.java:126)
       at com.pedro.encoder.input.gl.render.filters.BaseFilterRender.draw(BaseFilterRender.java:55)
       at com.pedro.encoder.input.gl.render.ManagerRender.drawOffScreen(ManagerRender.java:61)
       at com.pedro.rtplibrary.view.OffScreenGlThread.run(OffScreenGlThread.java:236)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by pedroSG94** [comment]
I see. 

- The first one could be a bug related with opengl lifecycle because it is produced after a retry. I will check if all is properly released, it is the most common reason for it.

- About the second error, that is different from previous error and really weird. That normally is because your are using opengl outside of opengl context but it is not the case. Maybe related with thread stop sync error? Do you have any way to know if it is produced when you stop stream/record?

**Comment by HirogaKatageri** [comment]
"About the second error, that is different from previous error and is really weird. That normally is because your are using opengl outside of opengl context but it is not the case. Maybe related with thread stop sync error? Do you have any way to know if it is produced when you stop stream/record?"

- Actually, we found out it happens while streaming, around 5 to 15 seconds just when the stream started.

**Comment by pedroSG94** [comment]
Are you using any filter?
I will refactor the opengl error to show it better and get some information on this.

**Comment by HirogaKatageri** [comment]
"Are you using any filter?"
- Yes, we actually are using around 4 filters, Image and Text Filters.

**Comment by pedroSG94** [comment]
Please, remove it in that device to reduce posisble reasons.
If that solve the problem, try play with filters to know exact problem. Set filters one by one to detect which is problem.

**Comment by HirogaKatageri** [comment]
Okay, I'll try that.

**Comment by pedroSG94** [comment]
I did a commit for the first error:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/c10f8ecdb88670a003733947b345d14d57f434de
Let me know if this solve your error. 

About second error, I added logs to help me with GL debugging for this case. Also, I will wait for your response because I don't know the possible reason without it.

**Comment by HirogaKatageri** [comment]
Just an update:

We haven't tested it yet this week but we should be able to test it next week after we move to MultiRtpDisplay.

**Comment by welcome2c** [comment]
@pedroSG94 Hi I got the same error 
my test case is app dies right away to persist Wi-Fi while streaming

this is my error logcat

   java.lang.RuntimeException: eglCreateWindowSurface. EGL error: 12291
        at com.pedro.encoder.utils.gl.GlUtil.checkEglError(GlUtil.java:133)
        at com.pedro.encoder.input.gl.SurfaceManager.eglSetup(SurfaceManager.java:161)
        at com.pedro.encoder.input.gl.SurfaceManager.<init>(SurfaceManager.java:32)
        at com.pedro.rtplibrary.view.OpenGlViewBase.addMediaCodecSurface(OpenGlViewBase.java:123)
        at com.pedro.rtplibrary.base.Camera2Base.resetVideoEncoder(Camera2Base.java:564)
        at com.pedro.rtplibrary.base.Camera2Base.reTry(Camera2Base.java:642)
        at com.pedro.rtplibrary.base.Camera2Base.reTry(Camera2Base.java:632)
        at kr.co.sauce.live.broadcast.ui.StreamingActivity.onConnectionFailedRtmp$lambda-8(StreamingActivity.kt:492)
        at kr.co.sauce.live.broadcast.ui.StreamingActivity.lambda$Z7GmnHD8Gy3mD-J7qE0JEu0Uerg(Unknown Source:0)
        at kr.co.sauce.live.broadcast.ui.-$$Lambda$StreamingActivity$Z7GmnHD8Gy3mD-J7qE0JEu0Uerg.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8462)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)


There was a problem at that point when I was debugging
Camera2Base.java 

private void resetVideoEncoder() {
    if (glInterface != null) {
      glInterface.removeMediaCodecSurface();
    }
    videoEncoder.forceKeyFrame();
    if (glInterface != null) {
      glInterface.addMediaCodecSurface(videoEncoder.getInputSurface()); <--- Here
    } else {
      cameraManager.closeCamera();
      cameraManager.prepareCamera(videoEncoder.getInputSurface(), videoEncoder.getFps());
      cameraManager.openLastCamera();
    }
  }

Thanks bro

**Comment by pedroSG94** [comment]
I did a change in a branch to solve it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/glwindowsfix
Let me know if it is working for you

**Comment by welcome2c** [comment]
@pedroSG94 Sorry for the late reply I just tested it and it works thanks bro

**Comment by HirogaKatageri** [comment]
Hi @pedroSG94, so we were able to do some testing for

```java.lang.RuntimeException: drawFilter end. GL error: 1281```

What do you need for more information about the crash?

**Comment by HirogaKatageri** [comment]
We also got another issue

```
Fatal Exception: java.lang.IllegalArgumentException: bitmap is recycled
       at android.opengl.GLUtils.texImage2D(GLUtils.java:154)
       at com.pedro.encoder.input.gl.TextureLoader.load(TextureLoader.java:23)
       at com.pedro.encoder.input.gl.render.filters.object.BaseObjectFilterRender.drawFilter(BaseObjectFilterRender.java:90)
       at com.pedro.encoder.input.gl.render.filters.object.ImageObjectFilterRender.drawFilter(ImageObjectFilterRender.java:23)
       at com.pedro.encoder.input.gl.render.filters.BaseFilterRender.draw(BaseFilterRender.java:52)
       at com.pedro.encoder.input.gl.render.ManagerRender.drawOffScreen(ManagerRender.java:61)
       at com.pedro.rtplibrary.view.OffScreenGlThread.run(OffScreenGlThread.java:213)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by pedroSG94** [comment]
> Hi @pedroSG94, so we were able to do some testing for
> 
> `java.lang.RuntimeException: drawFilter end. GL error: 1281`
> 
> What do you need for more information about the crash?

I was waiting your tests without filters to know if filters could be related.

About bitmap error, this seems that you reused a bitmap but when you set a bitmap to a filter, after load it, I recycle it to preserve memory.
Maybe I should let user configure it isntead of recycle always. What do you think about it?

**Comment by HirogaKatageri** [comment]
For ```drawFilter end. GL error: 1281``` I'll try asking my colleagues to test without the filters

For the bitmap error, I think probably it could just be bad implementation on our end but just to confirm, if we're recycling it here this is how we implement it.

```
private fun showOverlay2() {
        val bitmap: Bitmap? = BitmapFactory.decodeResource(
            activity.resources,
            R.drawable.bg_privacy_land
        )

        try {
            val renderer = ImageObjectFilterRender().apply {
                setImage(bitmap)
                setScale(100f, 100f)
                setPosition(TranslateTo.CENTER)
                setAlpha(0.0f)
            }

            multiRtpDisplay?.glInterface?.setFilter(2, renderer)
        } catch (ex: Exception) {
            e(ex) { "showOverlay2(): Unable to render" }
            Crashlytics.recordException(ex)
        }
    }
```

```
private fun showOverlay0() {

        val pathUrl = URL(url)
        val inputStream: InputStream? = pathUrl.openStream()

        var bitmap: Bitmap? = bitmapFromUrl(URL)

        inputStream?.use { stream ->
                        bitmap = BitmapFactory.decodeStream(stream)
                    }

        if (bitmap != null) {
            try {
                val renderer = ImageObjectFilterRender().apply {
                    setImage(bitmap)
                    setPosition(TranslateTo.CENTER)
                    setScale(100f, 100f)
                }
                multiRtpDisplay?.glInterface?.setFilter(0, renderer)
            } catch (ex: Exception) {
                e(ex) { "showOverlay0(): Unable to render" }
                Crashlytics.recordException(ex)
            }
        }
    }
```

```
private fun showOverlay1() {
        val height: Int = multiRtpDisplay?.streamHeight ?: 0
        val width: Int = multiRtpDisplay?.streamWidth ?: 0
        if (width == 0 && height == 0) return

        val text = TextObjectFilterRender().apply {
            setText("Hi there", 23f, Color.WHITE, Typeface.DEFAULT_BOLD)

            when (rotation) {
                90, 270 -> setDefaultScale(height, width)
                else -> setDefaultScale(width, height)
            }
            setPosition(75f, 90f)
        }

        multiRtpDisplay?.glInterface?.setFilter(1, text)
    }
```

**Comment by pedroSG94** [comment]
My first suspecious is showOverlay0.
After decode bitmap from inputstream and send it to filter, this bitmap is recycled and you can't reuse it so if you call this method a second time without a valid bitmap in inputstream you are reusing it.

I recommend you create a copy of each bitmap and send that copy to filter. By this way, you can re use the original bitmap:

```java
fun copyBitmap(bitmap: Bitmap): Bitmap {
      return bitmap.copy(bitmap.config, true)
}

//now you can use it like this
val renderer = ImageObjectFilterRender().apply {
                    setImage(copyBitmap(bitmap))
                    setPosition(TranslateTo.CENTER)
                    setScale(100f, 100f)
                }
```

After that, remember recycle original bitmap when you don't need it anymore

**Comment by HirogaKatageri** [comment]
That solved most of the issues we have occurring in our app thanks for that @pedroSG94

**Comment by welcome2c** [comment]
@pedroSG94  hi pedro this issue is happening again in landscape mode, can you please check it?
