### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'void java.net.Socket.connect

### ISSUE THREAD

**Issue by Sermilion** [pedroSG94/rtmp-rtsp-stream-client-java#871]
Hi. I have got this exception in our app. Only 2 occurrences so far. But I thought this might be something that you or others experienced.
Here is a stacktrace of the exception:
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.net.Socket.connect(java.net.SocketAddress, int)' on a null object reference
       at com.github.faucamp.simplertmp.io.RtmpConnection.connect(RtmpConnection.java:137)
       at com.github.faucamp.simplertmp.DefaultRtmpPublisher.connect(DefaultRtmpPublisher.java:21)
       at net.ossrs.rtmp.SrsFlvMuxer.connect(SrsFlvMuxer.java:237)
       at net.ossrs.rtmp.SrsFlvMuxer.access$100(SrsFlvMuxer.java:53)
       at net.ossrs.rtmp.SrsFlvMuxer$2.run(SrsFlvMuxer.java:275)
       at java.lang.Thread.run(Thread.java:919)`

Phones: Realme XT and OnePlus 6.
OS Version: Android 10
Let me know if I can provide any more info and if this is something you have seen before.

**Comment by pedroSG94** [comment]
Rtmp module was migrated to kotlin and totally refactored. I have plan to update version soon with that and you error should be fixed.
