### ISSUE TITLE
SSL Exception

### ISSUE THREAD

**Issue by HirogaKatageri** [pedroSG94/rtmp-rtsp-stream-client-java#890]
Hi @pedroSG94 do you have an idea on why a server would forcibly disconnect? 

```
E/RtmpClient: disconnect error
    javax.net.ssl.SSLException: Write error: ssl=0x7851091648: I/O error during system call, Broken pipe
        at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_write(Native Method)
        at com.google.android.gms.org.conscrypt.NativeSsl.write(:com.google.android.gms@211816037@21.18.16 (120400-374723149):3)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(:com.google.android.gms@211816037@21.18.16 (120400-374723149):5)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at com.pedro.rtmp.rtmp.CommandsManager.sendClose(CommandsManager.kt:201)
        at com.pedro.rtmp.rtmp.RtmpClient.disconnect$lambda-7$lambda-6(RtmpClient.kt:417)
        at com.pedro.rtmp.rtmp.RtmpClient.lambda$GE66-2i-w_N6KG9XCLsADgTKGzQ(Unknown Source:0)
        at com.pedro.rtmp.rtmp.-$$Lambda$RtmpClient$GE66-2i-w_N6KG9XCLsADgTKGzQ.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by pedroSG94** [comment]
This could be multiple reasons like a crash, or someone stream in your stream name and close old connection
I recommend you check server logs to get info about it. Also read logs provided by my library to know if server send any command before close connection.

**Comment by pedroSG94** [comment]
Do you have this error while stream or always when you try to connect?

**Comment by HirogaKatageri** [comment]
It sometimes only happens while streaming, ```CommandsManager``` is the class we have to watch for logs right?

**Comment by pedroSG94** [comment]
Yes, this line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/pedro/rtmp/rtmp/CommandsManager.kt#L130

**Comment by HirogaKatageri** [comment]
Thanks @pedroSG94 moving forward we'll observe the logs from here, I'll close this now :)
