### ISSUE TITLE
push to FB Live-Video failed

### ISSUE THREAD

**Issue by seanbabby** [pedroSG94/rtmp-rtsp-stream-client-java#916]
I'm using DEMO App, and try to broadcast to Facebook , by use Live-Video API, but show error:

```
2021-07-27 15:24:23.264 22280-22794/com.pedro.rtpstreamer E/CreateSSLSocket: Error
2021-07-27 15:24:23.265 22280-22794/com.pedro.rtpstreamer E/RtmpClient: connection error
    java.io.IOException: Socket creation failed
        at com.pedro.rtmp.rtmp.RtmpClient.establishConnection(RtmpClient.kt:211)
        at com.pedro.rtmp.rtmp.RtmpClient.connect$lambda-1$lambda-0(RtmpClient.kt:146)
        at com.pedro.rtmp.rtmp.RtmpClient.lambda$LoJDha3-SEOOnf1PoFSNRWFIoXw(Unknown Source:0)
        at com.pedro.rtmp.rtmp.-$$Lambda$RtmpClient$LoJDha3-SEOOnf1PoFSNRWFIoXw.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

But broadcast to Youtube is success.

Facebook Live-Video API reruns this:
```
{
  "id": "4776497585698526",
  "stream_url": "rtmps://live-api-s.facebook.com:443/rtmp/4776497585698526?s_bl=1&s_psm=1&s_sw=0&s_vt=api-s&a=AbwSzD2m_r1dXR3C",
  "secure_stream_url": "rtmps://live-api-s.facebook.com:443/rtmp/4776497585698526?s_bl=1&s_psm=1&s_sw=0&s_vt=api-s&a=AbwSzD2m_r1dXR3C",
  "stream_secondary_urls": [
  ],
  "secure_stream_secondary_urls": [
  ]
}
```
So I use stream_url, but get error.
Did I need to set something that I can push to FB successful ?

**Comment by seanbabby** [comment]
Update
Finally , I found that can broadcast by fanpage's stream url,
but user's will failed, that didn't mention in doc.
