### ISSUE TITLE
Error: Unknown chunk stream id value: 63

### ISSUE THREAD

**Issue by AlexUrrutia** [pedroSG94/rtmp-rtsp-stream-client-java#917]
Hello Pedro, **I just updated to 2.0.5** and when I try to stream Live, it doesn't work and returns the following error:

`E/RtmpClient: connection error`
`java.io.IOException: Unknown chunk stream id value: 63`

It was working fine with previous versions, and no code was changed, just update to **2.0.5**
Also it doesn't work with your sample app, so I guess there is a change when sending chunks to the server? and it doesn't work on Adobe Media Server anymore?

**Server always used: Adobe Media Server 5**

Thanks!
<img width="776" alt="Screen Shot 2021-07-28 at 9 43 06 AM" src="https://user-images.githubusercontent.com/7042361/127342768-8df320ec-f61a-40b9-99f2-92c779f9cdea.png">

**Comment by jamieadkins95** [comment]
Am also seeing the same issue while trying to stream to Youtube (2.0.3 and 2.0.4 are also affected for me). On 2.0.2 I get a different error, but I think that one is on me.

**Comment by pedroSG94** [comment]
Hello,

I did a commit to fix it. Can you compile this commit and try?
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/fixheader

**Comment by AlexUrrutia** [comment]
Hello Pedro, Can you give me a Gradle Path to test this commit please? Thanks!

**Comment by pedroSG94** [comment]
implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:fixheader-SNAPSHOT'

**Comment by AlexUrrutia** [comment]
Ok, now getting this error:

`E/RtmpClient: connection error
    java.io.IOException: Unimplemented message type: null`

**Comment by pedroSG94** [comment]
This could be for multiple reason...
Can you provide me an endpoint to test it?
If possible send me to my email and you can keep it private: 
pedrossgg1994@gmail.com

**Comment by AlexUrrutia** [comment]
Sent yo your email, thank you

**Comment by pedroSG94** [comment]
I did a fix that is working in my side:
```gradle
  implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:9eba863f99'
```
Test it and le tme know if work to do a merge and update version

**Comment by AlexUrrutia** [comment]
> I did a fix that is working in my side:
> 
> ```groovy-gradle
>   implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:9eba863f99'
> ```
> 
> Test it and let me know if work to do a merge and update version

Yes, it works perfect, thank you

**Comment by Nodalailama** [comment]
Hi,

I have a similare issue since some days (I was testing the app...)

2021-08-14 08:25:49.119 11233-12604/com.xxx.android E/RtmpClient: connection error
    java.io.IOException: Unimplemented message type: null
        at com.pedro.rtmp.rtmp.message.RtmpMessage$Companion.getRtmpMessage(RtmpMessage.kt:52)
        at com.pedro.rtmp.rtmp.CommandsManager.readMessageResponse(CommandsManager.kt:128)
        at com.pedro.rtmp.rtmp.RtmpClient.handleMessages(RtmpClient.kt:235)
        at com.pedro.rtmp.rtmp.RtmpClient.connect$lambda-1$lambda-0(RtmpClient.kt:155)
        at com.pedro.rtmp.rtmp.RtmpClient.lambda$LoJDha3-SEOOnf1PoFSNRWFIoXw(Unknown Source:0)
        at com.pedro.rtmp.rtmp.-$$Lambda$RtmpClient$LoJDha3-SEOOnf1PoFSNRWFIoXw.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-08-14 08:25:49.120 11233-12604/com.xxx.android W/Broadcast Fragment: RTMP Connection Failure
2021-08-14 08:25:49.132 11233-12653/com.xxx.android E/RtmpClient: disconnect error
    java.net.SocketException: Socket closed
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:124)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:161)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at com.pedro.rtmp.rtmp.CommandsManager.sendClose(CommandsManager.kt:201)
        at com.pedro.rtmp.rtmp.RtmpClient.disconnect$lambda-7$lambda-6(RtmpClient.kt:417)
        at com.pedro.rtmp.rtmp.RtmpClient.lambda$GE66-2i-w_N6KG9XCLsADgTKGzQ(Unknown Source:0)
        at com.pedro.rtmp.rtmp.-$$Lambda$RtmpClient$GE66-2i-w_N6KG9XCLsADgTKGzQ.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)

Using implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:9eba863f99' not change the error.

Cordialement,

**Comment by pedroSG94** [comment]
Which server are you using?

**Comment by Nodalailama** [comment]
I am using mux.com, Right now I am testing with iphone, to be sure my backend and the mux endpoint is okay, then I will come back android testing. I am testing a new endpoint so was wondering if it has an error but iphone seems to work well...

Previously, it was working ... but now, it's not. I will come back to you with more info on this day.

**Comment by pedroSG94** [comment]
Did you updated library? 
Let me know old version and actual version to compare. Also, today I did a fix that could be related to your case. Please, compile app example with last commit to comfirm that you still have the problem.

If you possible open a new issue because sometimes I can miss comments in a closed issue because I could forget that a closed issue is active (I usually check it in open issues). You can write a link to this issue if you think that your case is related.

**Comment by Nodalailama** [comment]
It was a typo from me: I change the rtmp url ... and forget a "/" at the end...
Thanks for quickly answer.
