### ISSUE TITLE
Amazon IVS unimplemented message type (Error: Unknown chunk stream id value: 63)

### ISSUE THREAD

**Issue by yunusefendi52** [pedroSG94/rtmp-rtsp-stream-client-java#919]
I am using Amazon IVS to live streaming, I don't know if this is related to #917 but after tried the latest version (v2.0.6) I got an error "unimplemented message type" previously is the same as #917, the full logs:

```
D/ForceDarkHelper: updateByCheckExcludeList: pkg: com.pedro.rtpstreamer activity: com.pedro.rtpstreamer.customexample.RtmpActivity@9d622c6
D/ForceDarkHelper: updateByCheckExcludeList: pkg: com.pedro.rtpstreamer activity: com.pedro.rtpstreamer.customexample.RtmpActivity@9d622c6
D/TAG_R: b_start_stop: 
W/BpBinder: Slow Binder: BpBinder transact took 204 ms, interface=android.hardware.ICamera, code=1 oneway=false
W/VideoCapabilities: Unsupported mime video/divx
W/VideoCapabilities: Unsupported mime video/divx311
W/VideoCapabilities: Unsupported mime video/divx4
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities: Unsupported mime video/x-ms-wmv
W/VideoCapabilities: Unsupported mime video/x-ms-wmv
W/Utils: could not parse long range '175-174'
I/VideoEncoder: 3 encoders found
I/VideoEncoder: Encoder OMX.qcom.video.encoder.avc
    Color supported: 2141391876
I/VideoEncoder: Color supported: 2130708361
    Color supported: 2135033992
    Color supported: 21
    Encoder selected OMX.qcom.video.encoder.avc
I/OMXClient: IOmx service obtained
I/VideoEncoder: Prepare video info: YUV420SEMIPLANAR, 480x800
    bitrate mode CBR not supported using default mode
I/ExtendedACodec: setupVideoEncoder()
W/OMXUtils: do not know color format 0x7fa30c04 = 2141391876
    do not know color format 0x7f000789 = 2130708361
I/ACodec: setupAVCEncoderParameters with [profile: High] [level: Level31]
I/ACodec: [OMX.qcom.video.encoder.avc] cannot encode HDR static metadata. Ignoring.
    setupVideoEncoder succeeded
I/ExtendedACodec: [OMX.qcom.video.encoder.avc] configure, AMessage : AMessage(what = 'conf', target = 1) = {
      int32_t color-format = 21
      int32_t i-frame-interval = 2
      string mime = "video/avc"
      int32_t width = 480
      int32_t bitrate = 921600
      int32_t max-input-size = 0
      int32_t frame-rate = 30
      int32_t height = 800
      int32_t encoder = 1
    }
W/ExtendedACodec: Failed to get extension for extradata parameter
I/VideoEncoder: prepared
I/MicrophoneManager: Microphone created, 44100hz, Stereo
I/AudioEncoder: 2 encoders found
    Encoder OMX.google.aac.encoder
    Encoder c2.android.aac.encoder
    Encoder selected c2.android.aac.encoder
D/CCodec: allocate(c2.android.aac.encoder)
I/Codec2Client: Available Codec2 services: "software"
    Creating a Codec2 client to service "software"
I/Codec2Client: Client to Codec2 service "software" created
I/CCodec: Created component [c2.android.aac.encoder]
D/CCodecConfig: read media type: audio/mp4a-latm
D/ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater: extent() != 1 for single value type: output.subscribed-indices.values
    extent() != 1 for single value type: input.buffers.allocator-ids.values
    extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.allocator-ids.values
    extent() != 1 for single value type: output.buffers.pool-ids.values
    extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig: query failed after returning 9 values (BAD_INDEX)
D/CCodecConfig: c2 config is Dict {
      c2::u32 coded.bitrate.value = 64000
      c2::u32 coded.pl.level = 0
      c2::u32 coded.pl.profile = 8192
      c2::u32 coding.aac-sbr-mode.value = 3
      c2::u32 input.buffers.max-size.value = 2048
      c2::u32 input.delay.value = 0
      string input.media-type.value = "audio/raw"
      string output.media-type.value = "audio/mp4a-latm"
      c2::u32 raw.channel-count.value = 1
      c2::u32 raw.sample-rate.value = 44100
    }
D/CCodecConfig: no c2 equivalents for aac-profile
    no c2 equivalents for encoder
D/CCodecConfig: c2 config is Dict {
      c2::u32 coded.bitrate.value = 98304
      c2::u32 coded.pl.level = 0
      c2::u32 coded.pl.profile = 8192
      c2::u32 coding.aac-sbr-mode.value = 3
      c2::u32 input.buffers.max-size.value = 4096
      c2::u32 input.delay.value = 0
      string input.media-type.value = "audio/raw"
      string output.media-type.value = "audio/mp4a-latm"
      c2::u32 raw.channel-count.value = 2
      c2::u32 raw.sample-rate.value = 44100
    }
W/Codec2Client: query -- param skipped: index = 1107298332.
D/CCodec: setup formats input: AMessage(what = 0x00000000) = {
      int32_t channel-count = 2
      int32_t max-input-size = 7104
      string mime = "audio/raw"
      int32_t sample-rate = 44100
    } and output: AMessage(what = 0x00000000) = {
      int32_t bitrate = 98304
      int32_t channel-count = 2
      int32_t level = 0
      int32_t max-bitrate = 98304
      string mime = "audio/mp4a-latm"
      int32_t profile = 2
      int32_t sample-rate = 44100
    }
I/AudioEncoder: prepared
I/VideoEncoder: started
I/MediaCodec: MediaCodec will operate in async mode
I/AudioEncoder: started
I/MediaCodec: MediaCodec will operate in async mode
W/Codec2Client: query -- param skipped: index = 1342179345.
    query -- param skipped: index = 2415921170.
D/CCodecBufferChannel: [c2.android.aac.encoder#953] Created input block pool with allocatorID 16 => poolID 17 - OK (0)
I/CCodecBufferChannel: [c2.android.aac.encoder#953] Created output block pool with allocatorID 16 => poolID 108 - OK
D/CCodecBufferChannel: [c2.android.aac.encoder#953] Configured output block pool ids 108 => OK
E/ion: ioctl c0044901 failed with code -1: Invalid argument
D/AudioService: broadcastRecorderState:com.pedro.rtpstreamer
I/MicrophoneManager: Microphone started
E/libc: Access denied finding property "vendor.camera.hal1.packagelist"
W/dro.rtpstreamer: type=1400 audit(0.0:374459): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=14606 scontext=u:r:untrusted_app:s0:c36,c260,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
D/Camera: Lct package name is com.pedro.rtpstreamer
W/dro.rtpstreamer: type=1400 audit(0.0:374462): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=14597 scontext=u:r:untrusted_app:s0:c36,c260,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
I/Camera1ApiManager: 800X480
W/Looper: Slow Looper main: Long Msg: seq=1638 plan=20:38:11.091  late=3ms wall=1627ms running=419ms runnable=29ms io=149ms h=android.view.ViewRootImpl$ViewRootHandler c=android.view.View$PerformClick
I/Choreographer: Skipped 97 frames!  The application may be doing too much work on its main thread.
W/Looper: Slow Looper main: doFrame is 1626ms late because of 3 msg, msg 1 took 1627ms (seq=1638 running=419ms runnable=29ms io=149ms late=3ms h=android.view.ViewRootImpl$ViewRootHandler c=android.view.View$PerformClick)
I/OpenGLRenderer: Davey! duration=1651ms; Flags=0, IntendedVsync=447765533021448, Vsync=447767149688050, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=447767159547918, AnimationStart=447767159710678, PerformTraversalsStart=447767159712970, DrawStart=447767178233751, SyncQueued=447767181868074, SyncStart=447767182237345, IssueDrawCommandsStart=447767182385782, SwapBuffers=447767184224688, FrameCompleted=447767185326615, DequeueBufferDuration=341000, QueueBufferDuration=545000, 
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/RtmpClient: send sps and pps
I/Handshake: writing C0
    C0 write successful
    writing C1
    writing time 1627738693 to c1
    writing zero to c1
    writing random to c1
I/Handshake: C1 write successful
I/Handshake: reading S0
I/Handshake: read S0 successful
    reading S1
I/Handshake: read S1 successful
    writing C2
    C2 write successful
    reading S2
I/Handshake: read S2 successful
I/CommandsManager: send Command(name='connect', transactionId=1, timeStamp=0, streamId=0, data=[AmfString value: connect, AmfNumber value: 1.0, AmfObject properties: {AmfString value: app=AmfString value: , AmfString value: flashVer=AmfString value: FMLE/3.0 (compatible; Lavf57.56.101), AmfString value: swfUrl=AmfString value: , AmfString value: tcUrl=AmfString value: , AmfString value: fpad=AmfBoolean value: false, AmfString value: capabilities=AmfNumber value: 239.0, AmfString value: audioCodecs=AmfNumber value: 3191.0, AmfString value: videoCodecs=AmfNumber value: 252.0, AmfString value: videoFunction=AmfNumber value: 1.0, AmfString value: pageUrl=AmfString value: , AmfString value: objectEncoding=AmfNumber value: 0.0}], bodySize=407)
I/CommandsManager: read WindowAcknowledgementSize(acknowledgementWindowSize=2500000)
I/CommandsManager: read SetPeerBandwidth(acknowledgementWindowSize=2500000, type=DYNAMIC)
I/CommandsManager: read UserControl(type=STREAM_BEGIN, event=Event(data=0, bufferLength=-1), bodySize=6)
I/RtmpClient: user control command STREAM_BEGIN ignored
I/CommandsManager: read SetChunkSize(chunkSize=4096)
I/RtmpClient: chunk size configured to 4096
I/CommandsManager: read Command(name='_result', transactionId=1, timeStamp=0, streamId=0, data=[AmfString value: _result, AmfNumber value: 1.0, AmfObject properties: {AmfString value: fmsVer=AmfString value: FMS/3,5,7,7009, AmfString value: capabilities=AmfNumber value: 31.0, AmfString value: mode=AmfNumber value: 1.0}, AmfObject properties: {AmfString value: level=AmfString value: status, AmfString value: code=AmfString value: NetConnection.Connect.Success, AmfString value: description=AmfString value: Connection accepted., AmfString value: data=AmfObject properties: {AmfString value: string=AmfString value: 3,5,7,7009}, AmfString value: objectEncoding=AmfNumber value: 0.0}], bodySize=236)
I/CommandsManager: send Command(name='releaseStream', transactionId=2, timeStamp=0, streamId=0, data=[AmfString value: releaseStream, AmfNumber value: 2.0, AmfNull, AmfString value: ], bodySize=29)
I/CommandsManager: send Command(name='FCPublish', transactionId=3, timeStamp=0, streamId=0, data=[AmfString value: FCPublish, AmfNumber value: 3.0, AmfNull, AmfString value: ], bodySize=25)
I/CommandsManager: send Command(name='createStream', transactionId=4, timeStamp=0, streamId=0, data=[AmfString value: createStream, AmfNumber value: 4.0, AmfNull], bodySize=25)
I/RtmpClient: success response received from connect
I/CommandsManager: read Command(name='onFCPublish', transactionId=0, timeStamp=0, streamId=0, data=[AmfString value: onFCPublish, AmfNumber value: 0.0, AmfNull, AmfObject properties: {AmfString value: level=AmfString value: status, AmfString value: code=AmfString value: NetStream.Publish.Start, AmfString value: description=AmfString value: FCPublish to stream }], bodySize=112)
I/RtmpClient: unknown onFCPublish response received from unknown command
I/CommandsManager: read Command(name='_result', transactionId=4, timeStamp=0, streamId=0, data=[AmfString value: _result, AmfNumber value: 4.0, AmfNull, AmfNumber value: 1.0], bodySize=29)
I/CommandsManager: send Command(name='publish', transactionId=5, timeStamp=0, streamId=1, data=[AmfString value: publish, AmfNumber value: 5.0, AmfNull, AmfString value: , AmfString value: live], bodySize=30)
I/RtmpClient: success response received from createStream
I/CommandsManager: read UserControl(type=STREAM_BEGIN, event=Event(data=1, bufferLength=-1), bodySize=6)
I/RtmpClient: user control command STREAM_BEGIN ignored
E/RtmpClient: connection error
    java.io.IOException: Unimplemented message type: null
        at com.pedro.rtmp.rtmp.message.RtmpMessage$Companion.getRtmpMessage(RtmpMessage.kt:52)
        at com.pedro.rtmp.rtmp.CommandsManager.readMessageResponse(CommandsManager.kt:128)
        at com.pedro.rtmp.rtmp.RtmpClient.handleMessages(RtmpClient.kt:235)
        at com.pedro.rtmp.rtmp.RtmpClient.connect$lambda-1$lambda-0(RtmpClient.kt:155)
        at com.pedro.rtmp.rtmp.RtmpClient.lambda$LoJDha3-SEOOnf1PoFSNRWFIoXw(Unknown Source:0)
        at com.pedro.rtmp.rtmp.-$$Lambda$RtmpClient$LoJDha3-SEOOnf1PoFSNRWFIoXw.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:67)
D/ForceDarkHelper: updateByCheckExcludeList: pkg: com.pedro.rtpstreamer activity: com.pedro.rtpstreamer.customexample.RtmpActivity@9d622c6
D/ForceDarkHelper: updateByCheckExcludeList: pkg: com.pedro.rtpstreamer activity: com.pedro.rtpstreamer.customexample.RtmpActivity@9d622c6
I/CommandsManager: send Command(name='closeStream', transactionId=6, timeStamp=0, streamId=1, data=[AmfString value: closeStream, AmfNumber value: 6.0, AmfNull], bodySize=24)
D/ForceDarkHelper: updateByCheckExcludeList: pkg: com.pedro.rtpstreamer activity: com.pedro.rtpstreamer.customexample.RtmpActivity@9d622c6
D/ForceDarkHelper: updateByCheckExcludeList: pkg: com.pedro.rtpstreamer activity: com.pedro.rtpstreamer.customexample.RtmpActivity@9d622c6
D/AudioService: broadcastRecorderState:com.pedro.rtpstreamer
    broadcastRecorderState:com.pedro.rtpstreamer
I/MicrophoneManager: Microphone stopped
I/VideoEncoder: stopped
I/AudioEncoder: stopped
D/CCodecBuffers: [c2.android.aac.encoder#953:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 0
    [c2.android.aac.encoder#953:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 1
I/Toast: Show toast from OpPackageName:com.pedro.rtpstreamer, PackageName:com.pedro.rtpstreamer
I/Toast: Show toast from OpPackageName:com.pedro.rtpstreamer, PackageName:com.pedro.rtpstreamer

```

If you would like to investigate more, I can send you IVS rtmps link in private
and also please try settings (as low as possible because I limit the settings)
resolution: 800x480
bitrate: 1000 kbps

**Comment by pedroSG94** [comment]
Yes, please send me an email with the endpoint and I will check it

**Comment by yunusefendi52** [comment]
Sent you the link in email
I tried the last 4 (2.0.2 through 2.0.5) and also v1 (forgot which ones) but none of these worked

**Comment by yunusefendi52** [comment]
sorry, accidentaly closed

**Comment by pedroSG94** [comment]
I haven't any email with the endpoint. Make sure that you write the email properly:
pedrossgg1994@gmail.com

**Comment by yunusefendi52** [comment]
Just sent you with my gmail account, previously I used outlook mail

**Comment by pedroSG94** [comment]
Hello,

The problem is that your url endpoint is malformed.
Following this guide you can stream like this:
https://aws.amazon.com/es/blogs/media/metfc-simplifying-live-streaming-contribution-amazon-ivs/

So your endpoint should be like this (replace xxx for your correct string in your case):
```java
rtmps://xxx.global-contribute.live-video.net:443/app/sk_eu-west-xxx
```

**Comment by yunusefendi52** [comment]
Oh yeah it's working now with /app, thank you for your help
