### ISSUE TITLE
the camera constantly flickers (in any state)

### ISSUE THREAD

**Issue by Igor755** [pedroSG94/rtmp-rtsp-stream-client-java#929]
Htc u ultra
Android 8.0.0

https://user-images.githubusercontent.com/25371495/131532227-7fa012df-c436-4761-866f-c249030b41dc.mp4

**Comment by pedroSG94** [comment]
Hello,

Did you tried camera1, camera2 and multiple resolutions?

**Comment by Igor755** [comment]
Hi, RtmpCamera1. As in the example

**Comment by pedroSG94** [comment]
Hello,

Please, follow this to discard possible reasons:
- Check that video with default app aplication is working fine to discard hardware problems.
- Compile my example app and check default example and opengl example to discard problems with opengl.
- Try with camera2, using another resolution and another fps values to discard a problems with a specific config.
- Record a video and start a stream with my library to discard problems only in preview.

**Comment by Igor755** [comment]
1) Camera on device working normal in standart gallery or another app.
2) Camera2 work withhout flicks but when i start record, its freezzy (stop, dont move). Record is Live, but camera freezzy(stop, dont move)
3) Camera1 have flicks and when i start record have flicks too. I looking video on server its have problem with voice (interruptions) and video with squars.
4) Camera1 have flicks with any parameters (720,1080 e.t.c)

**Comment by pedroSG94** [comment]
Ok, lets try fix point 2 because I think that your device has a problem with camera1 api configuration and I can't find anything on internet.
Are you using camera2 with openglview?
Can you share a full logcat of Camera2ApiManager?

**Comment by pedroSG94** [comment]
I found that maybe you have a problem with autofocus in htc using camera1. Try disable it using:
```java
    rtmpCamera1.disableAutoFocus();
```
This must be called after startPreview.

**Comment by Igor755** [comment]
![image](https://user-images.githubusercontent.com/25371495/131869040-d226c4c8-d6dc-41f2-ac2f-e76b2e14bd62.png)
camera2 without openglview. If i use openglview i get a black screen)

**Comment by Igor755** [comment]
autofocus dont help(

**Comment by pedroSG94** [comment]
Hello,

Please, share me logs using my last library version. 
One log with openglview and other log without openglview

**Comment by Igor755** [comment]
[withOpenGL.docx](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/7101724/withOpenGL.docx)
[withoutOpenGL.docx](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/7101725/withoutOpenGL.docx)

**Comment by pedroSG94** [comment]
I can't see any log of CameraApi.
Make sure that you get all logcat of Camera2ApiManager

**Comment by Igor755** [comment]
![image](https://user-images.githubusercontent.com/25371495/131975288-4dafe149-5a4e-48d1-87d5-3cc07ce2a2e8.png)

without opengl

**Comment by pedroSG94** [comment]
Do you have any logs with opengl?

**Comment by Igor755** [comment]
Now, i create view -  <com.pedro.rtplibrary.view.OpenGlView
use RtmpCamera1

surfaceView.holder.addCallback(this)
// Setup the camera
rtmpCamera = RtmpCamera1(surfaceView, this)

And i get normal stream))) and on server video is nice)))
But in next video , audio is gone and sometimes i get error

**Comment by Igor755** [comment]
E/BufferQueueProducer: [SurfaceTexture-1-31066-5] queueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer: [SurfaceTexture-1-31066-5] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer: [SurfaceTexture-1-31066-5] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer: [SurfaceTexture-1-31066-5] cancelBuffer: BufferQueue has been abandoned
E/SurfaceManager: GL already released
E/libc: Access denied finding property "camera.hal1.packagelist"
E/Camera1Base: Streaming or preview stopped, ignored
E/android.media.AudioRecord: stop() called on an uninitialized AudioRecord.
E/SurfaceManager: eglSwapBuffers failed
E/SurfaceManager: eglMakeCurrent failed
E/GLConsumer: [SurfaceTexture-1-31066-7] checkAndUpdateEglState: invalid current EGLContext
E/BufferQueueProducer: [SurfaceTexture-1-31066-7] queueBuffer: BufferQueue has been abandoned
E/libEGL: eglTerminate:319 error 3008 (EGL_BAD_DISPLAY)
E/AndroidRuntime: FATAL EXCEPTION: glThread
    Process: com.ollie_tech.app.dev, PID: 31066
    java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
        at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
        at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:243)
        at com.pedro.encoder.input.gl.render.CameraRender.updateTexImage(CameraRender.java:115)
        at com.pedro.encoder.input.gl.render.ManagerRender.updateFrame(ManagerRender.java:88)
        at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:133)
        at java.lang.Thread.run(Thread.java:764)
E/libEGL: eglTerminate:319 error 3008 (EGL_BAD_DISPLAY)

**Comment by pedroSG94** [comment]
Did you test in my app example?
Can you share me code used?

**Comment by Igor755** [comment]
Ok, thanks)

https://github.com/Igor755/ExampleStream

Please look, Did I do everything right?

 rtmpCamera!!.startPreview() - this is call without parameters, its true?

**Comment by pedroSG94** [comment]
Ok,

You audio problem could be because you are doing prepareVideo/Audio 2 times:
https://github.com/Igor755/ExampleStream/blob/master/app/src/main/java/com/example/muxlive/BroadcastActivity.java#L179

You don't need call it because you already called it here:
https://github.com/Igor755/ExampleStream/blob/master/app/src/main/java/com/example/muxlive/BroadcastActivity.java#L165

prepareVideo/Audio without params is doing this:

When you call this method without params the configuration selected is your last configuration. If you never used any configuration, Your are using default values from VideoEncoder (640, 480, 30, 1200 * 1024,  2,  CameraHelper.getCameraOrientation(this)) / AudioEncoder (64 * 1024, 32000, true).

So in Your case this code:
```java
// Configure the stream using the configured preset
            rtmpCamera.prepareVideo(
                    preset.width,
                    preset.height,
                    preset.frameRate,
                    preset.bitrate,
                    2, // Fixed 2s keyframe interval
                    CameraHelper.getCameraOrientation(this)
            );
            rtmpCamera.prepareAudio(
                    128 * 1024, // 128kbps
                    48000, // 48k
                    true // Stereo
            );

            if (rtmpCamera.prepareAudio() && rtmpCamera.prepareVideo()) {
                rtmpCamera.startStream(rtmpEndpoint + streamKey);
            } else {
                /**This device cant init encoders, this could be for 2 reasons:
                 * The encoder selected doesnt support any configuration setted
                 * or your device hasnt a H264 or AAC encoder (in this case you
                 * can see log error valid encoder not found)*/
            }
```

It is like:
```java
// Configure the stream using the configured preset
            rtmpCamera.prepareVideo(
                    preset.width,
                    preset.height,
                    preset.frameRate,
                    preset.bitrate,
                    2, // Fixed 2s keyframe interval
                    CameraHelper.getCameraOrientation(this)
            );
            rtmpCamera.prepareAudio(
                    128 * 1024, // 128kbps
                    48000, // 48k
                    true // Stereo
            );

            if (rtmpCamera.prepareAudio(
                    128 * 1024, // 128kbps
                    48000, // 48k
                    true // Stereo
            ) &&  rtmpCamera.prepareVideo(
                    preset.width,
                    preset.height,
                    preset.frameRate,
                    preset.bitrate,
                    2, // Fixed 2s keyframe interval
                    CameraHelper.getCameraOrientation(this)
            )) {
                rtmpCamera.startStream(rtmpEndpoint + streamKey);
            } else {
                /**This device cant init encoders, this could be for 2 reasons:
                 * The encoder selected doesnt support any configuration setted
                 * or your device hasnt a H264 or AAC encoder (in this case you
                 * can see log error valid encoder not found)*/
            }
```

StartPreview is exactly the same that prepareVideo.
If you call it without params it is like:
```java
    rtmpCamera1.startPreview(CameraHelper.Facing.BACK, 640, 480, CameraHelper.getCameraOrientation(this));
```

**Comment by pedroSG94** [comment]
Also, this thread is not necessary:
https://github.com/Igor755/ExampleStream/blob/master/app/src/main/java/com/example/muxlive/BroadcastActivity.java#L133

**Comment by pedroSG94** [comment]
It is recomendable use my app example first to discard problems with your code before start your implementation in your own project.

**Comment by Igor755** [comment]
Thanks, man) You very strong helped me. You is better) i try in monday, сorrect my mistakes.

**Comment by Igor755** [comment]
Hello, Can i change voice in live stream video (mute, unmute)?

**Comment by pedroSG94** [comment]
Yes:
```java
rtmpCamera1.disableAudio();
rtmpCamera1.enableAudio();
```

**Comment by Igor755** [comment]
all good, but sometimes i get error 

E/AndroidRuntime: FATAL EXCEPTION: glThread
java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
        at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
        at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:243)
        at com.pedro.encoder.input.gl.render.CameraRender.updateTexImage(CameraRender.java:115)
        at com.pedro.encoder.input.gl.render.ManagerRender.updateFrame(ManagerRender.java:88)
        at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:133)
        at java.lang.Thread.run(Thread.java:764)
E/BufferQueueProducer: [SurfaceTexture-1-4338-3] queueBuffer: BufferQueue has been abandoned

**Comment by Igor755** [comment]
![image](https://user-images.githubusercontent.com/25371495/132232113-608ccd99-ad8c-4136-8b27-90a96c5b2dd6.png)

when i press button live, and get error sometimes, not always

**Comment by pedroSG94** [comment]
Hello,

This is an opengl error that could be related with glcontext that is not working properly.
I will need send you few commits to test because I'm not able to reproduce your case.

First of all I need a logcat with more information. Can you send me all logs of the app when you get this error? 
The most relevant class are OpenGlView and SurfaceManager but if possible send me all app logs to know the moment of crash.
Please try reproduce the error in my app example to know code implementation.

**Comment by Igor755** [comment]
Hello, i think i decide problem in my code (need testing). And I have question, Can i restore stream (restore connect), if i press home button(example) and back to app through several minute?

**Comment by pedroSG94** [comment]
You can start stream inmediatelly without user interation after activity come to foreground calling it in this callback:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L485
To know if you need start stream or not when you press home (for example only start automatically if you was streaming previously), you will need save a variable that keep alive when app/activity is closed and change it in any required situation (in SharedPreferences or a DB for example). 
You can use this post to detect home press and change that variable if required:
https://stackoverflow.com/questions/8881951/detect-home-button-press-in-android

**Comment by Igor755** [comment]
Thanks, and sorry , but i have next question) Can i monitor stream frame-rate and change every second? 

Example:

    - if the AVERAGE(frame rates) < 27
    - Multiply the bitrate by 0.7, but don't lower the bitrate below 0.3 Mbps

**Comment by pedroSG94** [comment]
Yes, you can get fps with this:
```java
rtmpCamera1.setFpsListener(new FpsListener.Callback() {
      @Override
      public void onFps(int fps) {
        
      }
    });
```
And change fps if you are using OpenGlView with this:
```java
    openGlView.setFps();
```

**Comment by pedroSG94** [comment]
This last one (change fps to openglview) is not supposed to be change normally so it could produce few problems like reduce the num of keyframes because encoder es still configured to 30fps but normally it isn't really important.
I recommend you test it really well before implement it in your project (because it is not tested to be used to change it on fly) and report me problems.

**Comment by Igor755** [comment]
ok, thanks. And when i can change bitrate?

**Comment by pedroSG94** [comment]
Check this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Adaptative-video-bitrate

**Comment by Igor755** [comment]
nice, thanks

**Comment by Igor755** [comment]
All working, thanks. New question - in you library change bitrate if fps is changed? I try create adaptive algorithm, it is work is bad.
`rtmpCamera?.setFpsListener(FpsListener.Callback { frame_rate ->
            var change_bitrate = 0
            current_bitrate = rtmpCamera?.bitrate!!
            if (frame_rate < 27 ){
                change_bitrate = (current_bitrate * 0.7).toInt()
                //0.3 mb/s
                if(change_bitrate > 307200){
                    rtmpCamera?.setVideoBitrateOnFly(change_bitrate)
                }
            }
            if (frame_rate > 29.5){
                change_bitrate = (current_bitrate * 1.5).toInt()
                //3 mb/s
                if(change_bitrate < 3072000){
                    rtmpCamera?.setVideoBitrateOnFly(change_bitrate)
                }
            }
        })`

**Comment by pedroSG94** [comment]
No, the library keep bitrate constant if you don't use adaptative bitrate and with adaptative bitrate only cache size is related with change bitrate.

I don't know want do you want but if you want keep bitrate constant to preserve quality this is easier:
```kotlin
    val bitrateUsedInPrepareVideo = 3000000 //3mb
    val fpsUsedInPrepareVideo = 30
    rtmpCamera?.setFpsListener(FpsListener.Callback { frame_rate ->
      //This means that if you have 15fps, bitrate = 1.5mb. 20 fps = 2mb.
      //30 fps is the limit so keep bitrate constant 3000000 * 30 / 30 = 3000000 (3mb)
      val bitrate = bitrateUsedInPrepareVideo * frame_rate / fpsUsedInPrepareVideo
      rtmpCamera?.setVideoBitrateOnFly(bitrate)
    })
```

**Comment by Igor755** [comment]
Thanks, man. All working. I close issue

**Comment by user97116** [comment]
I tried recording it's works fine 
```java
 rtmpCamera1.prepareAudio();
  rtmpCamera1.prepareVideo(rWidth, rHeight, fps, 6500 * 1024, 0);
  rtmpCamera1.setExposure(exposure);
  rtmpCamera1.startRecord(path);
```
but when I try start stream
```java
rtmpCamera1.prepareVideo(1920,1080,1024*1024);
rtmpCamera1.startStream(url);
```

giving me
eglSwapBuffers failed
egl_window_surface_t::swapBuffers called with NULL buffer
tid 11917: swapBuffers(772): error 0x300d (EGL_BAD_SURFACE)
eglSwapBuffers failed

**Comment by pedroSG94** [comment]
Hello,

Please, open a new issue and provide a full code example to reproduce your case
