### ISSUE TITLE
Crash when setting numFilters and calling setFilter multiple times (v2.1.3)

### ISSUE THREAD

**Issue by florianmlr** [pedroSG94/rtmp-rtsp-stream-client-java#966]
Hello,
After updating the library from the version v2.0.2 to the v2.1.3 I'm facing with a new crash :
```
Fatal Exception: java.lang.RuntimeException
limit of filters(1) exceeded
com.pedro.encoder.input.gl.render.ManagerRender.setFilterAction (ManagerRender.java:167)
com.pedro.rtplibrary.view.OpenGlView.run (OpenGlView.java:195)
java.lang.Thread.run (Thread.java:762)
``` 
and

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.pedro.encoder.input.gl.render.ManagerRender.setFilter(ManagerRender.java:108)
        at com.pedro.encoder.input.gl.render.ManagerRender.setFilterAction(ManagerRender.java:164)
        at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:195)
```

To reproduce it , I used the BackgroundActivity example setting the `numFilters` to 1 and launch a coroutine scoped to the surfaceview which calls the `setFilter` method every second and by putting the application in the background and then bringing it to the foreground, I could reproduce the crash (not every time)
```
override fun surfaceChanged(holder: SurfaceHolder, p1: Int, p2: Int, p3: Int) {
RtpService.setView(surfaceView)
RtpService.startPreview()
job = CoroutineScope(Job() + Dispatchers.Main)
    job?.launch {
      while(isActive) {
        delay(1000)
        RtpService.setFilter()
      }
    } // cancel it in surface destroy
```
The setFilter method in RtpService : 
```
fun setFilter() {
      camera2Base?.glInterface?.setFilter(BasicDeformationFilterRender())
    }
```

**Comment by pedroSG94** [comment]
I can't reproduce it.
I did this changes:
```kotlin
  private var job: CoroutineScope? = null

  override fun surfaceChanged(holder: SurfaceHolder, p1: Int, p2: Int, p3: Int) {
    RtpService.setView(surfaceView)
    RtpService.startPreview()
    job = CoroutineScope(Job() + Dispatchers.Main)
    job?.launch {
      while(isActive) {
        delay(500)
        RtpService.setFilter()
      }
    } // cancel it in surface destroy
  }

  override fun surfaceDestroyed(holder: SurfaceHolder) {
    RtpService.setView(applicationContext)
    RtpService.stopPreview()
    job?.cancel()
  }
```
How did you set numFilters to 1?
Can you share me all code in BackgroundActivity class?

**Comment by florianmlr** [comment]
By setting it in the xml file : 
```
<com.pedro.rtplibrary.view.OpenGlView
      android:id="@+id/surfaceView"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      app:numFilters="1"/>
```
I don't have more code than you, i can't reproduce it every time, often I have to put the application in background then foreground more than ten times but that's the only way I could reproduce it, it's not a common use case I agree.

**Comment by pedroSG94** [comment]
I could reproduce it and now it is fixed in:
cb8c8fcdad4e8454cb88339fcd0f28c6d51e6f87
Test it and re open the issue if the problem persist.

**Comment by florianmlr** [comment]
It's fixed, thank you !
